### ISSUE TITLE
How to mark up an electronic issue?

### ISSUE THREAD

**Issue by truschel** [plazi/community#10]
How we should mark up electronic issue in "Add document Meta data"?
The GGI is not accepting electronic issue with "e" in the beginning.

![image](https://user-images.githubusercontent.com/57402704/74962069-f0c4b800-53ed-11ea-9bf3-9abd384635c4.png)

**Comment by myrmoteras** [comment]
need be discussed. e can not be in an issue- unless Guido changed. so just use for the volume (part) the number without the e for the moment. It is being discussed

**Comment by mguidoti** [comment]
Guido already implemented the solution (pagination will accept these electronic issues) and it's coming in the next build.
