### ISSUE TITLE
test processing

### ISSUE THREAD

**Issue by peteruetz** [plazi/community#100]
[2021 Pelodiscus Anhui.pdf](https://github.com/plazi/community/files/7650974/2021.Pelodiscus.Anhui.pdf)
might it be possible this could be processed, Thanks :)

**Comment by flsimoes** [comment]
Hi @peteruetz 

This one has already been processed, please see the link below:

https://tb.plazi.org/GgServer/summary/FF8C9D29FFE2FFA2FFC1E175FF88FFFB

**Comment by peteruetz** [comment]
Thanks - you got this paper already :)
