### ISSUE TITLE
Engelbrecht 2021, https://doi.org/10.7717/peerj.117

### ISSUE THREAD

**Issue by peteruetz** [plazi/community#101]
Can you please process this article, Thanks, Peter

Engelbrecht, H. M., Branch, W. R., & Tolley, K. A. 2021
Snakes on an African plain: the radiation of Crotaphopeltis and Philothamnus into open habitat (Serpentes: Colubridae).
PeerJ, 9: e11728
https://doi.org/10.7717/peerj.117

[Engelbrecht 2021 Crotaphopeltis Philothamnus.pdf](https://github.com/plazi/community/files/7651088/Engelbrecht.2021.Crotaphopeltis.Philothamnus.pdf)
28

**Comment by flsimoes** [comment]
Thanks for the PDF. Will process it asap.

**Comment by flsimoes** [comment]
Just processed the paper.
Since it has no treatments the article's page on TB will show a "No treatments" screen instead.

UUID: 3625FFFADF0709707D7BFFF347473E47
https://tb.plazi.org/GgServer/summary/3625FFFADF0709707D7BFFF347473E47

Should be up in Zenodo shortly.

**Comment by myrmoteras** [comment]
article in BLR
https://zenodo.org/record/5753075

figures:
https://doi.org/10.5281/zenodo.5753079

https://doi.org/10.5281/zenodo.5753077

**Comment by flsimoes** [comment]
Not sure why it's showing up as `Closed Access` on Zenodo though. The IMF has the correct CC-BY license.

**Comment by flsimoes** [comment]
Here's a stats page with the results from the extraction:

https://tb.plazi.org/GgServer/dioStats/stats?outputFields=doc.articleUuid+doc.name+doc.doi+doc.zenodoDepId+cont.pageCount+cont.treatCount+cont.figCount+cont.tabCount&groupingFields=doc.articleUuid+doc.name+doc.doi+doc.zenodoDepId+cont.pageCount+cont.treatCount+cont.figCount+cont.tabCount&FP-doc.articleUuid=3625FFFADF0709707D7BFFF347473E47&format=HTML
