### ISSUE TITLE
font issues in metadata: 

### ISSUE THREAD

**Issue by myrmoteras** [plazi/community#102]
Please look at
https://tb.plazi.org/GgServer/summary/FFF0FFD4FF877767FFA9FF93FFE3FFE0

The paper in Acta Entomologica is by Tomáš Lackner & Gerardo Arriagada. How do you account for the additional "AƶUR, RıAǤAĐA, RıAǤAĐA & AƶUR", which has been reproduced in GBIF:

https://www.gbif.org/species/10704872

What other citations in Plazi have been corrupted by the same processing error?

Best wishes,
Bob
-- 
Dr Robert Mesibov
West Ulverstone, Tasmania, Australia 7315

![image](https://user-images.githubusercontent.com/4609956/145784608-35002740-acb8-4bc6-a2bc-fa01460c71d7.png)

this seems to be an issue with Metatdata

![image](https://user-images.githubusercontent.com/4609956/145784409-bf416d90-23dc-4bb9-9a62-fd9d13d0e254.png)

**Comment by flsimoes** [comment]
This was processed under a old template back in June 2020. With the current template this error cannot be reproduced.
But even looking at the article I can't figure out where the "Azur, Riagada" came from.

Anyway, you can tell Dr. Mesibov that I just fixed the document in our side (also QCd it).
