### ISSUE TITLE
Scope of this projects

### ISSUE THREAD

**Issue by retog** [plazi/community#103]
I was looking at this repo, evaluating where to direct users that want to report an issue with Plazi data. Now I see that the README says this repo is for GGI users. My guess is that very few of the Plazi users even know what GGI is, so I perceive a mismatch between the repo name and its declared scope, which could be fixed either way. In any case, it would be good to have the acronym expanded and linked.

**Comment by mguidoti** [comment]
Gosh, I agree @retog. Thanks for catching this.

This repo has an Integromat recipe listening to it, and it auto-posts all new issues into our Slack group. I could tailor it to something more specific (e.g., only issues with specific keywords or labels), and we could make this repo as a more generalist community hub for every Plazi product, like Synospecies included. 

What do you think? And @myrmoteras ?

**Comment by myrmoteras** [comment]
The directory to send issues about data is https://github.com/plazi/community. May be we should make this more known. even to our own members.

The community github is our oldest our of which many other have developed. It is also not a public repository.

@retog thanks for pointing this out.

GGI repo is for the public https://github.com/gsautter/goldengate-imagine/issues

https://github.com/plazi/ggi/issues GGI is for internal use

**Comment by myrmoteras** [comment]
For specific projects, we have individual repositories, Reto can point out where the synospecies repo is.
