### ISSUE TITLE
materialCitation in table, processing Arthropleura

### ISSUE THREAD

**Issue by myrmoteras** [plazi/community#104]
This article includes in a table the entire list of specimens. 

This might be an example to keep to see, how we could make all this data accessible to GBIF

https://jgs.lyellcollection.org/content/jgs/early/2021/11/19/jgs2021-115.full.pdf

![image](https://user-images.githubusercontent.com/4609956/147190181-e7c60c84-7de1-4770-a967-d163a63ccfcd.png)

**Comment by flsimoes** [comment]
Tables have since been sorted. Need to check whether we've processed this yet.

**Comment by flsimoes** [comment]
TB: https://tb.plazi.org/GgServer/summary/FFC92774FFBBFFE85606FFF6712EFFCD
Zenodo: https://zenodo.org/records/5801508
GBIF: https://www.gbif.org/dataset/ae6d3266-5931-47bf-8faa-87f527891cf2
