### ISSUE TITLE
processing of Flora Iberica vol 9

### ISSUE THREAD

**Issue by myrmoteras** [plazi/community#105]
@flsimoes do you think we can process this? would it make sense to create a template for it? https://bibdigital.rjb.csic.es/viewer/16359/?offset=#page=1&viewer=picture&o=bookmark&n=0&q= I think there would be more volumes to process

**Comment by flsimoes** [comment]
We could try.
I can foresee some challenges with the nomenclature, vernacular name and reference_group sections.

Whether or not a template would apply to other volumes will depend entirely on them using the same layout.

**Comment by flsimoes** [comment]
Were you able to open it on GGI? I couldn't

**Comment by myrmoteras** [comment]
@flsimoes yes, the document has been processed https://tb.plazi.org/GgServer/summary/FFD13E3C0951FF8B9D2D4A2DFFBCFFDD

It took something like 3 h. Guido and I then processed the Oxalis part, which is now on TB https://tb.plazi.org/GgServer/summary/FFD13E3C0951FF8B9D2D4A2DFFBCFFDD

The rest we need to discuss, but it gives an idea of what could be done. Also whether a template could be made - we would need to look into other volumes, but also funding.

**Comment by myrmoteras** [comment]
@flsimoes can you please organize that somebody goes through the flora and makes sure that all the figures and plates and captions are properly annotated.  FFD13E3C0951FF8B9D2D4A2DFFBCFFDD so that we have them all in this BLR deposit listed ? https://zenodo.org/record/5820085#.YdVrxWjML8A

tx

**Comment by flsimoes** [comment]
> @flsimoes can you please organize that somebody goes through the flora and makes sure that all the figures and plates and captions are properly annotated. FFD13E3C0951FF8B9D2D4A2DFFBCFFDD so that we have them all in this BLR deposit listed ? https://zenodo.org/record/5820085#.YdVrxWjML8A
> 
> tx

Hi @myrmoteras 

Yes, I'll pass that on to the team
