### ISSUE TITLE
GBIF Feedback - treatment issues - https://www.gbif.org/dataset/92d80046-8608-4b9f-b36a-8a86b319e232

### ISSUE THREAD

**Issue by ManonGros** [plazi/community#106]
Hi PLAZI,

One of the authors for this publication: https://doi.org/10.11646/zootaxa.5082.3.4 gave us some feedback concerning [its treatment in GBIF](https://www.gbif.org/dataset/92d80046-8608-4b9f-b36a-8a86b319e232) available: https://github.com/gbif/portal-feedback/issues/3830
Not everything is PLAZI related, here is what I think could be solved on PLAZI side:

- There should be only one Allotype but right now 37 out of the 39 occurrence records are Allotypes: https://www.gbif.org/occurrence/search?taxon_key=1649464&type_status=ALLOTYPE. Could you take a look?
- I think the taxon records generated are not all correct. Someone should double check what I am writing here but if I understand correctly, the name for "Sabethes shannoni (Lane & Cerqueira, 1942) Nascimento-Pereira, Neves, Guimarães, Motta & De-Oliveira, 2021" (https://www.gbif.org/species/191654844) should be "Sabethes (Peytonulus) shannoni (Lane & Cerqueira, 1942)"

**Comment by diegojalvares** [comment]
Hi Marie
Thanks for your feedback
First point: materialCitations from treatments were reviewed and typeStatus is fixed
Second point: taxonomicNames authorities ia fixed too

Best
Diego

**Comment by ManonGros** [comment]
Great, thank you Diego! (we interpret the name incorrectly but this is an issue to be handled on GBIF's side)
