### ISSUE TITLE
treatment spilit not ok, taxoxonomic names not all correct, male symbol. Revue Suisse de Zoologie

### ISSUE THREAD

**Issue by myrmoteras** [plazi/community#108]
this article https://tb.plazi.org/GgServer/summary/1C36FF8CFFD7297B725DE7783833FF9F has some errors

https://tb.plazi.org/GgServer/html/E00F87F4FFD6297972CAE13B3A50F9B4

![image](https://user-images.githubusercontent.com/4609956/148342524-d4bb42ca-16c9-475b-8905-c79096f624a4.png)

**Comment by diegojalvares** [comment]
Done
