### ISSUE TITLE
treatment boundaries wrong 

### ISSUE THREAD

**Issue by myrmoteras** [plazi/community#109]
in this case https://tb.plazi.org/GgServer/html/8F4E9617414ADF0CDEE94EEDFD9942E9, the treatment  boundaries are wrong https://tb.plazi.org/GgServer/summary/7377EE6F4149DF0FDE614C54FF82416E

![image](https://user-images.githubusercontent.com/4609956/148343252-b6eba8b0-59df-47b3-b2d7-c3fc8c47afac.png)

**Comment by diegojalvares** [comment]
Done
