### ISSUE TITLE
Coded Materials Citation (Insecta Mundi 0611)

### ISSUE THREAD

**Issue by flsimoes** [plazi/community#11]
@myrmoteras @mguidoti In this publication, [IM 0611](https://drive.google.com/open?id=1mQrUir6RAZ7MipZZZ80uewORwYZOMsnD), the type material is coded under labels such as HTm (for male holotypes) or PTf for female paratypes). In my view this is already a problem in itself, specially for when the publications have closed access (how could a reader recover that coding information which is found outside the treatment proper?).

What makes matters worse is that the authors didn't include the collection codes right after each `materialsCitation`, opting instead to summarise it at the end of the section, thus creating several questions as to the exact whereabouts of each type specimen (to illustrate, they say "HT+AT+24PT at TMSA, 5 PT at BMNH", how would the reader know which paratypes are at TMSA and not at the BMNH?)

![image](https://user-images.githubusercontent.com/3343086/75904458-01c7ed00-5e22-11ea-94bc-386d7e7dc0ad.png)

**Comment by mguidoti** [comment]
Terrible presentation of the information. 

I think in these cases we do our best focusing on liberating the treatment text, and that would be it. If we have the time or the reason why (e.g. contract) we can attempt to fix this by manually entry attributes in the materials citations that would translate all this mess into meaningful data. But that's not the case for this journal, so, I would just mark the treatments... and expose the authors, in a way.

Sorry for my late reply.

**Comment by myrmoteras** [comment]
I would, if at all, just code the first materialsCitation because it has a type, The rest I would skip and let it open, if somebody wants to do it later, whichi is easily possible.

But to get the type is helpful

**Comment by flsimoes** [comment]
Thanks both!
