### ISSUE TITLE
missing description or diagnosis   FFE6FFC7FFEA754FFC7EF853FFC2FFF8

### ISSUE THREAD

**Issue by myrmoteras** [plazi/community#110]
![image](https://user-images.githubusercontent.com/4609956/148352953-cc16ba4a-cb31-4a3e-8909-6aaeb235af1c.png)

in this treatment, there is no description or diagnosis subSubSection included
https://tb.plazi.org/GgServer/html/03DF87BFFFEB754EFCE9FD99FD50F960

**Comment by diegojalvares** [comment]
Done Donat
now it's ok
https://treatment.plazi.org/GgServer/html/03DF87BFFFEB7546FCE9FD99FB8FFDC5
