### ISSUE TITLE
please process http://www.bjc.sggw.pl/arts/2021v21n1/07

### ISSUE THREAD

**Issue by myrmoteras** [plazi/community#111]
This is a new species in a [scitech](https://scitechdaily.com/new-species-discoveries-grow-earths-tree-of-life-from-the-lowland-forests-of-madagascar-to-easter-islands-coral-reefs/) and CAS press release. 

http://www.bjc.sggw.pl/arts/2021v21n1/07.pdf

**Comment by flsimoes** [comment]
TB
https://tb.plazi.org/GgServer/summary/FF842236FFDA5747FFF4A375E50A8C13

Zenodo
https://zenodo.org/record/5825174#.YdbwA2iZMuV

GBIF (waiting...)
