### ISSUE TITLE
journal to be added to the list of journals to be templated and processed

### ISSUE THREAD

**Issue by myrmoteras** [plazi/community#112]
http://www.bjc.sggw.pl/ this is another journal to be considered to template and add to our list of continually processed journals. 

Could also be added to the Polish processing project

**Comment by flsimoes** [comment]
> http://www.bjc.sggw.pl/ this is another journal to be considered to template and add to our list of continually processed journals.

Ok

> 
> Could also be added to the Polish processing project

I'll add that to the email next I message them

**Comment by flsimoes** [comment]
Added
