### ISSUE TITLE
to be processed: https://link.springer.com/content/pdf/10.1007/s12225-021-09988-7.pdf

### ISSUE THREAD

**Issue by myrmoteras** [plazi/community#117]
this is one more from the CAS new species press release

https://link.springer.com/content/pdf/10.1007/s12225-021-09988-7.pdf

thanks for processing

holotype, gbif

**Comment by JonasBlanco** [comment]
The file was processed. The links are the following:

https://tb.plazi.org/GgServer/summary/7071FFD18C3234009620B5167C18FF96

https://zenodo.org/record/5825372#.Ydb_EGjMKUl

https://www.gbif.org/dataset/ead24401-b440-433c-9123-bc9bca82e0b1

Kind regards.
