### ISSUE TITLE
to be processed: 10.1080/00305316.2021.2023056

### ISSUE THREAD

**Issue by myrmoteras** [plazi/community#119]
* please process, including holotype and GBIF

First record of the ant genus Agraulomyrmex Prins, 1983 (Formicidae: Formicinae) from India, with description of a new species
[oritentalInsects.56.2021.2023056.pdf](https://github.com/plazi/community/files/7835576/oritentalInsects.56.2021.2023056.pdf)

**Comment by flsimoes** [comment]
TB
https://tb.plazi.org/GgServer/summary/FFD5FE12FFAC54602101FFDDFF95FFFD

BLR
https://zenodo.org/record/5832018#.YduOBWiZMuU

GBIF
https://www.gbif.org/dataset/d85c2d68-ac95-4c54-a452-e260e6d3886d
