### ISSUE TITLE
Can this paper be extracted?

### ISSUE THREAD

**Issue by truschel** [plazi/community#12]
This looks like a book chapter and we don't know if it has DOI. Can this paper be extracted?

https://drive.google.com/file/d/1UInNhV_JMym5kjkhUvUO8yFyyCmUy1jM/view?usp=sharing

**Comment by flsimoes** [comment]
If I remember correctly this is a Book Chapter in fact.

**Comment by mguidoti** [comment]
@truschel you can select a different Grazia paper to work on.

@myrmoteras should we proceed and extract chapters or only the entire book?

**Comment by mguidoti** [comment]
@truschel I think this is already done, right? If so, could you please close this issue?

Thanks!

**Comment by truschel** [comment]
Yes, this is already done.
