### ISSUE TITLE
A GENERIC CLASSIFICATION OF THE THELYPTERIDACEAE by Fawcett to be finished

### ISSUE THREAD

**Issue by myrmoteras** [plazi/community#121]
This  is the file name for the fern book 2021_ThelypteridaceaeFerns_OACopy3.pdf 

FF8EFF8EFFE99B4B602B7D49FFA7FFBB

thanks for looking into this - quiet a bit has already been done

tx donat

**Comment by flsimoes** [comment]
Do you remember which steps have already been done?

It seems like you did `Detect Document Structure`, the `bibRef` parsing and citation marking, and `Mark Taxon Names`
Is that correct?

**Comment by flsimoes** [comment]
@myrmoteras 

I'm closing this one as we already had one issue for it where I mention the problems with the key
https://github.com/plazi/community/issues/107
