### ISSUE TITLE
Zootaxa with treatments not split

### ISSUE THREAD

**Issue by myrmoteras** [plazi/community#122]
here is a today's Zootaxa with many treatments in one

https://tb.plazi.org/GgServer/summary/2F10FFEC5345FFD0FFC5177C83113D1A

https://tb.plazi.org/GgServer/html/D32987945346FFD3FF52168280F038FC

![image](https://user-images.githubusercontent.com/4609956/148766698-8baf1100-eddc-485b-bf53-de505ab861bb.png)

**Comment by flsimoes** [comment]
Fixed by @truschel
