### ISSUE TITLE
to be processed for new species 2021 news item

### ISSUE THREAD

**Issue by myrmoteras** [plazi/community#123]
@flsimoes here is the copy of the Ankylosaurus pape
[Maidment et al. 2021 - Spicomellus.pdf](https://github.com/plazi/community/files/7839219/Maidment.et.al.2021.-.Spicomellus.pdf)
r

**Comment by flsimoes** [comment]
Got it, thanks

**Comment by flsimoes** [comment]
TB: [FFD978351F78FFEBD61FFFA4FFBAFFD4](https://tb.plazi.org/GgServer/summary/FFD978351F78FFEBD61FFFA4FFBAFFD4)
BLR: [5842122](http://zenodo.org/record/5842122)
GBIF: [4971b307-67fe-49a2-8401-a744db5f4c58](http://www.gbif.org/dataset/4971b307-67fe-49a2-8401-a744db5f4c58)
