### ISSUE TITLE
to be processed: science 371.941

### ISSUE THREAD

**Issue by myrmoteras** [plazi/community#124]
I would appreciate if this article could be processed. It has not treatments, but figures etc. 
Please let @millerjeremya have the UUID
t
[science.371.941-944.pdf](https://github.com/plazi/community/files/7846427/science.371.941-944.pdf)
x

**Comment by flsimoes** [comment]
Will do it

**Comment by flsimoes** [comment]
@myrmoteras @millerjeremya
4923A566B615E903FFFBFFA8FFF2FF84
https://tb.plazi.org/GgServer/summary/4923A566B615E903FFFBFFA8FFF2FF84

**Comment by flsimoes** [comment]
Should be on BLR shortly

**Comment by flsimoes** [comment]
https://zenodo.org/record/5838282#.Yd20jWiZMuU
