### ISSUE TITLE
Zenascus roberti Grzymala & Leschen, 2020

### ISSUE THREAD

**Issue by SiobhanLeachman** [plazi/community#127]
I was attributing specimens in BionomiaTracker and I believe this species was collected in New Zealand given it is endemic to New Zealand rather than in the Congo. Thanks for your help.

**Context**
[GBIF occurrence](https://www.gbif.org/occurrence/2988225363)
[Plazi reference](http://treatment.plazi.org/id/03A48794FFF0FFD16F854D5473A1F847)

**Comment by flsimoes** [comment]
I've fixed these at our end, let's hope the changes take effect on GBIF soon

**Comment by flsimoes** [comment]
All of them have been updated:
https://www.gbif.org/occurrence/search?offset=0&dataset_key=11a122a9-8f3e-4a1c-a8d3-5ef3bea09b59
