### ISSUE TITLE
to be discussed and figure to be added FF96FFCDFFB5BD7DFFECD36C6639A326

### ISSUE THREAD

**Issue by myrmoteras** [plazi/community#129]
https://tb.plazi.org/GgServer/summary/FF96FFCDFFB5BD7DFFECD36C6639A326

this article is complicated. the article has part of a publication, that is each treatment is its own Fungal Planet article, however they are all part of a publication Persoonia 47 https://doi.org/10.3767/persoonia.2021.47.06

* how to process them?
* each Fungal Planet has a cover page with all the figures, followed by one page of text, i.e. the treatment.

**Comment by flsimoes** [comment]
it looked to me as though they are treated as 1 big paper, it is just that they identify who worked on what parts at the end of the descriptions

**Comment by myrmoteras** [comment]
they treat it as one paper, yes But each two pages has its own numeration etc.

**Comment by flsimoes** [comment]
I'm closing this issue.

I've taken a new look at it and it seems straightforward. We should basically treat it as we would book chapters.
