### ISSUE TITLE
Country is MX & needs repair

### ISSUE THREAD

**Issue by dshorthouse** [plazi/community#130]
Change country to México and countryCode to MX.

**Context**
[GBIF occurrence](https://www.gbif.org/occurrence/1671744800)
[Plazi reference](http://treatment.plazi.org/id/06475241FFCFFFF8FF440004FD1FF8C0)

**Comment by flsimoes** [comment]
Should be fixed now.

**Comment by dshorthouse** [comment]
Thanks @flsimoes. What's the refresh schedule for the record @ GBIF's end?

**Comment by flsimoes** [comment]
> Thanks @flsimoes. What's the refresh schedule for the record @ GBIF's end?

Not sure, but it seems that in the paper's materials list, that particular record has already been updated
![image](https://user-images.githubusercontent.com/3343086/149832862-46fc4e48-6073-4be3-a356-031fe9cdf178.png)

Just noticed these 4 which are probably wrong as well, will fix them right away

**Comment by flsimoes** [comment]
Fixed these as well

**Comment by myrmoteras** [comment]
@dshorthouse  The DwC-A proper used for the transfer to GBIF is re-packed 5 minutes after the treatment changes are done translating to the flat HTML included in the DwC-A, and notification to GBIF goes out immediately after the archive is done (re-)packing.

How long GBIF take to come harvest the new or updates DwC-A is outside our domain of control, but usually it's less than 30 minutes.

**Comment by dshorthouse** [comment]
Thanks all for this. FWIW for your records, the "big" download off GBIF takes 2-3 days to mirror what's on smaller, one-off downloads. Pleased to hear the re-harvesting is fairly quick.
