### ISSUE TITLE
Lestid BiCIKL project

### ISSUE THREAD

**Issue by myrmoteras** [plazi/community#131]
@flsimoes 

can you look into these treatmentCitation in Lestids

* markup of all the treatmentCitation
* get a list of all the bibRefs cited in treatment Citation
* check whether we have all the publications cited in the TC processed

Do you have access to the list of existing, processed articles?

**Comment by flsimoes** [comment]
> Do you have access to the list of existing, processed articles?

No, I don't

**Comment by flsimoes** [comment]
Should we go through all of the papers or is there a shortlist of the ones we need to check?

**Comment by myrmoteras** [comment]
We will discuss on Sunday afternoon and decide. Do you want to participate in this discussion with Jeremy and Marcus at 4pm.
Donat

**Comment by flsimoes** [comment]
That's your 4pm, right? Guess that's midday here

**Comment by mguidoti** [comment]
Will be any meeting with Jeremy to discuss this? At the end of the day, we
talked about something else on Sunday.

**Comment by myrmoteras** [comment]
https://calendar.google.com/calendar/u/0/r/week/2022/1/26?eid=Y3BobWFkOW02ZGozaWJiNTZvbzM0YjlrNzVnajBiYjI2c3NtOGI5bzc1aGppZHBrNnRqNjhjcGc2YyAwNnN0a2hkc3JnNTNhOWMwMGlxY2k2MmEzZ0Bn&ctz=Europe/Zurich&sf=true

**Comment by mguidoti** [comment]
Hi Donat, the link doesn't work... can you simply re-send the invitation?

![image](https://user-images.githubusercontent.com/44419136/151715118-30e64dbf-09f6-4d25-8c6b-6c3b1463e754.png)

**Comment by myrmoteras** [comment]
the meeting has been last week.
