### ISSUE TITLE
to be processed 10.1016/j.isci.2021.103579 and 10.1126/sciadv.aav3875

### ISSUE THREAD

**Issue by myrmoteras** [plazi/community#132]
MIght it be possible to process this article that has not treatments, but should go to BLR https://www.cell.com/action/showPdf?pii=S2589-0042%2821%2901549-2 (just remove the first page?!), and the original description in https://www.science.org/doi/reader/10.1126/sciadv.aav3875 low level

tx

**Comment by flsimoes** [comment]
BLR
https://zenodo.org/record/5902217#.Ye_zNOqZOUk

TB
https://treatment.plazi.org/GgServer/summary/3F1756536D3BFFF00C09FA2CDE1CFFCE

GBIF
https://www.gbif.org/dataset/6bfef94c-9692-4e1f-8960-f1d23d58895c
