### ISSUE TITLE
to be processed: 10.1111/syen.12521

### ISSUE THREAD

**Issue by myrmoteras** [plazi/community#133]
one more tonight that is in the news... 
[systEnt.47.94-112.pdf](https://github.com/plazi/community/files/7935846/systEnt.47.94-112.pdf)

low level

tx

**Comment by flsimoes** [comment]
By @diegojalvares 

TB: https://tb.plazi.org/GgServer/summary/67713F34E8128E1DFF839C761C2BEA65
Zenodo:https://zenodo.org/record/5903588#.YfBH7uqZOUk
GBIF:https://www.gbif.org/dataset/2b3da782-3b9c-41a8-ae0b-f0cb9e87e3e3
