### ISSUE TITLE
wrong higher categories

### ISSUE THREAD

**Issue by myrmoteras** [plazi/community#136]
can somebody please clean up the wrong higher categories in these publications: 
https://tb.plazi.org/GgServer/srsStats/stats?outputFields=doc.articleUuid+tax.orderEpithet+tax.familyEpithet+tax.genusEpithet&groupingFields=tax.orderEpithet+tax.familyEpithet&FP-tax.familyEpithet=Fabaceae%20Leguminosae&format=HTML

![image](https://user-images.githubusercontent.com/4609956/151503743-a76776d9-1469-4c4a-9518-cfd791ca568e.png)

urgent

**Comment by diegojalvares** [comment]
Hi Donat
I will fix this, but you can share this search with the document title or UUID?

**Comment by diegojalvares** [comment]
Hi Donat
I'am looking this issue, how urgent is it?
I ask because some of the papers are in xml and take a more time

Best
Diego

**Comment by myrmoteras** [comment]
can you list the papers that are in XML (I guess pensoft journals), and we do them later, and also notify Pensoft.  You do not need them now, but the others from our side would be great.
tx

**Comment by diegojalvares** [comment]
![image](https://user-images.githubusercontent.com/65625004/151546956-d84188c4-5c51-402a-9efb-efcf74332daf.png)
Is a total of 8 Pensosft papers. If you want, I can fix them from here
From our side there was only one that I already fixed

**Comment by myrmoteras** [comment]
@diegojalvares please do not post images, but the html output from the Stats so we can copy and past the article uuid. thanks.

As suspected these are malmost all Pensoft articles. I will deal with this https://github.com/plazi/treatmentBank/issues/29

**Comment by diegojalvares** [comment]
Great
I fixed last comment with the tb link attached

**Comment by myrmoteras** [comment]
let's find out what Guido says, and decide. May be we fix them, if these are not many paper, and the fixes do not take a lot time - how much time do you expect to fix one treatment?

**Comment by diegojalvares** [comment]
I dont know how much time in each treatment, it depends a lot
But I believe in an hour or two it should be ready

**Comment by diegojalvares** [comment]
I fixed most of then, just one still remaining
any problem let me know

**Comment by myrmoteras** [comment]
there is on more
https://tb.plazi.org/GgServer/html/3FCC6BC99D285782A53CC33E644C4015

the family here is not Rosaceae....  otherwise as far as I can see in hymenoptera we do pretty well

**Comment by diegojalvares** [comment]
Fixed this one too
