### ISSUE TITLE
Gonatopus nigricans: a wasp species misplaced under plants

### ISSUE THREAD

**Issue by myrmoteras** [plazi/community#137]
Gonatopus nigricans: a wasp species misplaced under plants

The species name appears in GBIF.org under the wrong branch of the backbone (a wasp species linked into a plant family). Together with this, the occurrence record (https://www.gbif.org/occurrence/1653530363: Holotype!) also appears under plants rather than under animals, where it belongs.

Tracing this back: the source dataset (https://www.gbif.org/dataset/5fac9c21-a601-4155-873a-0ddd55f3a0b0) contains six names in the "taxa.txt" file, three of which are classified as Plantae... Araceae. The title of the dataset suggests that these classifications should rather read as Animalia... Hymenoptera.

Homonymous genera:

Gonatopus Engl. (Araceae, Liliopsida)
Gonatopus Ljungh, 1810 (Dryinidae, Hymenoptera)
User: See in registry
System: Firefox 96.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/species/8482880
Window size: width 1571 - height 810
API log
Site log
System health at time of feedback: WARNING

**Comment by diegojalvares** [comment]
Fixed

**Comment by myrmoteras** [comment]
tx
