### ISSUE TITLE
broken figure links, words taken apart

### ISSUE THREAD

**Issue by myrmoteras** [plazi/community#138]
could somebody have a look at this treatment  https://treatment.plazi.org/id/F52B87F6-5E17-6163-FF5E-DE3FFC951F38

it has broken words and the link to the images seem not to be ok - at least there is not link to an image of Formica helvetica

![image](https://user-images.githubusercontent.com/4609956/151591104-b15537a1-81fa-479f-a415-25245b026155.png)

also please check the DOI in the metadata which is broken http://doi.org/ 10.25849/myrmecol.news_031:13328 because there is a space between` / 1`

I would appreciate if we could do this tonight, since this is an example for a lecture tomorrow morning.

tx

**Comment by diegojalvares** [comment]
I fixed most of errors, just the links between figureCitations need a little more time (this treatment in particular is fixed) but will be done soon

**Comment by myrmoteras** [comment]
@diegojalvares thanks for fixing
