### ISSUE TITLE
GBIF: Bird type specimens of Batis minor linked to plant homonym

### ISSUE THREAD

**Issue by ahahn-gbif** [plazi/community#139]
We received user feedback commenting on bird type specimen records of _Batis minor_ from [this dataset](https://www.gbif.org/dataset/f2daf753-e802-4035-9a1f-6878de66e7ca) being linked to a homonymous name under plants: https://www.gbif.org/species/11373026. GBIF seems to get this higher taxonomy placement from the source dataset.

**Context**
[GBIF occurrences (23 records)](https://www.gbif.org/occurrence/search?taxon_key=11373026)
[GBIF sample occurrence](https://www.gbif.org/occurrence/3387263366)
[Plazi reference sample record](http://treatment.plazi.org/id/03EB1A422650FFEFFF1EF8E91F7BFC0D)

_Homonym entries in GBIF:_
[_Batis minor_, Brassicales](https://www.gbif.org/species/11373026)
[_Batis minor_ Erlanger, 1901, Aves](https://www.gbif.org/species/5231180)

It is possible that the "homonym" species is an artifical entry created under plants in GBIF to accomodate these occurrence records, and that it should eventually disappear after the records are re-connected to birds.

**Comment by Carol-Sokolowicz** [comment]
higher taxonomy has been fixed in the file.
should take a while to update in all repositories

**Comment by Carol-Sokolowicz** [comment]
Taxonomy on TB has been updated, but GBIF still has the wrong taxa .

**Comment by ahahn-gbif** [comment]
The archive behind the endpoint of the [dataset registered in GBIF](https://www.gbif.org/dataset/f2daf753-e802-4035-9a1f-6878de66e7ca), http://tb.plazi.org/GgServer/dwca/FFD2623A2658FFE6FF89FFA41D3CFFF7.zip, still contains the taxa.txt table with plant higher taxonomy. The GBIF ingestion logs report "not modified" on an indexing attempt. Are any additional steps needed to regenerate the archive at source?

**Comment by myrmoteras** [comment]
@ahahn-gbif there is a major processing on our side. So it needs a bit patience - but it will come.
Sorry
All the best

**Comment by ahahn-gbif** [comment]
No rush, and thanks for the response and quick fix! I was just commenting on the line above (I thought)
