### ISSUE TITLE
Missing a specific date of publication

### ISSUE THREAD

**Issue by truschel** [plazi/community#14]
This article does not have a specific date of publication. The only information is July/August 2004.
How should I get the information on Document Meta data?

![image](https://user-images.githubusercontent.com/57402704/77560677-8a273400-6e9c-11ea-9186-5bd4cc5cd3cd.png)

**Comment by myrmoteras** [comment]
2004-08-31. This is the latest possible date. Remember, this can be corrected in case somebody has a better date at some poiint. To find publication dates out is beyond our scope

**Comment by flsimoes** [comment]
@truschel for the template you can tell GGI to include the info after the `-`.

**Comment by truschel** [comment]
@flsimoes it is for an individual extraction.

**Comment by truschel** [comment]
Thanks @myrmoteras
