### ISSUE TITLE
African Invertebrates: Jason Londt project

### ISSUE THREAD

**Issue by myrmoteras** [plazi/community#140]
Via Torsten Dikow

I have set-up a Dropbox folder with 28 publications by Jason Londt in African Invertebrates. Two of these are faunistic studies so might be of less taxonomic importance but I thought I include them.

I can provide bibliographic data as well. The earliest of these publications don’t have a DOI (or at least didn’t get one assigned initially) but were incorproared/accessible from the Sabinet African Journal Archive. I can obtain the unique URLs (I think they use the handle system now) for all of these earlier publications if that would help.

The folder can be accessed here: https://www.dropbox.com/sh/xmzrruu00xn5cd8/AACj3w9fSCMD8jSz_4QObeXVa?dl=0 .

How can I help in marking these articles up?

Thanks for all of your help, Torsten

**Comment by mguidoti** [comment]
If there is anything we can automate with crawlers or such, let me know... O3RT could be used to find potential late-assigned DOIs.

**Comment by flsimoes** [comment]
The following papers shared in the dropbox are already on TB:

londt_2014d - https://tb.plazi.org/GgServer/summary/FF8AFFEEE8465848FFC2A86AFF98FFA1
londt_2016 - https://tb.plazi.org/GgServer/summary/2A2BBE684276A033A53B5268FFFF2036
londt_2019 - https://tb.plazi.org/GgServer/summary/FFCFEA24FF9E22460D51327BFF8EFFA2
londt_2019b - https://tb.plazi.org/GgServer/summary/5C2A2092E76958E79C6E93C56A0F66FF
londt_2020 - https://tb.plazi.org/GgServer/summary/1CCA7F4D3CB555A98C0DA976F578DA16
londt_dikow_2016 - https://tb.plazi.org/GgServer/summary/FF876B512F69FFF3FFC9CC2BFFFFAC74
londt_dikow_2018a - https://tb.plazi.org/GgServer/summary/D53AF1570374FFF1AF44FF89DB03864B
                                - https://tb.plazi.org/GgServer/summary/EC52FF92791EEA3DFFF15C6C285E456E (DUPLICATE ENTRY)
londt_dikow_2019 - https://tb.plazi.org/GgServer/summary/FFCFEA24FF9E22460D51327BFF8EFFA2

**Comment by flsimoes** [comment]
So, @myrmoteras, what should we do with it (+ see @mguidoti's comment above)?
