### ISSUE TITLE
figures not linked  FFFF7518FFBD1432FF8A2D7CA4693666

### ISSUE THREAD

**Issue by myrmoteras** [plazi/community#142]
in this new Zootaxa, the figureCitations are not linked to the figures 

https://tb.plazi.org/GgServer/html/03C60D60FFAF1421FF1D2DEBA53D369F

FFFF7518FFBD1432FF8A2D7CA4693666

**Comment by Carol-Sokolowicz** [comment]
This is currently in the QC queue, it will be soon fixed.

**Comment by truschel** [comment]
Guido

There are two figures in this IMF with captions starting by the word `text`.

![image](https://user-images.githubusercontent.com/57402704/152588538-30471460-2860-4dad-a19d-98ac0d0b4a8b.png)
![image](https://user-images.githubusercontent.com/57402704/152588655-54703e1c-ac3b-46a7-baac-398081fd0f88.png)

and the figureCitations

![image](https://user-images.githubusercontent.com/57402704/152589370-ad3f77da-f7b2-4e5e-9b15-415f2a7c1635.png)

![image](https://user-images.githubusercontent.com/57402704/152589276-18ecde83-3d1e-4939-b53d-1232211db87d.png)


I marked the figure citation by `Annotate Figure Citation` and I made sure the image is correctly assigned with its respective caption. However these two images are not in Zenodo.

What could I do to fix it?

**Comment by gsautter** [comment]
@truschel I don't think there is much you or I can do right now ... keep getting HTTP 500 errors from the Zenodo API, I see it in the server console, and rather soon it should also show up in the transit protocols.

**Comment by truschel** [comment]
Thanks Guido!

**Comment by gsautter** [comment]
No worries, you're welcome ... handling Zenodo is a bit of a challenge these days, lots of 500 range HTTP errors ...

**Comment by myrmoteras** [comment]
Did you contact @aslim?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by gsautter** [comment]
@myrmoteras not yet ... kind of came up only this evening, so I'll observe until Monday and raise an alarm then ... slim chance of anything happening over the weekend ...

**Comment by truschel** [comment]
Hello 

We are verifying open issues today and I realize that the figures mentioned here are in Zenodo. So I'm closing this issue.
