### ISSUE TITLE
Taxonomy not correct

### ISSUE THREAD

**Issue by seggenberger** [plazi/community#143]
In this [paper](https://tb.plazi.org/GgServer/summary/78CD0BFB64B65DFB88DA0AE7871A8E5B) the three beetle species (Calotheca spp.) are taxonomicly treated as poaceae (grasses) and not as beetles. This may be because Calotheca used to be a genus in the poaceae family too.

**Comment by Carol-Sokolowicz** [comment]
I fixed the XML. It might take a while to update all repositories.
