### ISSUE TITLE
Sp. nov authority on http://treatment.plazi.org/id/9B48474CE8148E14FCD2999E1905E9CD

### ISSUE THREAD

**Issue by dshorthouse** [plazi/community#144]
On http://treatment.plazi.org/id/9B48474CE8148E14FCD2999E1905E9CD, the name & authority is listed as:

`Neuroterus valhalla, Brandão‐Dias & Zhang & Pirro & Vinson & Weinersmith & Ward & Forbes & Egan, 2022`

..whereas in the paper & treatment, it is expressed as:

`Neuroterus valhalla sp. nov. Brandão-Dias, Zhang, Weinersmith, Forbes & Egan`

The former has also found its way on GBIF, https://www.gbif.org/occurrence/3455130301. Although peculiarly, the name on https://www.gbif.org/species/192604755 is expressed as:

`Neuroterus valhalla Brandão`

In all these instances, I would expect the name & authority to be expressed as:

`Neuroterus valhalla Brandão-Dias, Zhang, Weinersmith, Forbes & Egan, 2022`

**Comment by debpaul** [comment]
Hm regarding "occurrences" (and I'm talking "scientific name" field here in dwc). note that [at GBIF](https://www.gbif.org/data-quality-requirements-checklists#dcSciName), see
for checklists and occurrence records
- `Valid scientific names are Latin names following the syntax rules of the respective taxon group (e.g. botanical nomenclature). **Not permitted** are, i.a., working names ("Mallomonas sp.4"), common names ("fruit fly"), or names containing identification qualifiers ("Anemone cf. nemorosa"). If common names are used, they should be supplied in addition to the scientific names, using the VernacularName set of fields(see below)."`

**Comment by flsimoes** [comment]
Will check it out

**Comment by flsimoes** [comment]
Fixed it on our side, but I have no idea at the moment as to why the GBIF entry only says "Brandão"

**Comment by mguidoti** [comment]
The name is now correct on the first GBIF link provided by @dshorthouse (https://www.gbif.org/occurrence/3455130301) but not in the second (https://www.gbif.org/species/192604755). This, alongside with the fact that in TB is fixed like @flsimoes said, tells me that on Plazi side the data is correct now. Thus... just a wild idea here: could it be possible that GBIF UI doesn't handle well the `-` in author names in that particular type of page (treatment page)?

**Comment by dshorthouse** [comment]
@mguidoti Does indeed look like a UI issue at GBIF's end. There's a noticeable flicker in the page rendering where the full name + authority is presented and then quickly reflows to truncate the authority information.

**Comment by mguidoti** [comment]
@myrmoteras do we have any direct contact to report this type of issue to GBIF?
