### ISSUE TITLE
Catalogue numbers are a list in single occurrence record

### ISSUE THREAD

**Issue by dshorthouse** [plazi/community#145]
Parsing of material examined has resulted in a single occurrence record whose `catalogNumber` is a comma-separated list.

**Context**
[GBIF occurrence](https://www.gbif.org/occurrence/3455130302)
[Plazi reference](http://treatment.plazi.org/id/9B48474CE8148E14FCD2999E1905E9CD)

**Comment by flsimoes** [comment]
Due to time and personnel constraints this one only had its types parsed.
I checked the parsing of the paratypes, so at least they should be showing up soon

**Comment by dshorthouse** [comment]
Super, though unless I've mistaken or misunderstood, all the specimens in this occurrence are in fact paratypes. Do you mean to say that there ought to soon be 6 occurrence records at GBIF's end in place of just this one that has `individualCount` = 3? Of note, three of these paratypes are indicated as female whereas three are asexual.

**Comment by flsimoes** [comment]
> Super, though unless I've mistaken or misunderstood, all the specimens in this occurrence are in fact paratypes. Do you mean to say that there ought to soon be 6 occurrence records at GBIF's end in place of just this one that has `individualCount` = 3? Of note, three of these paratypes are indicated as female whereas three are asexual.

Sorry, I misinterpreted your first sentence regarding the comma-seaparated list.

Yes, all of them will be showing up individually
