### ISSUE TITLE
Coordinates issue - Saussurea talungensis (Asteraceae), a new species from Humla, Nepal Himalayas

### ISSUE THREAD

**Issue by ManonGros** [plazi/community#146]
Hi PLAZI team,

We have received a feedback message concerning the dataset titled [Saussurea talungensis (Asteraceae), a new species from Humla, Nepal Himalayas](https://www.gbif.org/dataset/c31ce8bd-b442-4668-956b-a6696feae657 - http://treatment.plazi.org/id/CF67BDBBBB555226A6245BB6CF415A49): https://github.com/gbif/portal-feedback/issues/3937

The problem seems to be the geolocation for an occurrence of Saussurea talungensis S.K.Ghimire & H.K.Rana: https://www.gbif.org/occurrence/3079224311
According to the article (http://dx.doi.org/10.3897/phytokeys.176.61996), this species only occurs in Nepal. It looks like there was a mix up in the coordinates used. The article does contain coordinates outside of Nepal but they are associated with a different species, Saussurea lanata:
> **Additional herbarium specimens examined**

> Saussurea lanata. Nepal. Jumla: 3050 m a.s.l., 1952, O. Polunin et al. 3101 (BM, E); Mustang: Tukucha, 3050 m a.s.l., 1954, J.D.A. Stainton et al. 7846 (BM). China. Xizang: Lhozhag, 4450 m a.s.l., 2013, FLPH Tibet Exped. 13-1617 (PE); Gyaca, 4800 m a.s.l., 1972, Tibet Chinese Herbal Medicine Census Team 4538 (PE); Gongbo’gyamda, Bahe, 98°59'41.15"N, 93°41'38.35"E, 3350 m a.s.l., 2012, FLPH Tibet Exped. 12-2144 (PE); Lhunze, Sanga Choling, 28°35'22.92"N, 92°55'12.54"E, 3960 m a.s.l., 2013, FLPH Tibet Exped. 13-0860 (PE).

Perhaps this is where the issue comes from? Would it be possible to check? Thanks!

**Comment by JonasBlanco** [comment]
We identified the problem. The additional examined materials (in the figure below) were linked to the treatment of the species Saussurea talungensis. We have already separated them, so the information must be soon updated in the links.

![image](https://user-images.githubusercontent.com/92064978/154689300-d282b8e4-cd9c-43db-a3c8-d14286a5fe4a.png)

Please, let us know if the problem was solved and if there is any other issue regarding these treatments and materials citations.

**Comment by ManonGros** [comment]
Thanks @JonasBlanco I can see that the dataset doesn't contains occurrences any more. Was it intentional?
The problematic occurrence isn't available any more so I will close the related issue.

**Comment by JonasBlanco** [comment]
Hi, @ManonGros!

Yes, we removed occurrences related to other species, which did not belong to the treatment species but were marked together, so we only kept materials citations related to the type-locality.
