### ISSUE TITLE
process world’s tiniest land snails

### ISSUE THREAD

**Issue by seggenberger** [plazi/community#147]
_Angustopila coprologos_ Páll-Gergely, Jochum & Hunyadi n. sp. and A_ngustopila psammion_ Páll-Gergely, Vermeulen & Anker n. sp. in [10.1163/18759866-bja10025](10.1163/18759866-bja10025)

Would be great, if these two could be integrated into TreatmentBank! Possible?

**Comment by JonasBlanco** [comment]
Hi!

I will process the paper and share the links as soon as I finish.

**Comment by seggenberger** [comment]
Thanks a lot!
