### ISSUE TITLE
missing metadata in TB for articles

### ISSUE THREAD

**Issue by myrmoteras** [plazi/community#148]
in this article, large parts of the metadata is missing. 

https://tb.plazi.org/GgServer/summary/FF86FFB6A336FFE4FFC9FFA0FFE8FFBA

![image](https://user-images.githubusercontent.com/4609956/155485982-102ed692-5d91-4b5e-81cc-2cab76a377dc.png)

![image](https://user-images.githubusercontent.com/4609956/155486061-384b9c18-5b77-41e5-8690-5ed626e9d07e.png)

in comparison

https://tb.plazi.org/GgServer/summary/6A26421EFF8FFF8C3866FFC64618C671

![image](https://user-images.githubusercontent.com/4609956/155486209-724ad351-551a-4181-be57-2284b8c0dc51.png)
![image](https://user-images.githubusercontent.com/4609956/155486251-5110e898-6698-44b2-a4c3-d0b34a595efa.png)

**Comment by flsimoes** [comment]
Quickly fixed

The issue number was mistakenly added as the document's title, hence why everything else got fuzzy:

![image](https://user-images.githubusercontent.com/3343086/155516583-0ee98691-f160-43b5-aa7d-c6a4c9b1a43f.png)
