### ISSUE TITLE
GBIF: Syrphid species A. bombiformis placed under plant genus Arctophila Rupr. ex Andersson

### ISSUE THREAD

**Issue by CecSve** [plazi/community#149]
A GBIF user has notified us of an issue where a syrphid species (_Arctophila bombiformis_) is wrongly placed in the higher taxonomy of plants (although Kingdom Animalia is correct): https://github.com/gbif/portal-feedback/issues/4033. The dataset where the issue appears is hosted by Plazi: https://www.gbif.org/dataset/02db0742-97fe-4ff8-8917-c8d2591d12a1. Could you please help us correct the taxonomy? The correct taxonomy should be Kingdom Animalia - Phylum Arthropoda - Class Insecta - Order Diptera - Family Syrphidae - Genus _Arctophila_

**Comment by diegojalvares** [comment]
Fixed
thanks for your contribution
