### ISSUE TITLE
GBIF: author team separators cause truncation at name parsing

### ISSUE THREAD

**Issue by ahahn-gbif** [plazi/community#150]
#https://github.com/gbif/portal-feedback/issues/3916

We received feedback that a name in GBIF that should read "Neuroterus valhalla Brandão-Dias, Zhang, Weinersmith, Forbes & Egan" is truncated to "[Neuroterus valhalla Brandão](https://www.gbif.org/species/192604755/verbatim)". The source of the record is this treatment: https://treatment.plazi.org/id/9B48474CE8148E14FCD2999E1905E9CD

The reason appears to be that the author team, consisting of 5 parties, is using the character '&' throughout, rather than the more standard notation of using commata in all but the last position. The [GBIF name parser](https://www.gbif.org/tools/name-parser) is not expecting this notation. Is this intentional / expected, so that we would need to handle this notation, or could it be in error?

**Comment by flsimoes** [comment]
Hi @ahahn-gbif 
Thanks for reporting this! We will discuss this with our software developer and will get back to you soon.

**Comment by flsimoes** [comment]
@ahahn-gbif 
Sorry for the late reply, but could it be there's something to be done on GBIF's side?

We did notice the other author names are missing from our side, however, for us it shows "Brandão-Dias", but on GBIF it shows only "Brandão", so there seems to be a problem with the dash on GBIF.

**Comment by ahahn-gbif** [comment]
Hi @flsimoes, thanks for getting back to this!

I checked into this - you are right that it isn't the ampersands that are causing this, though I am still surprised by this notation. Rather, it is the dash character that sits in the double name at the start. To illustrate, try and copy-paste all four of these lines into our names parser at https://www.gbif.org/tools/name-parser, then click on "parse":

Neuroterus valhalla Brandão‐Dias & Zhang & Pirro & Vinson & Weinersmith & Ward & Forbes & Egan 2022
Neuroterus valhalla Brandão-Dias & Zhang & Pirro & Vinson & Weinersmith & Ward & Forbes & Egan 2022
Neuroterus valhalla Brandão‐Dias, Zhang, Pirro, Vinson, Weinersmith, Ward, Forbes & Egan 2022
Neuroterus valhalla Brandão-Dias, Zhang, Pirro, Vinson, Weinersmith, Ward, Forbes & Egan 2022

Each of these pairs has two identical lines, except that I replaced the dash in Brandão-Dias in the second one both tims. In each pair, the second one parses correctly, while the original one fails (check to the right of the result to see the difference).

I have not checked any further than this, but my guess is that the original version, while looking like a dash, is some control character or other. I thought that in occurrence data, we have a pretty good grip by now on stripping these out, but we obviously do not catch this one in a names resource. While we probably will want to handle this as well: should that character be in the text at the source?

**Comment by flsimoes** [comment]
> Hi @flsimoes, thanks for getting back to this!
> 
> I checked into this - you are right that it isn't the ampersands that are causing this, though I am still surprised by this notation. Rather, it is the dash character that sits in the double name at the start. To illustrate, try and copy-paste all four of these lines into our names parser at https://www.gbif.org/tools/name-parser, then click on "parse":
> 
> Neuroterus valhalla Brandão‐Dias & Zhang & Pirro & Vinson & Weinersmith & Ward & Forbes & Egan 2022 Neuroterus valhalla Brandão-Dias & Zhang & Pirro & Vinson & Weinersmith & Ward & Forbes & Egan 2022 Neuroterus valhalla Brandão‐Dias, Zhang, Pirro, Vinson, Weinersmith, Ward, Forbes & Egan 2022 Neuroterus valhalla Brandão-Dias, Zhang, Pirro, Vinson, Weinersmith, Ward, Forbes & Egan 2022
> 
> Each of these pairs has two identical lines, except that I replaced the dash in Brandão-Dias in the second one both times. In each pair, the second one parses correctly, while the original one fails (check to the right of the result to see the difference).
> 
> I have not checked any further than this, but my guess is that the original version, while looking like a dash, is some control character or other. I thought that in occurrence data, we have a pretty good grip by now on stripping these out, but we obviously do not catch this one in a names resource. While we probably will want to handle this as well: should that character be in the text at the source?

Indeed you can even see the difference here:
<img width="80" alt="image" src="https://user-images.githubusercontent.com/3343086/167156570-180ed30a-ce21-4257-a5ad-27c878785f24.png">

It is not an en-dash nor an em-dash, just tested it, so I'm curious myself as to which character it is and why we are getting this character instead of an hyphen. I'll get back to you soon...

**Comment by gsautter** [comment]
For what it looks like, the problematic character seems to be a Unicode hyphen (0x2010) ... replaced it with an ASCII minus (0x002D) now, so this should be fine.

**Comment by ahahn-gbif** [comment]
Thank you, looks good now! Closing.
