### ISSUE TITLE
incorrect kingdom - Ascra Say, 1832

### ISSUE THREAD

**Issue by ManonGros** [plazi/community#151]
Hi PLAZI,

Someone recently logged this feedback message on our portal: https://github.com/gbif/portal-feedback/issues/4057
It looks like there is an error for the kingdom of the genus Ascra Say, 1832: https://www.gbif.org/species/119643589 (see dataset here: https://www.gbif.org/dataset/8d4ae7bf-0427-4539-8dfb-6ca52d647b73 and corresponding DOI: https://doi.org/10.11646/zootaxa.4034.3.2).
Ascra seems to be an insect but for some reason the kingdom provided is Plantae. Could you take a look?
Thanks!

**Comment by JonasBlanco** [comment]
I will take a look!

**Comment by JonasBlanco** [comment]
Fixed!
Please, let me know if there is any other issue that needs fixing.

**Comment by ManonGros** [comment]
Thanks Jonas! It looks good now, I will close this issue.
