### ISSUE TITLE
GBIF occurrence - country inferred incorrect

### ISSUE THREAD

**Issue by ManonGros** [plazi/community#152]
Hi PLAZI,

We recently received a feedback message concerning some occurrences in the dataset: [Anarsioses, a new generic name for Phyllonorycter aberrans (Braun) (Lepidoptera Gracillariidae)](https://www.gbif.org/dataset/0a904757-e79b-4065-981f-5dcf10ae7d07) (https://doi.org/10.11646/zootaxa.4701.6.6).

The country provided for the species Anarsioses aberrans is Colombia but the country should be the US. See the full message here: https://github.com/gbif/portal-feedback/issues/4084

Could you take a look? Thanks!

**Comment by diegojalvares** [comment]
Hi
I will take a look

thanks

**Comment by diegojalvares** [comment]
Hi Marie
Fixed
https://www.gbif.org/occurrence/search?dataset_key=0a904757-e79b-4065-981f-5dcf10ae7d07

best
Diego
