### ISSUE TITLE
taxonomic names are mingled up

### ISSUE THREAD

**Issue by myrmoteras** [plazi/community#153]
in this article http://treatment.plazi.org/GgServer/summary/FF8CF90FFFB66C66FFE64527A673FFDB taxonomic names are mingled up: 
![image](https://user-images.githubusercontent.com/4609956/169457792-90b3197c-5e72-41c6-9d0f-cedcfa9a7e77.png)

other examples are here 
https://we.tl/t-FjNeYMC8Tr

Christos

**Comment by flsimoes** [comment]
Fixed almost all the errors.
Just this one I haven't managed yet
![image](https://user-images.githubusercontent.com/3343086/169603693-2d8bd05e-51a5-4006-b184-01201d911748.png)

**Comment by myrmoteras** [comment]
@flsimoes thanks. Do you have an understanding why this happened?
cheers
donat

**Comment by flsimoes** [comment]
> @flsimoes thanks. Do you have an understanding why this happened? cheers donat

Fixed it now. Had to change some attributes in the `taxonomicName`.

Before the fix:
`authority` = (Bruguiere, 1792)
`authorityName` = Brugiere
`authorityYear` = 1792

After the fix:
`authority` = (Bruguiere, 1792)
`baseAuthorityName` = Brugiere
`baseAuthorityYear` = 1792
