### ISSUE TITLE
please check taxon name: should not be Peromyscus

### ISSUE THREAD

**Issue by myrmoteras** [plazi/community#155]
https://treatment.plazi.org/id/03B587A75C63E16D120DC6BFD3C9CEF7

![image](https://user-images.githubusercontent.com/4609956/173532294-45bfebe0-0a7d-4d09-b68e-299719247296.png)

**Comment by valdenar** [comment]
Hi Donat,
I'll check.

**Comment by valdenar** [comment]
I made the necessary correction. The taxonName was with the wrong gender.
![image](https://user-images.githubusercontent.com/57402751/173569224-fc969206-c9db-4302-9ca7-f10d739d958a.png)
