### ISSUE TITLE
recordedBy incorrectly parsed in this one

### ISSUE THREAD

**Issue by dshorthouse** [plazi/community#158]
recordedBy is incorrectly parsed in this treatment

**Context**
[GBIF occurrence](https://www.gbif.org/occurrence/3758305316)
[Plazi reference](http://treatment.plazi.org/id/B23987DCFFAEFFEA5E83D0BAFECFFC82)

**Comment by flsimoes** [comment]
Fixed
![image](https://user-images.githubusercontent.com/3343086/183550148-412e0948-3577-4e86-81eb-c6afe9a11c51.png)

Thanks for notifying us
