### ISSUE TITLE
Three GBIF datasets are missing endpoints

### ISSUE THREAD

**Issue by ManonGros** [plazi/community#159]
Hi PLAZI,

My colleague noticed that these three datasets were published without any endpoint:

title | URL
-- | --
Phylogeny of Celastraceae subfamily Hippocrateoideae inferred from morphological characters and nuclear and plastid loci | https://www.gbif.org/dataset/15120008-4ae6-4221-91ed-2ea9d7d1f8d6
Goodyera malipoensis (Cranichideae, Orchidaceae), a new species from China: Evidence from morphological and molecular analyses | https://www.gbif.org/dataset/bd7b875f-5b3d-4ab7-aec1-060759727ece
Limonium poimenum (Plumbaginaceae), a new chasmophyte species from Sicily | https://www.gbif.org/dataset/6e7d12f7-3cb0-465a-8d7a-f32f50ee00ae

Would it be possible to check what happened? Thanks!

(related issue: https://github.com/gbif/portal-feedback/issues/4167)

**Comment by flsimoes** [comment]
Hi Manon

There's other GBIF entries for these articles. I'm not sure why the other ones weren't fully deprecated by GBIF.

title | URL | URL 2
-- | -- | --
Phylogeny of Celastraceae subfamily Hippocrateoideae inferred from morphological characters and nuclear and plastid loci | https://www.gbif.org/dataset/15120008-4ae6-4221-91ed-2ea9d7d1f8d6 | https://www.gbif.org/dataset/9f08fae6-4e03-4823-988c-2076eddd45f5
Goodyera malipoensis (Cranichideae, Orchidaceae), a new species from China: Evidence from morphological and molecular analyses | https://www.gbif.org/dataset/bd7b875f-5b3d-4ab7-aec1-060759727ece | https://www.gbif.org/dataset/fcacce7b-005a-4976-9926-825ebce5d8be
Limonium poimenum (Plumbaginaceae), a new chasmophyte species from Sicily | https://www.gbif.org/dataset/6e7d12f7-3cb0-465a-8d7a-f32f50ee00ae | https://www.gbif.org/dataset/540141ce-6044-48c2-86f4-64c41468fc4a

**Comment by flsimoes** [comment]
I'll investigate further on our end.
But it might be simply a failed deprecation on GBIF's side.

**Comment by ManonGros** [comment]
Thanks @flsimoes! I have linked the datasets with their duplicates and deleted the versions without endpoints.
I will close the issue.

**Comment by flsimoes** [comment]
> Thanks @flsimoes! I have linked the datasets with their duplicates and deleted the versions without endpoints. I will close the issue.

You're welcome!
