### ISSUE TITLE
EJT.492.1-135 - Treatments

### ISSUE THREAD

**Issue by flsimoes** [plazi/community#16]
@myrmoteras @mguidoti
This publication has a different way of showing their treatments (assuming I can consider them as such):
- they have "Taxonomic Notes"
![image](https://user-images.githubusercontent.com/3343086/78036653-f1cbfc00-7340-11ea-89d9-066f1d6c8dfa.png)

- then they have these new combinations:
![image](https://user-images.githubusercontent.com/3343086/78036794-1a53f600-7341-11ea-8fba-151ce0e704c8.png)

I know how to deal with most of them, although some will probably require me to manually change the word relation and word flow to get it more accurately. However, as you can see in the very last example, they sometimes have more than one species per treatment. 

My question is: should I consider just the genus as a `Heading` in these cases?

![image](https://user-images.githubusercontent.com/3343086/78037297-bbdb4780-7341-11ea-817b-668f55066471.png)

Also, are these treatments?

![image](https://user-images.githubusercontent.com/3343086/78037538-14aae000-7342-11ea-901b-b81f4f4ee464.png)

**Comment by mguidoti** [comment]
I would get the treatments at the most specific level we can, even if that requires change word relation.

The second question I would say that it's a treatment, a list of specis, of the family Cypridoidea.

I'll ask @truschel  to take care of this.

**Comment by flsimoes** [comment]
I just made the remaining corrections to this issue.
UUID: FFE4FFA0FFF5D207FFE0A659703AFFCC

There are a 2 errors left in the gatekeeper stats, but they should eventually be solved when the automated gizmos run through it.
