### ISSUE TITLE
"Scarabaeoidea" tagged as genus

### ISSUE THREAD

**Issue by larsgw** [plazi/community#160]
In this treatment https://treatment.plazi.org/id/901F8794-FF8D-747A-FEFF-FF3AFBFAFAA0, Scarabaeoidea is stated to be a genus (and assigns an author citations that doesn't seem to appear in the original work). The attached treatment is an identification keys to a subset of species in the Scarabaeoidea superfamily.

**Comment by flsimoes** [comment]
Thank you for noticing this!
I've just fixed it (should read superfamily now).
As far as I'm aware, the author for Scarabaeoidea is indeed Latreille, 1802.

**Comment by larsgw** [comment]
Thank you!

> As far as I'm aware, the author for Scarabaeoidea is indeed Latreille, 1802.

Ah okay, that makes sense. I just was unsure where it came from since I could not find it in the original source.

**Comment by flsimoes** [comment]
> Thank you!
> 
> > As far as I'm aware, the author for Scarabaeoidea is indeed Latreille, 1802.
> 
> Ah okay, that makes sense. I just was unsure where it came from since I could not find it in the original source.

Most of the taxonomic information available in our processed articles come from the GBIF backbone or the Catalogue of Life, but every now and then we add it manually if we happen to know an specific piece of information through our own research.
