### ISSUE TITLE
GBIF Feedback - Pentastira eminei Demirel, 2022

### ISSUE THREAD

**Issue by ManonGros** [plazi/community#161]
Hi PLAZI,

The author of one the of this paper: https://doi.org/10.11646/zootaxa.5190.2.2 (treatment: https://treatment.plazi.org/id/03CD8639-FF85-FFC7-A2F7-1D47FC2D514E) contacted us because he noticed that the scientific name authorship published on GBIF isn't correct: https://www.gbif.org/species/201137874
On GBIF, the species is `Pentastira eminei Demirel & Erbey, 2022` but should be `Pentastira eminei Demirel, 2022`. Would it be possible to update the dataset? Thanks!

Here is the dataset concerned:
https://doi.org/10.15468/85rq37
https://www.gbif.org/dataset/14f25e68-9e16-4e3d-a888-f441bb1384cb

**Comment by diegojalvares** [comment]
Hi Marie
I fixed the taxon name authority attributes and it has already been updated in GBIF
thank you for the feedback
