### ISSUE TITLE
eventDate should be 13.XI.2020

### ISSUE THREAD

**Issue by dshorthouse** [plazi/community#162]
As in the subject. Also unclear if there is in fact a known catalogNumber on this specimen at USNM.

**Context**
[GBIF occurrence](https://www.gbif.org/occurrence/3864793302)
[Plazi reference](http://treatment.plazi.org/id/9642F329FFF1FFF731B3FC39799D178B)

**Comment by diegojalvares** [comment]
Thanks for your feedback
collection date and specimen code were fixed
