### ISSUE TITLE
Specimen parses with correct Lat/Long missplaces locality label as Country label

### ISSUE THREAD

**Issue by mjy** [plazi/community#163]
We found Country records were incorrectly attributed when Lat/Long was correctly detected.  In this case the name of the locality is "Angola", but it's in Steuben County, Indiana.  It's hard to know where the problem originated.  The "origin" in GBIF says "Angola", which doesn't seem to be reflected in the parsing as visualized from Plazi.

This raises the question, as we all collectively infer data from parsing, should we share a unified priority/process/procedure?  We hit similar issue in TaxonWorks when we use a Georeference to infer Country/State/County precisely, but our Gazetteers don't have enough resolution to correctly assign the values that were also provided as strings.  In this case the algorithm has to make a decision as to how to index the record.  In other words, if we can standardize how we make decisions when _both_ geo-spatial and geo-names are provided we might be better able to debug across platforms.

**Context**
[GBIF occurrence](https://www.gbif.org/occurrence/3111547401)
[Plazi reference](http://treatment.plazi.org/id/3D0ED365FF8A5146DA3CFBBD4251FEC5)

**Comment by mjy** [comment]
For reference here is the original string: `From journal: IN, Putnam Co., Tributary Big Walnut Creek, Hall Woods Nature Preserve, 4 km E Bainbridge, 39.7608, -86.7837, 4/20/2008, R.E. DeWalt, S. K. Ferguson,♀️ (INHS); Steuben Co., Tributary Lake Lonidaw, 10 km NNW Angola, Potawatomi State Park, Potawatomi Nature Preserve, 41.7091, -85.0150, 3/10/2006, R.E. DeWalt, 6 ♂️, 4 ♀️ (INHS); same location, 3/9/2008, R.E. DeWalt, D. W. Webb, 5♂️, 2♀️ (INHS)`

**Comment by mjy** [comment]
We were confused as to where the problem originated (GBIF or Plazi), but the API response indicates that the problem are on the Plazi side:

https://tb.plazi.org/GgServer/taxonx/3D0ED365FF8A5146DA3CFBBD4251FEC5

Note: `<dwc:Country>Angola</dwc:Country>`

**Comment by JonasBlanco** [comment]
I fixed all the occurrences in the manuscript.
Please, let us know if there is any other issue that needs to be fixed regarding this paper.
