### ISSUE TITLE
Xiphonectes aculeatus is not in French Polynesia

### ISSUE THREAD

**Issue by gargotato** [plazi/community#165]
Hi,
https://www.gbif.org/occurrence/search?taxon_key=9857279&country=PF
This occurrence is erroneous, French Polynesia is mentionned in Comparative material for Xiphonectes paralatibrachium
Regards,
Olivier

**Comment by diegojalvares** [comment]
Hi Olivier
Thanks for your feedback
As you already diagnosed, comparative material (from  _Xiphonectes paralatibrachium_) was interpreted as belonging to the taxon newly described.
I fixed this one and soon it should be updated in gbif database

Diego
