### ISSUE TITLE
Gonioinfradens giardi 

### ISSUE THREAD

**Issue by gargotato** [plazi/community#166]
Hi,
https://www.gbif.org/occurrence/search?dataset_key=53ad3f05-691d-4b34-8c76-8834d4908989
Occurrences in French Polynesia, Réunion and Mauritius are for Comparative material of Charybdis (Gonioinfradens) paucidentatus
cheers

**Comment by diegojalvares** [comment]
Hi Olivier,
I fixed this one

best
Diego
