### ISSUE TITLE
Xylocopa nautlana Cockerell, 1904 is not in Guadeloupe

### ISSUE THREAD

**Issue by gargotato** [plazi/community#169]
Hi,
https://www.gbif.org/occurrence/search?offset=0&country=GP&dataset_key=2ea92794-0848-464f-b082-5dc820088547
These occurences are not from Guadeloupe, the french antillean island (maybe Guadalupe, I did not checked so far)
Olivier

**Comment by diegojalvares** [comment]
Hi Olivier
This one seens fixed too

best
Diego
