### ISSUE TITLE
Pristimantis aff. pluvialis not Pristimantis pluvialis 

### ISSUE THREAD

**Issue by gargotato** [plazi/community#170]
Hi,
https://www.gbif.org/occurrence/search?taxon_key=8944519&country=GF
in the paper : Pristimantis aff. pluvialis "The population of this species likely
belongs to an undescribed species related to Pristimantis pluvialis."
so IT IS NOT Pristimantis pluvialis 
Regards,
Olivier

**Comment by diegojalvares** [comment]
Hi Olivier
Fixed this one too
best
Diego
