### ISSUE TITLE
Collocalia esculenta lagonoleucos not in New Caledonia

### ISSUE THREAD

**Issue by gargo-mnhn** [plazi/community#177]
Hi,
and thanks for your previous treatments
https://www.gbif.org/occurrence/search?taxon_key=9434981&country=NC
in the paper p427, this subsp in only recorded from NW Solomon Islands
only C. uropygialis albidior from New Caledonia
best,
Olivier

**Comment by valdenar** [comment]
Hi Olivier,
I made the correction of the treatment, soon the information will update.

Best,
Valdenar
