### ISSUE TITLE
Richerius marqueti Isyeb, 2020

### ISSUE THREAD

**Issue by gargo-mnhn** [plazi/community#178]
Hi,
https://www.gbif.org/occurrence/2642716305
this name/taxon does not exist
it is https://www.gbif.org/species/10869692
Isyeb is not author but affliliation of authors
Best,
Olivier

**Comment by flsimoes** [comment]
Hi Olivier

We'll look into fixing this one soon.

While we are at it, we've noticed the different sort of errors you've helped us with for the past few days and so we were wondering whether it is part of some bigger project envolving Pacific Islands or something else. Perhaps we could contribute and make it an easier for all involved. Perhaps we could reach a point were you would be able to fix the errors as well.

Thank you for your help!
Felipe

**Comment by gargotato** [comment]
Hi Felipe,
Thank you for your kind appreciation.
At time being I am very happy with the workflow which works remarquably.
I am responsible for the french national register TAXREF (https://inpn.mnhn.fr/programme/referentiel-taxonomique-taxref and https://taxref.mnhn.fr publically accessible by the end of the year), which explains that all my issues concern french territories.
Thank you for the prompt replies to issues and bravo for the up-to-date datas on gbif - impressively efficient.
Olivier

**Comment by flsimoes** [comment]
Thank you very much for the clarification!

Glad to hear it's working out nicely, so please keep them coming. This is the sort of community help that we want to provide and works both ways.

Also thanks for the links, I'll check it out!

**Comment by valdenar** [comment]
Hi Olivier,
I corrected the authority in the taxon name, soon the information will update.

Best,
Valdenar
