### ISSUE TITLE
Aphanomerus rufescens not in French southern Territories 

### ISSUE THREAD

**Issue by gargo-mnhn** [plazi/community#179]
Hi,
https://www.gbif.org/occurrence/search?taxon_key=1400439&country=TF
This species is not recorded from French southern Territories in the paper. I think the coordinates on gbif are false because they fall into the territory, indeed.
Best,
Olivier

**Comment by valdenar** [comment]
Hi Olivier,
I corrected the examined material, soon the information will update.

Best,
Valdenar
