### ISSUE TITLE
TB: treatment with wrong genus name

### ISSUE THREAD

**Issue by myrmoteras** [plazi/community#18]
see the issues here, wherby Acer is the wrong name, should be Argilus

https://github.com/plazi/ggi/issues/19

**Comment by Carol-Sokolowicz** [comment]
I've fixed the genus names in the attributes of all taxonomic names.
I noticed that several treatments were not marked, if I you want I can fix it.

**Comment by mguidoti** [comment]
@truschel can you please fix the non-marked treatments, pointed out by Carol?

**Comment by truschel** [comment]
@myrmoteras @mguidoti it is done.
