### ISSUE TITLE
Heterotetramelus (Heterotetramelus) novaecaledoniae (Jałoszyński, 2021) Jałoszyński, 2021

### ISSUE THREAD

**Issue by gargo-mnhn** [plazi/community#181]
Hi,
https://www.gbif.org/occurrence/search?taxon_key=11156376&country=NC
https://www.gbif.org/occurrence/3071254304 is an error for Heterotetramelus novaecaledoniae (Franz, 1971)
gbif trust more on plazi than on taxref, too bad ;)
do you link with then ?
Best
Olivier

**Comment by valdenar** [comment]
Hi Olivier,
I corrected the examined material, soon the information will update.

Best
Valdenar
