### ISSUE TITLE
Homo sapiens ferus unexpectedly changed to Homo Sapiens ferus in 0B6AC9BA1E03488CE06DCAA62DC4AA02

### ISSUE THREAD

**Issue by jhpoelen** [plazi/community#182]
Previously, 0B6AC9BA1E03488CE06DCAA62DC4AA02 reported name:

Homo sapiens ferus

but currently, 0B6AC9BA1E03488CE06DCAA62DC4AA02 reports:

Homo Sapiens fetus

Note the unconventional capitalization of "Sapiens"

**Comment by jhpoelen** [comment]
See also https://github.com/plazi/treatments-rdf/main/data/0B/6A/C9/0B6AC9BA1E03488CE06DCAA62DC4AA02.ttl

**Comment by jhpoelen** [comment]
Note that the change appears to have been made 3 months ago on 2022-08-29 by a robot called ```action runner``` via commit https://github.com/plazi/treatments-rdf/commit/2b5578e213c46d820e4c6120e23137dcc7b646ee (see https://github.com/plazi/treatments-rdf/blame/main/data/0B/6A/C9/0B6AC9BA1E03488CE06DCAA62DC4AA02.ttl and associated screenshot) 

![Screenshot from 2022-11-17 12-54-20](https://user-images.githubusercontent.com/1084872/202533754-bbf884d3-fd97-4a23-b378-40900c6155c7.png)

**Comment by jhpoelen** [comment]
And also note that the associated Plazi concept id and taxon name id changed from:

http://taxon-concept.plazi.org/id/Animalia/Homo_sapiens_ferus_Linnaeus_1758

to

http://taxon-concept.plazi.org/id/Animalia/Homo_Sapiens_ferus_Linnaeus_1758

and 

from 

http://taxon-name.plazi.org/id/Animalia/Homo_sapiens_ferus

to 

http://taxon-name.plazi.org/id/Animalia/Homo_Sapiens_ferus

Seemingly small change for us humans (sapiens -> Sapiens), but a big change for naive computer programs and databases.

**Comment by myrmoteras** [comment]
referred this discussion to https://github.com/plazi/treatments-rdf/issues/7

**Comment by jhpoelen** [comment]
@myrmoteras thanks! Curious to learn more about the mechanisms that caused this change.

**Comment by retog** [comment]
@gsautter, can you explain why the casing of "sapiens" changed here: https://github.com/plazi/treatments-xml/blob/29e8fd74b1f2b24bb590e51992ea54d6b42a3a60/data/0B/6A/C9/0B6AC9BA1E03488CE06DCAA62DC4AA02.xml#L31
?

**Comment by gsautter** [comment]
Well, it has been this way since last January ... digging into what exactly made the change, as I did not ...

**Comment by gsautter** [comment]
It's actually correct in the parent XML document of the overall book, and the capitalization was most likely imported from https://zoobank.org/NomenclaturalActs/ADAA382F-6794-4AB2-B43B-5412B0394005 ... added some more scrutiny there, and it went back to its expected "sapiens" in lower case.

**Comment by retog** [comment]
Thanks @gsautter.  It's fixed in https://github.com/plazi/treatments-xml/blob/a9ac69dddbdf556b61709714851daa98286a2de2/data/0B/6A/C9/0B6AC9BA1E03488CE06DCAA62DC4AA02.xml#L31, so I got picked up the action creating the RDF.

**Comment by jhpoelen** [comment]
I just confirmed that Homo sapiens subsp. ferus now occurs in https://tb.plazi.org/GgServer/html/0B6AC9BA1E03488CE06DCAA62DC4AA02 (also see attached screenshot).

@gsautter @retog @myrmoteras thanks for addressing this issue.

![Screenshot from 2023-01-17 09-38-27](https://user-images.githubusercontent.com/1084872/212942742-30e0af88-7c47-42ee-974a-d20c83b24bda.png)
