### ISSUE TITLE
eventDate is incorrectly parsed here

### ISSUE THREAD

**Issue by dshorthouse** [plazi/community#187]
As in the subject. Collected by T.A. Wheeler who was not alive in the late 19th century.

[GBIF occurrence](https://www.gbif.org/occurrence/2985225873)
[Plazi reference](http://treatment.plazi.org/id/03FB87A9FECCFEBEFE6D6F21FEAAFA37)

**Comment by truschel** [comment]
Hi @dshorthouse 
I fixed the evenDate. See the updated link below.
Thank you for letting us know.
https://www.gbif.org/occurrence/2985225846

**Comment by dshorthouse** [comment]
Thanks, @truschel but that's a different occurrence from the one reported, https://www.gbif.org/occurrence/2985225873. And, unless I'm mistaken, it looks like you've additionally stripped away `recordedBy`.

**Comment by myrmoteras** [comment]
probably: no

**Comment by dshorthouse** [comment]
> probably: no. It is a question, not least of resources and priorities.

In taking a closer look at this particular occurrence, the `eventDate` is incorrect, `recordedBy` is incorrect, `locality` is incorrect, `individualCount` = 665 (what?!) is incorrect, `decimalLatitude` and `decimalLongitude` are incorrect, and if a portion of the locality is correct, then `institutionCode` is is likewise incorrect. So, the result is a material citation-based occurrence for which nearly all metadata about it except `scientificName` is incorrectly lifted from the printed work. Does this record actually serve any purpose when shared with GBIF? Are there particular signals end-users can employ to filter out such records?

**Comment by truschel** [comment]
Hi @dshorthouse 

I fixed all the material citation related to this species, _Anthomyza gilviventris_, Roháćek & Barber, 2016.

Best,
Tatiana

**Comment by dshorthouse** [comment]
Super! Thanks for this @truschel.
