### ISSUE TITLE
Anisus vorticulus  not a coleoptera

### ISSUE THREAD

**Issue by myrmoteras** [plazi/community#188]
Good morning, 
I was looking for information about Anisus vorticulus and I found your web page http://treatment.plazi.org/id/03CDA653FFF4FFFDFF411DF7FDD5DB16.
Opening the taxonomy menu, the species, which is a pulmonate gastropod, appears under Coleoptera Curculionidae:
 
Best wishes
Carla

**Comment by diegojalvares** [comment]
Hi Donat
I fixed information about all Anisus species
https://www.gbif.org/dataset/aceedc3f-3f24-490c-8046-7528c30aac10
https://tb.plazi.org/GgServer/summary/FFF4DE2BFFE9FFE0FFD61C2CFFFDDF22

Best
Diego
