### ISSUE TITLE
wrong species name

### ISSUE THREAD

**Issue by myrmoteras** [plazi/community#19]
this should be infusca not infosca
discovered in:
https://www.gbif.org/species/163435116
Bonaccorso, Frank (2019): Family Emballonuridae (Sheath-tailed Bats). In: Wilson, Don E., Mittermeier, Russel A. (Eds): Handbook of the Mammals of the World. Volume 9. Lyny Edicions: 350-373, ISBN: 978-84-16728-19-0, DOI: http://doi.org/10.5281/zenodo.3740269

**Comment by Carol-Sokolowicz** [comment]
Hi Donat,
I fixed the taxonomic name in the XML...
Up to now, it's still not fixed on GBIF.
Cheers

**Comment by myrmoteras** [comment]
i will check

**Comment by myrmoteras** [comment]
@Carol-Sokolowicz  I fixed this this morning already and should have close the issue. The reason was that the treatment started at genus level, and now it is a genus and a species treatment.

**Comment by Carol-Sokolowicz** [comment]
OK! Is it good now?

**Comment by myrmoteras** [comment]
I check and seems to be ok
tx

**Comment by Carol-Sokolowicz** [comment]
Ok!!Good!
