### ISSUE TITLE
[treatment E11F878EFFCAFFC5FF50F949FDC9DA9C / taxonomicName AEB64D1BFFCAFFC5FE3BF923FBF3DA75] on 2022-12-19 ,  Donat claimed that [ Abrocoma bennetti ] should be replaced with [ Abrocoma bennettii ]

### ISSUE THREAD

**Issue by jhpoelen** [plazi/community#220]
[treatment E11F878EFFCAFFC5FF50F949FDC9DA9C / taxonomicName AEB64D1BFFCAFFC5FE3BF923FBF3DA75] on 2022-12-19 ,  Donat claimed that [ Abrocoma bennetti ] should be replaced with [ Abrocoma bennettii ]

**Comment by jhpoelen** [comment]
See attached 2023-01-17 screenshots of:

https://tb.plazi.org/GgServer/html/E11F878EFFCAFFC5FF50F949FDC9DA9C

https://tb.plazi.org/GgServer/xml/E11F878EFFCAFFC5FF50F949FDC9DA9C 

related to:

treatment:
 E11F878EFFCAFFC5FF50F949FDC9DA9C
taxonomicName:
 AEB64D1BFFCAFFC5FE3BF923FBF3DA75

**Comment by jhpoelen** [comment]
Some time ago, I've attempted to update the issue to comply with the Plazi feedback protocol.

And it appears that the content of the treatment has not yet been updated. See e.g. screenshot attached of https://tb.plazi.org/GgServer/xml/E11F878EFFCAFFC5FF50F949FDC9DA9C . 


![image](https://user-images.githubusercontent.com/1084872/219067926-07cd7a43-2021-4d04-9a91-146c7be59b1a.png)



@flsimoes @myrmoteras please let me know if you need more information to correct this suspected OCR transcription error related to:

[treatment E11F878EFFCAFFC5FF50F949FDC9DA9C / taxonomicName AEB64D1BFFCAFFC5FE3BF923FBF3DA75] on 2022-12-19 , Donat claimed that [ Abrocoma bennetti ] should be replaced with [ Abrocoma bennettii ].

**Comment by myrmoteras** [comment]
@jhpoelen not sure whether Donat claimed this, because `benetti` is the original spelling and we do not make such changes to source text

![image](https://user-images.githubusercontent.com/4609956/219105438-fb385ed0-1aaa-4fc6-b735-d33e39cb2f6e.png)

**Comment by jhpoelen** [comment]
ok @myrmoteras Thanks for clarifying. Closing issue.
