### ISSUE TITLE
author wrong

### ISSUE THREAD

**Issue by myrmoteras** [plazi/community#222]
I found an error in BLR

https://zenodo.org/record/5281719/export/xd#.Y871LnbMIuV

which is http://treatment.plazi.org/id/313A87D7FFAE6B35AE262025FCAB4E3F

The authors are Patterson, David J. and Lee, WonJe.  The two have been combined.

Can you pass this on to see if the developers can fix the algorithm

thanks Paddy

**Comment by juwingert** [comment]
Hi Donat, it has been corrected already.
