### ISSUE TITLE
Fix needed for new combinations under Pygoda genus

### ISSUE THREAD

**Issue by dartar** [plazi/community#223]
The following 4 species redescribed with a new name in Fernandes, Nascimento & Nunes, 2018 have a spurious "Comb." in the authority reference string as captured in GBIF:
* Pygoda civilis (Breddin, 1903) Comb.
* Pygoda expolita (Distant, 1892) Comb.
* Pygoda irrorata (Dallas, 1851) Comb.
* Pygoda thoracica (Dallas, 1851) Comb.

* Pygoda polita <-- misses the author reference in GBIF

**Comment by valdenar** [comment]
Hi @dartar 
I corrected the Taxon Names authority. The information should update soon.
Thanks for your review

Best
