### ISSUE TITLE
Wrong Fungi Chrysididae family

### ISSUE THREAD

**Issue by mdoering** [plazi/community#225]
This dataset contains the hymenoptera family Chrysididae twice:

https://www.checklistbank.org/dataset/33631/names?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&limit=50&offset=0&q=Chrysididae&rank=family&status=accepted&status=provisionally%20accepted

Once wrongly under Fungi.

https://tb.plazi.org/GgServer/summary/FF9BFFE80C65E621D1255343631D483B

**Comment by mdoering** [comment]
Same problem here:
https://tb.plazi.org/GgServer/summary/FF9EFF935938FF8EFF4DFFEBFFAEFF82

https://www.checklistbank.org/dataset/34856/names?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&limit=50&offset=0&q=Chrysididae&sortBy=taxonomic

Looking at this dwca there are a few wrongly classified species like the following:

> 04867375F03A7C9D7DA3E18A2083FB98.taxon					Animalia	Ascomycota	Eurotiomycetes	Hymenoptera	Chrysididae	Stilbum	species	Stilbum calens (Fabricius 1781)	(Fabricius 1781)	Stilbum calens	Stilbum calens (Fabricius, 1781)	Fabricius	1781					https://treatment.plazi.org/id/04867375F03A7C9D7DA3E18A2083FB98

**Comment by mdoering** [comment]
Where is Ascomycota coming from? I cant find it anywhere in the original publication.

**Comment by juwingert** [comment]
Hi @mdoering, I'll fix these. I'll be back soon with the information.

**Comment by mdoering** [comment]
That reminds me we should properly discuss whether adding external classifications from COL,GBIF or others really is useful. I would prefer if we only had data found in the publication and not sth interpreted from elsewhere. We are feeding a circular pathway from Plazi to Col back to Plazi. The classification could be used at Plazi to organise data, but maybe we should not use it in the dwc archives at all. 

On the other hand some taxonomic context is very much needed. But that might better reside in the dataset metadata and apply to all treatments in an article?

**Comment by juwingert** [comment]
Hi, the problem was fixed. Cheers
