### ISSUE TITLE
GBIF dataset - html in title

### ISSUE THREAD

**Issue by ManonGros** [plazi/community#227]
This is an issue that was originally reported on the GBIF Portal feedback repo: https://github.com/gbif/portal-feedback/issues/4623

The title for this dataset (https://www.gbif.org/dataset/c8670273-a22c-4b4a-972d-38a43cd66f86) is `<p class = " HeadingRunIn " align = " left "> <strong> The genus <em> Hybos </ em> Meigen (Diptera: Empidoidea: Hybotidae) in Thailand </ strong> </ p>`. Would it be possible to remove the html? Thanks!

**Comment by flsimoes** [comment]
Just fixed it.
Thanks for notifying us!
