### ISSUE TITLE
linking directly into synospecies using http://taxon-concept.plazi.org/id/Animalia/Apis_mellifera_Linnaeus_1758

### ISSUE THREAD

**Issue by jhpoelen** [plazi/community#229]
Hi!

I was hoping to create a direct link from GloBI into synospecies, 'cause the visual representation of the taxonomic information looks pretty neat! See attached screenshot from https://synospecies.plazi.org/#Homo+sapiens . 

I was wondering if there's a way to directly link to synospecies if I know the plazi taxon concept id http://taxon-concept.plazi.org/id/Animalia/Apis_mellifera_Linnaeus_1758 , is there a way to directly link to synospecies instead of using a search by name.

If you have suggestion on how else to link into synospecies for taxa known to synospecies, please do let me know.

![Screenshot from 2023-04-04 17-31-41](https://user-images.githubusercontent.com/1084872/229937226-774d1ffd-46dd-482e-8799-632e2994a569.png)

**Comment by flsimoes** [comment]
@jhpoelen Sorry to have let it slip under, but I guess the people at FactsMission are more suited to answer you (if it hasn't been answered elsewhere already).
https://github.com/factsmission/synospecies/issues

**Comment by jhpoelen** [comment]
@flsimoes thanks - Would you be able to transfer this issue to the appropriate issue tracker to avoid duplicate work?

**Comment by flsimoes** [comment]
@jhpoelen I don't think there's another issue on the topic, but I just re-read your initial question and I believe there's no way to link them at the moment, at least not on the treatment bank stats pages we have.

**Comment by myrmoteras** [comment]
you need to discuss this with @nleanba @retog running synospecies!

**Comment by nleanba** [comment]
Currently, there is no such way. However, there are currently major changes in the works for how synospecies works under the hood; the current prototype is available under https://synospecies.plazi.org/next/ .
Note that the UI and features are still under construction and will change before it will become the default version.

The new version supports searching by a taxon-concept-url or taxon-name-url (simply enter it into the search bar). It uses the `?q=` URL parameter, so https://synospecies.plazi.org/next/?q=http://taxon-concept.plazi.org/id/Animalia/Apis_mellifera_Linnaeus_1758 works.

Note: however, these links will change (and lose the `/next/`) as soon as the new system is completed (i.e. at least as good as the status quo) and it replaces the current synospecies. Therefore I suggest waiting to implement direct links until this is done, or be prepared to change the links in the near-ish future.

**Comment by jhpoelen** [comment]
> Currently, there is no such way. 

Thanks for sharing and taking the effort to expand on the state of synospecies. 

Sounds like your infrastructure is not (yet?) setup for reuse beyond human actors. Please let me know if you are ready for such reuse cases.

**Comment by nleanba** [comment]
What do you mean by reuse by non-human actors?

If you have specific use-cases in mind, please let us know so we can consider building support for them.

**Comment by jhpoelen** [comment]
@nleanba

Thanks for taking the time to respond. 

> What do you mean by reuse by non-human actors?

In my mind, reuse of synospecies by non-human actors be automated alignment of thousands of taxonomic names in biodiversity datasets with associated synospecies concepts and name change histories. 

Such a reuse use-case would enable tools like https://github.com/globalbioticinteractions/nomer to integrate versioned snapshots of the synospecies corpus/dataset into existing name alignment workflows. 

Currently, it appears that the synospecies tooling is optimized around human centered point-and-click exploratory workflow, instead of automated batch workflows. 

Let me know if this help to better describe what I mean by reuse by non-human actors. If it doensn't please let me know, and I'll try again.
