### ISSUE TITLE
linzer_ beetle in the atlantic

### ISSUE THREAD

**Issue by myrmoteras** [plazi/community#23]
![image](https://user-images.githubusercontent.com/4609956/78973045-580a0900-7b0f-11ea-8477-fff025298088.png)
![image](https://user-images.githubusercontent.com/4609956/78973199-ae774780-7b0f-11ea-93ce-a7ad7e6bce88.png)

this has obviously the wrong coordinates?
http://tb.plazi.org/GgServer/html/03A1879CD851FFDF3CB4FCC33382FA08

FF98FFE4D855FFDA3C23FFBA323FFB66

**Comment by valdenar** [comment]
Hi Donat
Yes, there is something wrong with the coordinates. I will check and fix the problems.

**Comment by mguidoti** [comment]
@valdenar have you checked? fixed? if so, please, close the issue?

Thanks!

**Comment by flsimoes** [comment]
Update to this issue:

Since 16 October 2020 (at least) the document remains unreachable (see image below).

![image](https://user-images.githubusercontent.com/3343086/102505245-82c63d00-4060-11eb-9bd7-53eac355628f.png)

This most likely needs Guido to trigger something in the server.

**Comment by valdenar** [comment]
The coordinate error has been resolved.
