### ISSUE TITLE
can you please process these Pteronotus parnellii articles ? 

### ISSUE THREAD

**Issue by myrmoteras** [plazi/community#231]
* Dávalos, L. M., Lancaster, W. C., Núñez-Novas, M. S., León, Y. M., Lei, B., Flanders, J., & Russell, A. L. (2019). A coalescent-based estimator of genetic drift, and acoustic divergence in the Pteronotus parnellii species complex. Heredity, 122(4), Article 4. https://doi.org/10.1038/s41437-018-0129-3 
[s41437-018-0129-3.pdf](https://github.com/plazi/community/files/11269350/s41437-018-0129-3.pdf)

* Pavan, A. C., Bobrowiec, P. E. D., & Percequillo, A. R. (2018). Geographic variation in a South American clade of mormoopid bats, Pteronotus (Phyllodia), with description of a new species. Journal of Mammalogy, 99(3), 624–645. https://doi.org/10.1093/jmammal/gyy048 
[gyy048.pdf](https://github.com/plazi/community/files/11269377/gyy048.pdf)

* Pavan, A. C., & Marroig, G. (2016). Integrating multiple evidences in taxonomy: Species diversity and phylogeny of mustached bats (Mormoopidae: Pteronotus). Molecular Phylogenetics and Evolution, 103, 184–198. https://doi.org/10.1016/j.ympev.2016.07.011 
[1-s2.0-S1055790316301580-main.pdf](https://github.com/plazi/community/files/11269383/1-s2.0-S1055790316301580-main.pdf)

* Pavan, A. C., & Marroig, G. (2017). Timing and patterns of diversification in the Neotropical bat genus Pteronotus (Mormoopidae). Molecular Phylogenetics and Evolution, 108, 61–69. https://doi.org/10.1016/j.ympev.2017.01.017 
[1-s2.0-S1055790317300908-main.pdf](https://github.com/plazi/community/files/11269397/1-s2.0-S1055790317300908-main.pdf)

* DÁVALOS, L. M. (2006). The geography of diversification in the mormoopids (Chiroptera: Mormoopidae). Biological Journal of the Linnean Society, 88(1), 101–118. https://doi.org/10.1111/j.1095-8312.2006.00605.x 
[j.1095-8312.2006.00605.x.pdf](https://github.com/plazi/community/files/11269402/j.1095-8312.2006.00605.x.pdf)

**Comment by flsimoes** [comment]
> * Dávalos, L. M., Lancaster, W. C., Núñez-Novas, M. S., León, Y. M., Lei, B., Flanders, J., & Russell, A. L. (2019). A coalescent-based estimator of genetic drift, and acoustic divergence in the Pteronotus parnellii species complex. Heredity, 122(4), Article 4. https://doi.org/10.1038/s41437-018-0129-3
>   [s41437-018-0129-3.pdf](https://github.com/plazi/community/files/11269350/s41437-018-0129-3.pdf)
> * Pavan, A. C., Bobrowiec, P. E. D., & Percequillo, A. R. (2018). Geographic variation in a South American clade of mormoopid bats, Pteronotus (Phyllodia), with description of a new species. Journal of Mammalogy, 99(3), 624–645. https://doi.org/10.1093/jmammal/gyy048
>   [gyy048.pdf](https://github.com/plazi/community/files/11269377/gyy048.pdf)
> * Pavan, A. C., & Marroig, G. (2016). Integrating multiple evidences in taxonomy: Species diversity and phylogeny of mustached bats (Mormoopidae: Pteronotus). Molecular Phylogenetics and Evolution, 103, 184–198. https://doi.org/10.1016/j.ympev.2016.07.011
>   [1-s2.0-S1055790316301580-main.pdf](https://github.com/plazi/community/files/11269383/1-s2.0-S1055790316301580-main.pdf)

This one was previously processed in 2020:
https://tb.plazi.org/GgServer/summary/111DFFA1AE3A751FFF83FFE4D50B0F11
https://zenodo.org/record/3909283#.ZD_WaXbMIuU

> * Pavan, A. C., & Marroig, G. (2017). Timing and patterns of diversification in the Neotropical bat genus Pteronotus (Mormoopidae). Molecular Phylogenetics and Evolution, 108, 61–69. https://doi.org/10.1016/j.ympev.2017.01.017
>   [1-s2.0-S1055790317300908-main.pdf](https://github.com/plazi/community/files/11269397/1-s2.0-S1055790317300908-main.pdf)
> * DÁVALOS, L. M. (2006). The geography of diversification in the mormoopids (Chiroptera: Mormoopidae). Biological Journal of the Linnean Society, 88(1), 101–118. https://doi.org/10.1111/j.1095-8312.2006.00605.x
>   [j.1095-8312.2006.00605.x.pdf](https://github.com/plazi/community/files/11269402/j.1095-8312.2006.00605.x.pdf)
