### ISSUE TITLE
Incomplete processing of names in a Phytoketys article

### ISSUE THREAD

**Issue by DianRHR** [plazi/community#233]
I downloaded the content of the article  ﻿Five new synonyms for Impatiens procumbens (Balsaminaceae) in China
https://doi.org/10.3897/phytokeys.222.97087

that is available in Checklist Bank https://www.checklistbank.org/dataset/240548/about

but got an incomplete list of taxa (not all the syonyms are included). 
![image](https://user-images.githubusercontent.com/124217901/234685000-9152b0a3-0b37-4536-9da3-7de183b1ee69.png)

**Comment by DianRHR** [comment]
Also, the checklist generated, does't include the authorship of each taxa, even that the article includes this information.

**Comment by flsimoes** [comment]
TB: https://tb.plazi.org/GgServer/summary/A2066AD53F295CD4B278A5D20D4AC010

**Comment by juwingert** [comment]
Dear @DianRHR , the taxonomic names attributes was fixed. Thanks for your feedback.

**Comment by DianRHR** [comment]
Thanks @juwingert  the downloadable file in https://www.gbif.org/dataset/dc176eaa-dec9-43b7-a355-1934b41407ab still has just 1 accepted name. 
![image](https://github.com/user-attachments/assets/eec0f1b9-7ff3-4d9d-9430-2b0bb44c6a03)

therefore in [ChecklistBank](https://www.checklistbank.org/dataset/240548/imports) occurs the same.

**Comment by juwingert** [comment]
Hi @DianRHR , now it's available. Thanks again.

![image](https://github.com/user-attachments/assets/a371a9ca-4439-46a7-a618-b92d670a331c)
