### ISSUE TITLE
paeonia requests

### ISSUE THREAD

**Issue by myrmoteras** [plazi/community#234]
Please process after we decided in regards of the tables.
* Zhou 2020
(https://github.com/plazi/community/files/11371036/journalOfSystematicsEvolution2020.-.Zhou.-.Out.of.the.Pan.Himalaya.Evolutionary.history.of.the.Paeoniaceae.revealed.by.pdf)

**Comment by flsimoes** [comment]
TB: [FFA2FF9C992647335F5BCF37FFB2DE5F](https://tb.plazi.org/GgServer/summary/FFA2FF9C992647335F5BCF37FFB2DE5F)

BLR: [7888942](http://zenodo.org/record/7888942)
