### ISSUE TITLE
 vitis vinifera requests

### ISSUE THREAD

**Issue by myrmoteras** [plazi/community#235]
Here are a couple of PDF to be processed that include phylogenies and tables. 

Please process them once we agree how we deal with this, since the table are in auxiliary material.  
* De michele et al. 2019 
[frontiersInPlantScience-10-01506.pdf](https://github.com/plazi/community/files/11370578/frontiersInPlantScience-10-01506.pdf)
* Wan et a., 2013 https://bmcecolevol.biomedcentral.com/articles/10.1186/1471-2148-13-141 and not to be processed supplement https://datadryad.org/stash/dataset/doi:10.5061/dryad.s1s75
   * The question here is how to deal with the trees that are large on include three consecutive figures. Should they be combined or not?
* Ma et al., 2018, Phylogenomics, biogeography, and adaptive radiation of grapes 
[molecularPhylogeneticsEvolution.129.258-267.pdf](https://github.com/plazi/community/files/11371801/molecularPhylogeneticsEvolution.129.258-267.pdf). includes supplementary material as table added to the pdf
* Zecca, 2020. Untangling the Evolution of American Wild Grapes: Admixed Species and How to Find Them 
[fpls-10-01814.pdf](https://github.com/plazi/community/files/11371917/fpls-10-01814.pdf) includes supplementary material as table added to the pdf

**Comment by valdenar** [comment]
Link to BLR
[FrontPlantSci.10.1-14.pdf](https://zenodo.org/record/7888658#.ZFG0-XbMKUk)
[MolPhylogenetEvol.129.258-267.pdf](https://zenodo.org/record/7888600#.ZFGza3bMKUk)

**Comment by flsimoes** [comment]
Wan et a., 2013
TB: [2F4B6729FFF8FFAD655AFFC73B30FFF7](https://tb.plazi.org/GgServer/summary/2F4B6729FFF8FFAD655AFFC73B30FFF7)
BLR: [7888989](http://zenodo.org/record/7888989)

Zecca, 2020
TB: [FFC7FFE3FFCB7625FFBE7734FFF2FF87](https://tb.plazi.org/GgServer/summary/FFC7FFE3FFCB7625FFBE7734FFF2FF87)

BLR:
