### ISSUE TITLE
Rosa phylogeny

### ISSUE THREAD

**Issue by myrmoteras** [plazi/community#236]
this includes a supplement file where each specimen is listed as paragraph. 
* Fougère-Danezan
[annalsBotany.115.275-291.pdf](https://github.com/plazi/community/files/11371980/annalsBotany.115.275-291.pdf)

here the tipLabel

![image](https://user-images.githubusercontent.com/4609956/235637565-efea398f-062a-47a8-877a-6667bbdd8627.png)

**Comment by juwingert** [comment]
Hi Donat, here go:

[Zenodo - 7888909](https://zenodo.org/record/7888909#.ZFG603bMKUk)

[GBIF - 70d2f55c-340f-4636-a9ef-02b031d58324](https://www.gbif.org/dataset/70d2f55c-340f-4636-a9ef-02b031d58324)

[TB - BC1DA267794CFFD30244FF87EA31FFCF](https://tb.plazi.org/GgServer/summary/BC1DA267794CFFD30244FF87EA31FFCF)

**Comment by myrmoteras** [comment]
@juwingert tx. can you please  check, why the material citations not the species do show up in GBIF. Did you do the QC?

**Comment by juwingert** [comment]
@myrmoteras I'm not sure if I understand your question, but I double-checked and didn't find anything odd.

**Comment by myrmoteras** [comment]
@juwingert the problem is solved. It was an issue on GBIF-side.
Tx for looking into it
