### ISSUE TITLE
reference group should be synonymic list?

### ISSUE THREAD

**Issue by myrmoteras** [plazi/community#238]
@flsimoes @jugiora  looking at this https://github.com/plazi/community/issues/237 when checking on the susSubSection types I think this 
![image](https://github.com/plazi/community/assets/4609956/28b16aa3-cb03-4b1a-8e19-a8a37e321780)

should be a type=taxon_list (thanks @flsimoes ). A reference_group is for TreatmentCitations

**Comment by flsimoes** [comment]
It's actually taxon_list
