### ISSUE TITLE
DwC-A issues for Euptychiina (Nymphalidae, Satyrinae) paper https://doi.org/10.15468/32v5r7

### ISSUE THREAD

**Issue by camiplata** [plazi/community#239]
There are some issues in the [DwC-A of the checklist](https://www.gbif.org/dataset/bfb878f3-8a74-46d3-a104-36485c32aaba) associated to the treatments of the paper [Combining target enrichment and Sanger sequencing data to clarify the systematics of the diverse Neotropical butterfly subtribe Euptychiina (Nymphalidae, Satyrinae)](https://doi.org/10.1111/syen.12590), I noticed that by merging this dataset with some other Satyrinae sources on checklistBank.

1. Incorrect Authorship

In the DwC-A Many of the authorships of the new genera have the full list of the paper authors and no the author of the new genera for example:
- Saurona Espeland1, Nakahara, Zacca, Barbosa, Huertas, Marín, Lamas, Benmesbah, Brévignon, Casagrande, Fåhraeus, Grishin, Kawahara1, Mielke, Miller, Nakamura, Navas, Patrusky, Pyrcz, Richards, Tan, Tyler, Viloria, Warren1, Xiao, Freitas, and Willmott 2023 instead of  `Saurona Huertas & Willmott, 2023`

Although on the final scientificName the author are incorrect, the verbatim information is correct
<img width="300" alt="Captura de pantalla 2023-05-12 a la(s) 12 07 29 p m" src="https://github.com/plazi/community/assets/5700527/400b4c4e-fa42-47d6-a16f-27e4a69db1be">

The information also looks correct on TreatmentBank so it looks like a particular problem of the DwC-A:
<img width="300" alt="Captura de pantalla 2023-05-12 a la(s) 12 18 25 p m" src="https://github.com/plazi/community/assets/5700527/64de805d-a1e1-42d2-8818-93cac5338529">

2.  Higher taxonomy is missing

The following information is missing probably because is on the scope of the paper but not on the treatments
    Subfamily: Satyrinae
    Tribe:  Satyrini (I'm providing the information, the tribe was not mentioned on the paper)
    Subtribe: Euptychiina

3. Synonyms incorrectly placed
This happens for all the new combinations proposed by the paper, here an example for clarity:

Taygetis Hubner 1819 (03EC879FFFB3FFCCA875AF90FD951641.taxon.syn1), is placed as a synonym of  Taguaiba Freitas, Zacca & Siewert 2023 (03EC879FFFB3FFCCA875AF90FD951641.taxon), but the paper actually refers to several new combinations and not to a genera synonym see https://treatment.plazi.org/id/03EC879FFFB3FFCCA875AF90FD951641 where the relationships and links direct to the species synonyms. 

Probably this issue comes from the fact that in the paper the synonym binomials are no explicitly presented only explain, but I think is a valuable fix so this dataset can be better use in GBIF and Checklistbank.

4. Incorrect Higher taxonomy

The genus [Stephenympha](https://www.checklistbank.org/dataset/58039/classification?taxonKey=03EC879FFFB1FFCEA875AF4BFDF21428.taxon) is placed as a Plant an not as Lepidoptera, I see the issue has benn adress already in TreatmentBank but is pending on the DwC-A

5. Journal name interpreted as a genus

This issue probably affects more than one dataset so I have created a specific issue #240

**Comment by truschel** [comment]
Hi @camiplata 

I checked the errors you pointed out and it looks like everything is correct now, including the issues #240 and #241.

I added the informations regarding subfamily, tribe and subrtribe that you informed us for _Saurona_ and _Argentaria_.

https://tb.plazi.org/GgServer/summary/FFD5FFE7FF8FFFF0A80FAB7BFFAB1055

Thank you for your message. 

Please feel free to contact us if you have any other questions.

Cheers,
Tatiana

**Comment by camiplata** [comment]
Hi Tatiana, thank you for addressing these issues. And sorry to come back so late to this thread.

 I'm wondering if would it be possible to add the higher taxonomy to the DWC. 

  Subfamily: Satyrinae
  Tribe: Satyrini
  Subtribe: Euptychiina

**Comment by flsimoes** [comment]
@camiplata sorry for the absurdly late response, but I've now added the requested higher taxonomy

**Comment by camiplata** [comment]
Thank you @flsimoes  the higher taxonomy is going to be very helpful for us ;)
