### ISSUE TITLE
EJT - taxonomic names with epithets "sp."

### ISSUE THREAD

**Issue by valdenar** [plazi/community#24]
Hello Donat,
 In the EJT - European Journal of Taxonomy we have cases of epithets of the species being determined as "sp.". How should we proceed in such cases? I'll send you an example below.

![image](https://user-images.githubusercontent.com/57402751/79133338-41b7b380-7d82-11ea-9cd9-c4d883090f7e.png)

Link to PDF: https://drive.google.com/open?id=15FsbfuUEe1DgTpsArzmeDxXDQVjJZSGK
Link to IMF: https://drive.google.com/open?id=1MUIN9yumitTaYpkx84LDqdPo7vihELIF

**Comment by valdenar** [comment]
Hi Donat, we have another example 

link to PDF: https://drive.google.com/open?id=1g-0FZSc4m4rvy0UGwB_qapCEUVw2rKko
link to IMF: https://drive.google.com/open?id=1oWAxt7tfZWX4-wgh0luP5wnO3OPbIQMi

![image](https://user-images.githubusercontent.com/57402751/79357897-fb478d80-7f16-11ea-8e93-1a89160249c7.png)

**Comment by myrmoteras** [comment]
I tag them as rank=species and species = "sp." Or "sp.1" respectively

**Comment by valdenar** [comment]
OK, thank you so much for your attention.
