### ISSUE TITLE
incomplete authority

### ISSUE THREAD

**Issue by myrmoteras** [plazi/community#242]
https://treatment.plazi.org/id/03E787C55E37736FFF3BB172D58F7232 is not well done

![image](https://github.com/plazi/community/assets/4609956/f3f61d7f-91f2-4135-8e56-995ec8fd2507)

can you check for similar cases with slipinski?

**Comment by diegojalvares** [comment]
I have resolved this one. 
It seems to occur when GGI decoding encounters special characters and makes splits in the text. However, I am uncertain about the specific approach to searching for similar cases in TB stats.

**Comment by flsimoes** [comment]
Here's all occurences of Slipinski, filtered by `%lipi%`:

https://tb.plazi.org/GgServer/srsStats/stats?outputFields=tax.name+tax.authority&groupingFields=tax.name+tax.authority&orderingFields=tax.authority&FP-tax.authority=%22%25lipi%25%22&format=HTML

And here's one filtered by `S%l%ski%`:

https://tb.plazi.org/GgServer/srsStats/stats?outputFields=doc.articleUuid+tax.name+tax.authority&groupingFields=doc.articleUuid+tax.name+tax.authority&orderingFields=tax.authority&FP-tax.authority=%22S%25l%25ski%25%22&format=HTML

There's a few wrongly assigned authorities, but I didn't spot anything like the one you reported.
