### ISSUE TITLE
4 Parena genera in dwca of Taxonomic revision of the genus Parena Motschulsky, 1860 (Coleoptera, Carabidae, Lebiini, Metallicina)

### ISSUE THREAD

**Issue by mdoering** [plazi/community#244]
https://www.checklistbank.org/dataset/263342/classification?taxonKey=xD
<img width="1125" alt="image" src="https://github.com/plazi/community/assets/327505/ad071f39-a639-409d-82a9-39a96aa0a6fd">

The genus Parena is listed 4 times in the dwca. 
[Treatment Bank](https://tb.plazi.org/GgServer/summary/FFBE0E5B6246FFE32D78B27BFFE75D5A) instead has a genus, a subgenus and 2 keys to the genus.

This is confusing. a) one record should be the subgenus, not genus. b) should we exclude key treatments or at least find ways to share them in a way that it is understood these are keys? Also why is the entire key thought of as a single treatment of the root taxon, while all its included taxa / species are considered treatment citations? 

Maybe sharing keys as separate datasets would be better with every taxon in there as a taxon record.
Thats how we plan to bring other keys into the dwc world, e.g. https://identification-resources.github.io/

**Comment by flsimoes** [comment]
> This is confusing. a) one record should be the subgenus, not genus. b) should we exclude key treatments or at least find ways to share them in a way that it is understood these are keys? Also why is the entire key thought of as a single treatment of the root taxon, while all its included taxa / species are considered treatment citations?

a) Indeed, we'll fix this right away (should be updated already by now)
b) If the key is in a separate of the paper, as in not immediately after the treatment, the default is to have them tagged as separate treatments as this would require heavy text manipulation linking words from different pages in a different order than the one provided in the publication.
