### ISSUE TITLE
specimens in the sea

### ISSUE THREAD

**Issue by myrmoteras** [plazi/community#247]
Might it be possible that somebody checks first thing in the morning suspicious specimens in the Plazi.org homepage map? Erroneous specimens should be removed within 24 hours, eg 
![image](https://github.com/plazi/community/assets/4609956/6632748b-b252-45c7-94a2-72330809fe2c) https://tb.plazi.org/GgServer/html//038787BCF43873005988F98A5AD9DD36 
on 2023-06-03

**Comment by valdenar** [comment]
Hi Donat,
This species highlighted in the image is in the correct location, the small island of Saint Helena. There is a second case there, which is an Anuro, this one had the wrong geographic coordinates, I made the correction and am waiting for the update.

We have a dynamic in the office where each week we have a team member who is responsible for checking the map in the morning and making the necessary corrections. So as soon as we identify this problem we will correct it.

best regards,
Valdenar

**Comment by myrmoteras** [comment]
@plazi/poa-office thanks for this - very good
