### ISSUE TITLE
Polistes (Fuscopolistes) Fuscopolistes

### ISSUE THREAD

**Issue by mdoering** [plazi/community#249]
The subgenus Fuscopolistes is given as _genus_ `Polistes (Fuscopolistes) Fuscopolistes` in the dwca archive.
http://treatment.plazi.org/id/B67C1D44FF92204F4F9FF90AFE46F983

See https://github.com/gbif/portal-feedback/issues/4750

Should probably be _subgenus_ `Polistes (Fuscopolistes)` instead

**Comment by flsimoes** [comment]
That was indeed the case, thanks!
I've just fixed that, hope it transits nicely to the dwca.
Let me know if anything else needs fixing in this one.
