### ISSUE TITLE
EJT - Headings of identification keys without taxonomic names

### ISSUE THREAD

**Issue by valdenar** [plazi/community#25]
Hi Donat,
In EJT we have an article that has identification keys for species with headings without taxonomic names. therefore, the keys are not marked by the template and manual marking is also not possible. In this case shown below, the key belong to groups of species and treatments are presented after the key. How could we mark the keys?

Link to PDF: https://drive.google.com/open?id=1wrEby6tx0RzVJmPeTxHUFkVFzw2JLZRb
Link to IMF: https://drive.google.com/open?id=15lODpZ-T6BLjLBqmNtMjGoiCiRsydgnl

![image](https://user-images.githubusercontent.com/57402751/79157511-172e2080-7dab-11ea-8e10-1953b1513e9d.png)

**Comment by flsimoes** [comment]
I had a similar issue in ZooKeys (I will try to find the example).
My solution was to mark the word "species" as a taxonomicName. Then, I copied the attributes from the genus from somewhere else in the paper. It seems to have solved it.

**Comment by flsimoes** [comment]
http://publication.plazi.org/id/FF821D7BFFFFBE3CFFCFFFC75F63F619

This one.

**Comment by mguidoti** [comment]
It seems a pretty good strategy to me.

@valdenar could you please go through doing this?

**Comment by valdenar** [comment]
Link to TB:
http://publication.plazi.org/id/FFA0FFD93812FFCE2949FFEEFF9CFF98
