### ISSUE TITLE
genus named "Hyla Quoyi-Hyla Prasina Case" 

### ISSUE THREAD

**Issue by ahahn-gbif** [plazi/community#250]
In: Dubois, Alain, Ohler, Annemarie (2018): The Hyla quoyi-Hyla prasina case (Amphibia, Anura), with comments on bibliographic and taxonomic databases and on Article 23.9 of the Code. Zoosystema 40 (23): 501-506, DOI: 10.5252/zoosystema2018v40a23

Through https://www.gbif.org/dataset/c35887df-f50e-4c13-8b29-5f23d0e1df75 (treatment article "The Hyla quoyi-Hyla prasina case (Amphibia, Anura), with comments on bibliographic and taxonomic databases and on Article 23.9 of the Code"), this name is presently indexed in GBIF.org as a genus (https://www.gbif.org/species/176230819). "QUOYI – HYLA PRASINA CASE" is interpreted as the combination authors (see https://www.gbif.org/species/176230819/verbatim), which seems to be the root cause.

**Comment by truschel** [comment]
Hi @ahahn-gbif 

I fixed it for the treatment have the name of the valid species.

Thank you for your message.

Please feel free to contact us if you have any other questions.

Cheers,
Tatiana
