### ISSUE TITLE
Name capitalised in treatment leads to GBIF misinterpreting them

### ISSUE THREAD

**Issue by ManonGros** [plazi/community#251]
The paper concerned: ilho, Petrônio Alves Coelho (2006): Checklist of the Decapods (Crustacea) from the outer continental shelf and seamounts from Northeast of Brazil REVIZEE Program (NE III). Zootaxa 1184: 1-27, DOI: 10.5281/zenodo.2645999

The dataset concerned: https://www.gbif.org/dataset/2c234fee-9c05-4a6c-bd50-438312240644

For some reason, many scientific names have capital letter for the epitaph, for example `Symethis Variolosa (Fabricius 1793)` https://www.gbif.org/species/156789277/verbatim which makes GBIF interpret it as `spec.`.
Would it be possible to check the dataset?

See the original issue reported on the GBIF feedback portal: https://github.com/gbif/portal-feedback/issues/4807

**Comment by truschel** [comment]
Hi @ManonGros 

I fixed the problem (see below), but it may take a while to update in GBIF.

https://tb.plazi.org/GgServer/summary/FFBDFF8EA876266AFFAFFFC872061B35

Thank you for your message.

Cheers,
Tatiana
