### ISSUE TITLE
Treatment to be split

### ISSUE THREAD

**Issue by ChrFerrer** [plazi/community#253]
Hello, below is a treatment to be split into 2 parts, one for the genus _Polarasterias_, the other for the species _Polarasterias janusensis_:

- http://publication.plazi.org/GgServer/html/BD4787A8FFB0D36F0B5DF9F0FEE701AA

**Comment by jugiora** [comment]
Hi.
The treatment was splited and the paper was fixed.
Thanks for your contributions.

**Comment by ChrFerrer** [comment]
Ok thank you for the explanation, I did not know that the simple mention of the type of a genus was considered as treatment for that genus. Now I know.
