### ISSUE TITLE
Gale & Jagt (2021)

### ISSUE THREAD

**Issue by ChrFerrer** [plazi/community#254]
- [This treatment](http://publication.plazi.org/GgServer/html/F160A367717DFFB9FDAC7435FC1023C4) should be suppressed as it is not really a treatment.
- [This treatment](http://publication.plazi.org/GgServer/html/F160A3677153FF97FDF5740DFC652563) should be renamed to "_Henricia venturana_"

**Comment by juwingert** [comment]
Hi @ChrFerrer, I'll check and return. Thanks

**Comment by juwingert** [comment]
@ChrFerrer in the first case, it is indeed a treatment. In other words, any information regarding a taxon, whether it be a description, diagnosis, or even the type of material, is a treatment.

In the second case, it was changed.

Best regards.

**Comment by juwingert** [comment]
@ChrFerrer  In the first case, it is indeed a treatment. In other words, any information regarding a taxon, whether it be a description, diagnosis, or even the type of material, is a treatment.

In the second case, it was changed.
