### ISSUE TITLE
Abbreviation is resolved incorrectly

### ISSUE THREAD

**Issue by ManonGros** [plazi/community#256]
Hi Plazi,

One of my colleagues and I noticed that "TMS" for [this treatment](https://treatment.plazi.org/id/D27B87A3FFB1F132FEDBF94691CDFC13/2) is resolved as the "Toleco Museum of Health and Natural History" when in the original publication, it stand for "Thin Marginal Seta".

Could someone check the treatment? Thanks!

**Comment by flsimoes** [comment]
Thanks for letting us know!
Fixed
