### ISSUE TITLE
"checklist of ciliates (Ciliophora) inhabiting on ostracods (Crustacea, Ostracoda)" has bad dwca data

### ISSUE THREAD

**Issue by mdoering** [plazi/community#257]
See https://github.com/CatalogueOfLife/checklistbank/issues/1260
For example see verbatim data for [Loxophyllum helus](https://www.checklistbank.org/dataset/46512/taxon/AA61DC68FFB50324FF43FCC0FE33FAFE.taxon):

```
dwc:scientificName: Loxophyllum helus (Stokes 1884) (Stokes, 1884) Penard 1922
dwc:scientificNameAuthorship: (Stokes 1884) (Stokes, 1884) Penard 1922
```

**Comment by mdoering** [comment]
also the classification and more odd authorships

**Comment by truschel** [comment]
Dear all
I was working on the two papers mentioned here https://github.com/CatalogueOfLife/checklistbank/issues/1260

Here are the links for both on TB:
1. https://treatment.plazi.org/GgServer/summary/5658A410FFBA032BFFD4FFDFFA7DFF86
and the treatment mentioned https://treatment.plazi.org/id/AA61DC68FFB50324FF43FCC0FE33FAFE

2. https://treatment.plazi.org/GgServer/summary/FF9750679F768866350DB059FFA4BA37
and the treatment mentioned https://treatment.plazi.org/id/03AE281F9F718861359AB557FC96BFCC

The first one presented taxonomicNames with incorrect attributes for authorityName. The baseAuthorityName attribute was missing and the authorityName attribute had two author names. So I fixed it, as well the kingdom for all taxonomic names in the paper, as pointed by @kbseah.

Before I fix:

![image](https://github.com/plazi/community/assets/57402704/5801e83b-a8cd-4456-b40d-6bc38d961a55)

Later:
![image](https://github.com/plazi/community/assets/57402704/e3da2f39-c9b9-41b0-b401-88ea527e2187)

However, the species name in checklistbank is the same:
https://www.checklistbank.org/dataset/46512/taxon/AA61DC68FFB50324FF43FCC0FE33FAFE.taxon

The second paper present correct taxonomicName attributes:
![image](https://github.com/plazi/community/assets/57402704/98d26384-6265-4a01-a8a8-3773c3ec4037)
And here how it is in checklistbank:
https://www.checklistbank.org/dataset/23066/taxon/03AE281F9F718861359AB557FC96BFCC.taxon

Maybe an import error? gsautter @myrmoteras any idea how we can deal with this problem?

Cheers

**Comment by myrmoteras** [comment]
May be @Markus Döring ***@***.******@***.***> can contribute as well?!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by mdoering** [comment]
Is this a very recent change? CLB is in read only mode since Monday and no imports are running all week

**Comment by myrmoteras** [comment]
@truschel when did you make the changes?

**Comment by truschel** [comment]
@myrmoteras I did yesterday.
