### ISSUE TITLE
Consider complete extraction of  Mammals of the World

### ISSUE THREAD

**Issue by camiplata** [plazi/community#259]
There is only one treatment associated to Wilson, Don E. & Mittermeier, Russel A., 2011, please consider extracting the entire source:

<img width="678" alt="Captura de pantalla 2023-10-23 a la(s) 12 55 10 p m" src="https://github.com/plazi/community/assets/5700527/22d29d36-1455-4ca0-b6e0-b25daac6192a">

This renders a single species list on GBIF and checklistBank

<img width="798" alt="Captura de pantalla 2023-10-23 a la(s) 12 56 52 p m" src="https://github.com/plazi/community/assets/5700527/83cb30c2-5c30-4e1a-b4d5-d5c29590244e">

Thanks!

**Comment by flsimoes** [comment]
@myrmoteras do we have access to the rest of the publication. It seems that the _Canis lupus_ part is the only one present in our source document?

**Comment by myrmoteras** [comment]
@camiplata  this is aduplicate. The entire listing of Canidae is here https://tb.plazi.org/GgServer/summary/FF95B738BF37FFC97E1BFF90FFDBDD06 and here is Canis lupus https://tb.plazi.org/GgServer/html/03ACCF40BF35FFCB7E8BFE3EFA16D72F

and here are all the taxa, including subspecies of Canis lupus https://tb.plazi.org/GgServer/srsStats/stats?outputFields=doc.uuid+bib.source+tax.name+tax.genusEpithet+tax.speciesEpithet&groupingFields=doc.uuid+bib.source+tax.name+tax.genusEpithet+tax.speciesEpithet&FP-tax.genusEpithet=Canis&FP-tax.speciesEpithet=lupus&format=HTML
