### ISSUE TITLE
misinterpreted data - GBIF dataset - https://mapress.com/zt/article/view/zootaxa.5264.4.3/50474

### ISSUE THREAD

**Issue by spalp** [plazi/community#260]
1. The following records in GBIF with _Trechurus cardioderus athonis_ are with misinterpreted institution code ('r, bfus', 'r, nmnhs'): https://www.gbif.org/occurrence/search?dataset_key=ee639eb0-bf6f-410b-a903-21665b3bdb85&institution_code=r,%20bfus, https://www.gbif.org/occurrence/4097195309).  In the article, the misinterpreted paragraph is on p. 508, named **_Other material examined_**. Some also have a misinterpreted dates: "_Stara planina Mts.: 1:male_sign:, Kalofer, ecopath “Byala reka”, N42.65990 E24.95974, **06.08.2019**, R. Bekchiev leg. (BFUS)_"; “_Varshiloto” Place, N41.323117 E23.188700, **09.07.2008,** R. Bekchiev leg. (NMNHS)_"
2. Some records in GBIF with _Trechurus cardioderus athonis_ are with misinterpreted institution code 'r, mnhn' (should be just 'mnhn') BUT the name of collector (Jeannel) was also misinterpreted as Municipality for some of the records (e.g those in Greece and Albania): https://www.gbif.org/occurrence/search?dataset_key=ee639eb0-bf6f-410b-a903-21665b3bdb85&institution_code=r,%20mnhn
3. Records of _Trechurus cardioderus irenis_ with the institution code: 'nmnhs, r, bfus' have misinterpreted specimen data (locations, institution code, collectors and dates): https://www.gbif.org/occurrence/search?dataset_key=ee639eb0-bf6f-410b-a903-21665b3bdb85&institution_code=nmnhs,%20r,%20bfus. In the article, the misinterpreted paragraph is on p. 512, named **_Other material examined_**.
4. Some records in GBIF with _Trechurus strandzhensis_ are with misinterpreted institution codes 'r' and 'r, nmnhs': https://www.gbif.org/occurrence/search?dataset_key=ee639eb0-bf6f-410b-a903-21665b3bdb85&institution_code=r). The correct code is 'NMNHS'.  In the article, the misinterpreted paragraphs are on p. 513, named **_Holotype_** and **_Paratype_**.

In all of the above cases, the institution code 'r' comes from the first initial of the collector and should be removed. However, the p. 3 require greater attention.

Do you think these could be corrected?

**Comment by valdenar** [comment]
Hi @spalp,
I made corrections to the material examined and the changes will be available as soon as the system updates
Thank you for contacting us regarding this issue

Valdenar Gonçalves

**Comment by spalp** [comment]
Hi @valdenar, thank you for the fast reaction.
It is getting better but I still see the followiing strange codes here: https://www.gbif.org/occurrence/search?dataset_key=ee639eb0-bf6f-410b-a903-21665b3bdb85&institution_code=v,%20mnhn&institution_code=r,%20mnhn&institution_code=r

**Comment by valdenar** [comment]
Hi @spalp 
This pepar did not have a previously accurate correction of the data. I made the corrections to the treatments you requested, so the other treatments still had issues. 
I made corrections to the new treatments requested and the changes will be available as soon as the system updates. 

Valdenar Golçalves

**Comment by spalp** [comment]
Thank you @valdenar. I do not see any more problems with the institution codes. Keep up the good work!
