### ISSUE TITLE
misinterpreted data - GBIF dataset - https://treatment.plazi.org/id/7126879A3A748D2FE8A2A0D0FAACFE0A#49E73CD13A748D24EC35A216FA9CFD0D

### ISSUE THREAD

**Issue by spalp** [plazi/community#262]
In the following record: https://www.gbif.org/occurrence/4424048301 the field "Recorded by" is populated with "W Rhodopes Mts & P. Drensky". In the above "W Rhodopes Mts" is a mountain's name. Only "P. Drensky" is the collector.

**Comment by JonasBlanco** [comment]
Hi!

I fixed the record, soon it should update on GBIF.

Kind regards,

**Comment by spalp** [comment]
Hi @JonasBlanco  

Thanks a lot. 
I found the same issue also with: https://treatment.plazi.org/id/7126879A3A748D2FE8A2A0D0FAACFE0A#49E73CD13A748D24EC35A216FA9CFD0D. And here is the associated GBIF occurrence: https://www.gbif.org/occurrence/4424048301

Could you also fix this one?
Salza

**Comment by JonasBlanco** [comment]
Hi!

You sent me the same record as the first one.
What we need to do is to wait for a bit, the records may take some time to update on GBIF after being fixed by us.
I just checked and it did not update yet.

Cheers,
