### ISSUE TITLE
Insects are listed as plants: Magnificus (Lepidoptera, Hepialoidea , Hepialidae)

### ISSUE THREAD

**Issue by ktotsum** [plazi/community#263]
We received user feedback on GBIF as below.

The genus Magnificus Yang 2000 seems to be wrongly placed under plants instead of insects.

**Context**
[GBIF species](https://www.gbif.org/species/177316880)
[Plazi reference](https://treatment.plazi.org/id/03E987879B2BDA51A39AFF129BEEF859)

See the original issue reported on the GBIF feedback portal: https://github.com/gbif/backbone-feedback/issues/67

**Comment by juwingert** [comment]
Thanks @ktotsum, I'll check.

**Comment by juwingert** [comment]
Dear @ktotsum the error was fixed. Thanks for your feedback.
