### ISSUE TITLE
Incorrect higher taxonomy for Synergus Hartig - https://doi.org/10.11646/zootaxa.4906.1.1

### ISSUE THREAD

**Issue by ManonGros** [plazi/community#264]
Hi Plazi,

We recently received a feedback message: https://github.com/gbif/backbone-feedback/issues/64 which made me realise that the higher taxonomy for this dataset https://www.gbif.org/dataset/308129a3-a99f-4012-bb41-d3220692c398 is incorrect. The paper is about Synergus Hartig (Hymenoptera: Cynipidae) see also: https://www.gbif.org/species/1176773

But the higher taxonomy in the dataset is the one of Synergus J.Faust, 1895 a Curculionidae (https://www.gbif.org/species/8428248). Which means all the wasps in the dataset are shown in the weevil group.

Would it be possible to update the dataset? Thanks!

**Comment by truschel** [comment]
Hi @ManonGros,
I fixed the order and family names. Soon the dataset will be updated.
Thanks for the message.

Best regards,
Tatiana

**Comment by ManonGros** [comment]
Thank you Tatiana!
