### ISSUE TITLE
wrong subspecies

### ISSUE THREAD

**Issue by myrmoteras** [plazi/community#266]
this is not a subspecies but a species.

https://zenodo.org/records/8276418 

![image](https://github.com/plazi/community/assets/4609956/c089378e-2b1c-4921-b864-7b24052d854e)

URL
http://treatment.plazi.org/id/03EB87F2FFEBFFBBFFF2FBF095C8FA88

**Comment by Carol-Sokolowicz** [comment]
I just changed the taxon name attributes. I'll check if it updated in Zenodo and other repositories.

**Comment by Carol-Sokolowicz** [comment]
Here are the updated links
https://treatment.plazi.org/id/03EB87F2FFEBFFBBFFF2FBF095C8FA88
https://zenodo.org/records/8276418

**Comment by Carol-Sokolowicz** [comment]
These are the updated links
https://treatment.plazi.org/id/03EB87F2FFEBFFBBFFF2FBF095C8FA88
https://zenodo.org/records/8276418

**Comment by mdoering** [comment]
@myrmoteras I was wondering how you deal with changes of treatments in Zenodo so I came across this issue as an example. I see the Zenodo subspecies is gone, but it is still the same first DOI version. 

The treatment html file hasnt changed, so I guess this is _only_ a metadata change that does not trigger a new version?
Are there cases when a new DOI version gets assigned, i.e. when a new treatment file is uploaded?

**Comment by myrmoteras** [comment]
@gsautter can you please reply? Tx

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by gsautter** [comment]
I see the problem ... the heading as a whole is in italics, and the taxon name doesn't have an authority to indicate where it ends, either ... seems to be a journal specific issue, specifically bound to these italicized second level headings.

Had the deposition replaced, the new one is here: https://zenodo.org/records/10680804 and the treatment now links to that. The DwCA is updated as well.
