### ISSUE TITLE
Occurrences seem to have been removed in some GBIF datasets - was it intentional?

### ISSUE THREAD

**Issue by ManonGros** [plazi/community#267]
Hi PLAZI,

My colleagues and I recently noticed that for at least two datasets, the occurrences seem to have disappeared.

For example, this dataset https://www.gbif.org/dataset/e542d309-1af6-465f-816b-3ef3e62a526e has occurrences indexed on GBIF but there aren't any in the archive: https://tb.plazi.org/GgServer/dwca/C56BA308C17E0264FF88FFD6FFC6C32D.zip
GBIF has a safeguard to prevent accidental deletion of occurrences so if all the occurrences disappear from a given dataset, they are still in the index. This is why the occurrences are still on GBIF. We can removed those from the index manually but I want to make sure this wasn't an accidental deletion.
The other dataset concerned is this one: https://www.gbif.org/dataset/91a51391-41b1-4184-bb62-6cd3bbbfdd74.

Both datasets contain material from specimens in institution that aren't well represented on GBIF, the occurrences are valuable.
Were they deleted on purpose? Let me know, thanks!

**Comment by flsimoes** [comment]
Hi @ManonGros I honestly don't know, it seems to be something on the GBIF side of the operation.

On our side it seems normal
See:
- Article link on TreatmentBank -> https://tb.plazi.org/GgServer/summary/C56BA308C17E0264FF88FFD6FFC6C32D
- GBIF links to materials -> https://tb.plazi.org/GgServer/srsStats/stats?outputFields=doc.articleUuid+tax.name+matCit.id+matCit.gbifOccurrenceId&groupingFields=doc.articleUuid+tax.name+matCit.id+matCit.gbifOccurrenceId&FP-doc.articleUuid=C56BA308C17E0264FF88FFD6FFC6C32D&format=HTML

I'll have a further look and get back to you

**Comment by Carol-Sokolowicz** [comment]
I did the quality check on GGI.
If the problem persist let us know

**Comment by ManonGros** [comment]
Thank you Carol! The data looks good for the first dataset! Would it be possible to do the same for this other one: https://www.gbif.org/dataset/91a51391-41b1-4184-bb62-6cd3bbbfdd74? Thanks!

**Comment by flsimoes** [comment]
> Thank you Carol! The data looks good for the first dataset! Would it be possible to do the same for this other one: https://www.gbif.org/dataset/91a51391-41b1-4184-bb62-6cd3bbbfdd74? Thanks!

Should be updated in the next couple of hours

**Comment by spalp** [comment]
Thank you both.
I found yet another dataset, which previously had occurrences, but now returns 0 occurrences: https://www.gbif.org/occurrence/search?dataset_key=50e48d61-aaca-4af9-9ef3-d2104aba3b8b

**Comment by Carol-Sokolowicz** [comment]
This has been updated, if there's something elso wrong let me know
https://www.gbif.org/occurrence/search?dataset_key=50e48d61-aaca-4af9-9ef3-d2104aba3b8b

**Comment by myrmoteras** [comment]
@ManonGros is there a way on GBIF side to check, whether there are more datasets that have been disappearing? Just to understand the issue on our end.

**Comment by muttcg** [comment]
@myrmoteras More than 2600+ Plazi checklist datasets were affected.
List of GBIF Registry dataset keys: [plazi.csv](https://github.com/plazi/community/files/14177235/plazi.csv)

**Comment by myrmoteras** [comment]
@muttcg thanks. This might have to do with a reaanalysis of the articles using more advanced tools, especially older articles/datasets.
We look into this asap

**Comment by gsautter** [comment]
@myrmoteras your assumption seems to be pretty much spot-on ... since we retro-applied quality control to our older IMFs, occurrences might well have been filtered from several DwCAs ... as we catch up on inspecting these IMFs, the occurrences should reappear, though, at least the correct ones.

**Comment by ManonGros** [comment]
Hi PLAZI,

This issue is coming back in the context of the work with the European Journal of Taxonomy.
It looks like some archives are occurrence-less for some of the EJT datasets. For example this one: https://www.gbif.org/dataset/4036285a-e386-454b-ac37-faa8db1687af (no occurrence in the archive).

The total number of occurrences for EJT (https://www.gbif.org/publisher/a064f300-1bc8-41ea-9364-b864ef4e8938) doesn't seem to correspond to the number of material citations that was shown in PLAZI dashboards.

I think the reason might be that some datasets don't have any occurrences in them. Would it be possible to investigate what is happening? Thanks!

**Comment by flsimoes** [comment]
> Hi PLAZI,
> 
> This issue is coming back in the context of the work with the European Journal of Taxonomy. It looks like some archives are occurrence-less for some of the EJT datasets. For example this one: https://www.gbif.org/dataset/4036285a-e386-454b-ac37-faa8db1687af (no occurrence in the archive).

Do you mean the DwCA does not include the occurrences? Because the GBIF link does have occurrences (sorry if I misunderstand).
![image](https://github.com/user-attachments/assets/36cab65e-6f59-4180-8c3f-57fbea37b1a1)

> 
> The total number of occurrences for EJT (https://www.gbif.org/publisher/a064f300-1bc8-41ea-9364-b864ef4e8938) doesn't seem to correspond to the number of material citations that was shown in PLAZI dashboards.
> 
> I think the reason might be that some datasets don't have any occurrences in them. Would it be possible to investigate what is happening? Thanks!

There are about 5400 occurences that are indeed not on GBIF yet, mostly from very recent uploads (will be there soon) and from older publications. And as @gsautter said, we retro-applied QC to older IMFs, so these occurrences might well have been filtered from several DwCAs .

**Comment by ManonGros** [comment]
Thanks for the reply @flsimoes 

I mean for example this dataset has occurrences in GBIF: https://www.gbif.org/dataset/4036285a-e386-454b-ac37-faa8db1687af but no occurrence in the archive: https://tb.plazi.org/GgServer/dwca/087BED432E7DEF62FFA6FFE8FFB57E29.zip

Should they be deleted from the GBIF index?

**Comment by flsimoes** [comment]
@gsautter what's your take here?

**Comment by gsautter** [comment]
Well, if we clean up some faulty materials citations and they consequentially disappear from the DwCA, I think they should be removed in GBIF as well ... we wouldn't take them out if they weren't faulty, would we? or is there other reasons?

**Comment by flsimoes** [comment]
> Well, if we clean up some faulty materials citations and they consequentially disappear from the DwCA, I think they should be removed in GBIF as well ... we wouldn't take them out if they weren't faulty, would we? or is there other reasons?

agreed, and no I don't think there's any other reasons

**Comment by ManonGros** [comment]
@flsimoes @gsautter, from what I can see, that would be deleting about half of the occurrences shared on GBIF by PLAZI. That seems like a lot. See this list of dataset concerned:
[PLAZI_dataset_where_occ_should_be_deleted.csv](https://github.com/user-attachments/files/17554593/PLAZI_dataset_where_occ_should_be_deleted.csv)

Please let me know if that makes sense and if I should go ahead and delete them.

**Comment by ManonGros** [comment]
I went ahead and deleted the occurrences. They will be recreated if they are added to the archives again.
