### ISSUE TITLE
Incorrect higher taxonomy for Geyeria uruguayana - https://doi.org/10.5281/zenodo.278914

### ISSUE THREAD

**Issue by ManonGros** [plazi/community#268]
Hi PLAZI,

We recently received a feedback message: https://github.com/gbif/backbone-feedback/issues/39 which points out that the higher taxonomy for this dataset https://www.gbif.org/dataset/c9bf75c7-70e5-4d32-b25d-77b45ed25187 is incorrect. The paper is about the Castniidae family (Lepidoptera).

But the higher taxonomy for Geyeria uruguayana (Burmeister, 1879) Burmeister, 1879 https://www.gbif.org/species/119418854 is one of the genus Geyeria A.J.Wagner, 1914 (https://www.gbif.org/species/3244579) a mollusc.
This means that the butterfly species shows in the mollusc taxon.

Would it be possible to update the dataset? Thanks!

**Comment by truschel** [comment]
Hi @ManonGros 

I fixed the higher taxonomy for this species. Please let me know any other questions I can help with.

Best regards,
Tatiana

**Comment by ManonGros** [comment]
Thanks Tatiana, it looks good!
