### ISSUE TITLE
Euxaldar daweishanensis erroneously in France

### ISSUE THREAD

**Issue by gargo-mnhn** [plazi/community#269]
Hi,
https://www.gbif.org/occurrence/search?taxon_key=11111924&country=FR
These occurrences in France are errors. Please correct !
Many thanks and best wishes
Olivier

**Comment by flsimoes** [comment]
TB UUID: [771FE3A67E005B12BCAE02CD0B8E31B7](https://tb.plazi.org/GgServer/summary/771FE3A67E005B12BCAE02CD0B8E31B7)

**Comment by flsimoes** [comment]
We've fixed on our side, now need to wait for GBIF to re-harvest the data
