### ISSUE TITLE
Incorrect interpreted species

### ISSUE THREAD

**Issue by KwAntynn** [plazi/community#270]
In Schifani & Alicata (2023), all the _Aphaenogaster dulcineae_ specimens compared with _Aphaenogaster mauritanica_ were encoded as this last species. _Aphaenogaster dulcineae_ is not synonymised with _A. mauritanica_.
See here: https://treatment.plazi.org/id/03DC87A4-157F-4177-3881-AC31FDFAFE1B

**Comment by flsimoes** [comment]
TB UUID: [FFE5FFDC157E41743816AA07F926FFEE](https://treatment.plazi.org/GgServer/summary/FFE5FFDC157E41743816AA07F926FFEE)

**Comment by diegojalvares** [comment]
Fixed
