### ISSUE TITLE
Harpochilus corrugatus Zappi & F.A.Silva erroneously in France

### ISSUE THREAD

**Issue by gargo-mnhn** [plazi/community#271]
Hi,
https://www.gbif.org/occurrence/search?taxon_key=11781815&country=FR
These records from France are erroneous - the taxon is only in Brazil
Best wishes,
Olivier

**Comment by flsimoes** [comment]
TB UUID: [FFAD4B70FFF8FFE3F6666A03FFC4FFD4](https://tb.plazi.org/GgServer/summary/FFAD4B70FFF8FFE3F6666A03FFC4FFD4)

**Comment by diegojalvares** [comment]
Hi Olivier
We've fixed on our side, now need to wait for GBIF to re-harvest the data
