### ISSUE TITLE
Alvania herrerae vs Alvania herosae

### ISSUE THREAD

**Issue by gargo-mnhn** [plazi/community#272]
Hi,
I think there is an error of name in https://www.gbif.org/dataset/6247b5e8-e434-4ff4-a408-d8ee87c09da7
The paper does not deal with Alvania herrerae
Its deals with the ressembling name Alvania herosae which is not in your dataset also it should
The material should be reviewed with that view 
Best wishes,
Olivier

**Comment by flsimoes** [comment]
We're currently checking it, thanks for reporting!

**Comment by flsimoes** [comment]
So, this seems to be a GBIF bug...

We've thoroughly checked what we could on our side and all records have _Alvania herosae_, but for some reason they show up as _herrerae_ on GBIF.

What's even weirder is there's no reference to _herrerae_ at all in the publication and nothing on GBIF's backbone.
So, we can't even pinpoint where the wrong name is coming from...

**Comment by debpaul** [comment]
> So, this seems to be a GBIF bug...
> 
> We've thoroughly checked what we could on our side and all records have _Alvania herosae_, but for some reason they show up as _herrarae_ on GBIF.
> 
> What's even weirder is there's no reference to _herrarae_ at all in the publication and nothing on GBIF's backbone. So, we can't even pinpoint where the wrong name is coming from...

@flsimoes I wonder where in the GBIF backbone this name is appearing? (I'm going to look now). I wonder if fuzzy matching at GBIF could be an issue? Here's what I see when I search "herrarare" on GBIF. See the "?" for that one name in front of the specificEpithet? Hm. GBIF has a note for this name see: https://www.gbif.org/species/11240390 which says that this string appears in 1 checklist dataset: https://doi.org/10.15468/39omei

![image](https://github.com/plazi/community/assets/2990155/ce2edb8b-e096-43a6-9621-7fca0217f23c)

and here's what I see for "herrerae"
![image](https://github.com/plazi/community/assets/2990155/7a8d7058-419f-44fc-a5d9-9817ac245bbd)

**Comment by flsimoes** [comment]
@debpaul I misspeled the epithet, herrerae

**Comment by flsimoes** [comment]
There's this, but still... https://www.gbif.org/species/5192260
I don't understand how _that_ could be causing the problem

**Comment by flsimoes** [comment]
Closing this as it is a GBIF issue
