### ISSUE TITLE
Occurrence issues reported by GBIF user

### ISSUE THREAD

**Issue by ManonGros** [plazi/community#274]
Hi PLAZI,

I think my colleague John might already have contacted you by email about this but since the discussion is continuing on GitHub I thought I would like to the original issue here.
See this thread: https://github.com/gbif/portal-feedback/issues/5278

**Comment by guilhermepcoelho** [comment]
Hi @ManonGros,

I fixed this issue, the occurrences from this paper should be correct now.

Best regards.
