### ISSUE TITLE
Electroprojapyx, 2023 sp.nov. wrong

### ISSUE THREAD

**Issue by mdoering** [plazi/community#275]
https://treatment.plazi.org/id/039887CD4B1C6520FC98FEBCE29FF983

looks to be a new species, but is presented as a genus and with full capital letters for the species epithet in dwca:
[Electroprojapyx ALCHEMICUS 2023](https://www.dev.checklistbank.org/dataset/59207/verbatim/23)

**Comment by Carol-Sokolowicz** [comment]
I've fixed this and the other treatments from the same paper.
Please let me know if the problem is still on.
Cheers

**Comment by mdoering** [comment]
Thanks, all good now! 
https://www.checklistbank.org/dataset/59207/taxon/039887CD4B1C6520FC98FEBCE29FF983.taxon
