### ISSUE TITLE
Higher taxonomy of host and mite was mixed up - https://treatment.plazi.org/id/3251473DDE48FFFAFF6FFD5EFD2B00B8

### ISSUE THREAD

**Issue by ManonGros** [plazi/community#276]
Hi PLAZI,

One of our users initially reported an issue: https://github.com/gbif/backbone-feedback/issues/13 which is relating to this GBIF dataset: https://www.gbif.org/dataset/b7631fff-5be6-4105-a016-02f9de149381 (the publication is this one: https://doi.org/10.11646/zootaxa.4388.3.4).

The publication is about mites but the higher taxonomy for some of the taxon provided in the checklist are plants. It seems like the taxonomy of the host was mixed up with the one from the mite.

Plus some species don't seem to exist. For example Ziziphus furciger (Berlese) Berlese (https://www.gbif.org/species/141267347) isn't actually in the original publication, what I could find was _Zygoseius  furciger_  (Pachylaelapidae)

Would it be possible to investigate? Thanks!

**Comment by flsimoes** [comment]
Hi @ManonGros 
Thanks for reporting this back

What mainly happened here is that several taxonomic names were incompletely tagged, resulting in these errors.
For instance, the tagger only got the `furciger (Berlese)` part of `Zygoseius furciger (Berlese)`, and for some reason it referred back to a plant with the same specific name.
Bear in mind that this was made with an older version of the tagger.
I re-ran the marking of taxonomicNames through the publication and they should be fixed now.

I've also re-worked good chunks of the extraction, so you should be seeing even more improvements soon.
