### ISSUE TITLE
wrong country: Should be Brazil, but listed as CHAD

### ISSUE THREAD

**Issue by myrmoteras** [plazi/community#277]
Please leave your comment here...

This material citations has CHAD as country, whilst it should be Brazil

**Context**
[GBIF occurrence](https://www.gbif.org/occurrence/2013095063)
[Plazi reference](http://treatment.plazi.org/id/03AB87B1FFDFC12384F6FA8F79896751)

**Comment by diegojalvares** [comment]
Fixed, should be updated on GBIF soon
