### ISSUE TITLE
listed as CHAD, but coordinates are in South America

### ISSUE THREAD

**Issue by myrmoteras** [plazi/community#278]
listed as CHAD, but coordinates are in South America

**Context**
[GBIF occurrence](https://www.gbif.org/occurrence/3306132315)
[Plazi reference](https://treatment.plazi.org/id/305C878DEB2FFFF7FC2EF9C3FDD5A29F

**Comment by diegojalvares** [comment]
Fixed, should be updated on GBIF soon
