### ISSUE TITLE
this publication has country Chad erroneously listed

### ISSUE THREAD

**Issue by myrmoteras** [plazi/community#279]
Please leave your comment here...

this publication has country Chad erroneously listed
https://www.gbif.org/dataset/5b4badde-70a0-4197-af5e-4a7b691635f7 
**Context**
[GBIF occurrence](https://www.gbif.org/occurrence/2013095127)
[Plazi reference](http://treatment.plazi.org/id/03AB87B1FFDFC12384F6FA8F79896751)

**Comment by diegojalvares** [comment]
Fixed, should be updated on GBIF soon
