### ISSUE TITLE
conflicting DOI on Zenodo and TB

### ISSUE THREAD

**Issue by Carol-Sokolowicz** [plazi/community#28]
HI Donat,
**I was checking the new zootaxa to upload. I went to check this article:**

![image](https://user-images.githubusercontent.com/57491712/79265835-19f14a00-7e6d-11ea-8b70-20165bf2c4d7.png)

**The Zenodo search returned this DOI with another article:**

![image](https://user-images.githubusercontent.com/57491712/79265961-44430780-7e6d-11ea-8fb1-1bc2795bddb4.png)
https://zenodo.org/record/3607091

http://publication.plazi.org/id/FFD82A1CC378FFDFFD068D4FAD10FFD8

**Then I searched for the original article by the title and it has a different DOI as it is in the PDF file**

![image](https://user-images.githubusercontent.com/57491712/79266226-9dab3680-7e6d-11ea-8577-71b92b601515.png)
https://zenodo.org/record/3608018

**So, just to report the issue.**

**Comment by myrmoteras** [comment]
Hi @Carol-Sokolowicz 
if I am remembering right, I found this when I processed these files, checked at the mapress home page and came to the conclusion that this needs to be changed, even though the doi in the article is not the one actuually used for it.
in the last couple of yeasr, this has happened very rarely though

Nevertheless, thanks for pointing this out.
