### ISSUE TITLE
Geolocation improvement : Revision of the genus Prometopidia Hampson, 1902...

### ISSUE THREAD

**Issue by vijaybarve** [plazi/community#280]
I am in touch with Authors of https://www.gbif.org/dataset/778b8e9e-9010-4388-b049-5560cb26b544 for improvement in the geolocation of the records published. Once I receive the details, what would be the way forward to make sure the dataset is republished?

**Comment by flsimoes** [comment]
So, the authors do provide geolocations in the publication (at least to a part of the materials cited). Unfortunately the geo information was kept separate from the actual materials examined section.

We can add the geolocations to their respective materials, is that what you need?

**Comment by flsimoes** [comment]
@vijaybarve any updates here?

**Comment by flsimoes** [comment]
I'll close this issue as it is stale
