### ISSUE TITLE
GBIF Feedback - Incorrect scientific name authorship - https://doi.org/10.1080/00222933.2019.1704456

### ISSUE THREAD

**Issue by ManonGros** [plazi/community#281]
Hi PLAZI,

One of our users logged the following feedback message: https://github.com/gbif/backbone-feedback/issues/3.

The name `Niphargus keeleri Zamanpoore & Bakhshi, 2020` (https://www.gbif.org/species/11212622) which comes from this dataset: https://www.gbif.org/dataset/dcb6e6f0-da73-4034-be66-85bad65ee092 (and this publication:https://doi.org/10.1080/00222933.2019.1704456) should actually be `Niphargus keeleri Zamanpoore & Bakhshi, 2020`.
Thanks!

**Comment by guilhermepcoelho** [comment]
Hi, @ManonGros 

I've made the requested correction on the authority of this name. Soon it should be correct in GBIF.

Best regards.
