### ISSUE TITLE
"Catalogue of Geadephaga (Coleoptera, Adephaga) of America, north of Mexico" seems to contain plants

### ISSUE THREAD

**Issue by rossmounce** [plazi/community#282]
For this treatment article: "Catalogue of Geadephaga (Coleoptera, Adephaga) of America, north of Mexico" up on GBIF https://www.gbif.org/dataset/ca515b82-e301-43ff-9f69-2c0116e1c95b

It appears to contain two taxa that are mistakenly tagged as plants rather than beetles.

1.) https://www.gbif.org/species/182238098/verbatim
2.) https://www.gbif.org/species/182238100/verbatim

**Comment by guilhermepcoelho** [comment]
Hi, @rossmounce 

I've made the corrections on the higher taxonomy of these two taxa. Soon they should be correct in GBIF.

Best regards.
