### ISSUE TITLE
Within an Acari checklist there is a genus mistakenly tagged as a reptile

### ISSUE THREAD

**Issue by rossmounce** [plazi/community#283]
GBIF dataset here: https://www.gbif.org/dataset/b36bb855-16c8-4c79-94cd-056c16147d58

Specific mis-tagged genus: Diaguitacarus Stekolnikov & Gonzalez-Acuna, 2015 
https://www.gbif.org/species/183319578/verbatim

**Comment by guilhermepcoelho** [comment]
Hi @rossmounce

I've made the correction in the attributes of this name. Soon it should appear correctly in GBIF.

Best regards.

**Comment by rossmounce** [comment]
thanks
