### ISSUE TITLE
"Checklist of marine and estuarine fishes from the Alaska-Yukon Border, Beaufort Sea, to Cabo San Lucas, Mexico" higher taxonomy errors

### ISSUE THREAD

**Issue by rossmounce** [plazi/community#284]
This dataset has higher-taxonomy errors.

"Checklist of marine and estuarine fishes from the Alaska-Yukon Border, Beaufort Sea, to Cabo San Lucas, Mexico" https://www.gbif.org/dataset/75ffcff3-6336-4f6a-8d0b-94c082519099 

It ought to be all fish in this checklist but there are 

fish as "fungi" e.g. https://www.gbif.org/species/191881610/verbatim 
fish as "bryophytes" e.g. https://www.gbif.org/species/191881625/verbatim
fish as "ferns" e.g. https://www.gbif.org/species/191881638/verbatim

fish as "plants" e.g. https://www.gbif.org/species/191881740/verbatim
https://www.gbif.org/species/191881742/verbatim
https://www.gbif.org/species/191881738/verbatim
https://www.gbif.org/species/191881736/verbatim
https://www.gbif.org/species/191881734/verbatim

fish as "palms" e.g. https://www.gbif.org/species/191881656/verbatim

etc...

**Comment by guilhermepcoelho** [comment]
Hi, @rossmounce ,

I've corrected the higher-taxonomy issues in this dataset, soon the information should be correct in GBIF.

Best regards.
