### ISSUE TITLE
"new mite species described during 2007 to 2012 3663" higher taxonomy errors

### ISSUE THREAD

**Issue by rossmounce** [plazi/community#285]
Dataset on GBIF here: "new mite species described during 2007 to 2012 3663" https://www.gbif.org/dataset/e7d0117a-c188-4d9a-822f-9f7ae01b12fd

Should be all mites but...

there's a "fungi": https://www.gbif.org/species/193846250/verbatim
and "algae": https://www.gbif.org/species/193846278/verbatim 
and a "grass": https://www.gbif.org/species/193846266/verbatim
and an "orthopteran": https://www.gbif.org/species/193846243/verbatim

**Comment by guilhermepcoelho** [comment]
Hi, @rossmounce,

I've corrected the taxonomic information for these names, soon they should be correct in GBIF. 

Best regards.
