### ISSUE TITLE
higher taxonomy errors in https://www.gbif.org/dataset/8bb17a01-6ca6-4225-a42c-be3cb22e3db0

### ISSUE THREAD

**Issue by rossmounce** [plazi/community#286]
"Checklist of the marine and estuarine fishes of New Ireland Province, Papua New Guinea, western Pacific Ocean, with 810 new records"
https://www.gbif.org/dataset/8bb17a01-6ca6-4225-a42c-be3cb22e3db0

ought to be just fish but...

there's insects: 
a) https://www.gbif.org/species/157229929/verbatim
b) https://www.gbif.org/species/157229926/verbatim
c) many (16) in the genus _Acanthurus_ tagged as insects rather than fish https://www.gbif.org/species/232382955

**Comment by guilhermepcoelho** [comment]
Hi, @rossmounce

I've made the corrections in these names. Soon they should be correct in GBIF.
