### ISSUE TITLE
weevils of Ukraine should not contain millipedes

### ISSUE THREAD

**Issue by rossmounce** [plazi/community#287]
"A survey of the weevils of Ukraine (Coleoptera: Curculionoidea)" 
https://www.gbif.org/dataset/1416a8a0-adc9-486b-b88d-52328522c85b

5 different taxa in Leiosoma are all wrongly marked as millipedes
 https://www.gbif.org/species/232353547

**Comment by guilhermepcoelho** [comment]
Hi, @rossmounce 

I've corrected the attributes for all Leiosoma species. Soon it should appear correctly in GBIF.

Best regards.
