### ISSUE TITLE
higher taxonomy errors in https://www.gbif.org/dataset/bd9063be-ff50-4ccd-ad69-3819e3fc7d97

### ISSUE THREAD

**Issue by rossmounce** [plazi/community#288]
"A nomenclator of extant and fossil taxa of the Melanopsidae (Gastropoda, Cerithioidea)"
https://www.gbif.org/dataset/bd9063be-ff50-4ccd-ad69-3819e3fc7d97

should be all gastropods but...

a) Homalia wrongly tagged as a bryophyte: https://www.gbif.org/species/127893327
b) Martinia Handmann, 1887 has some issues as it's wrongly in brachiopoda: https://www.gbif.org/species/127894457
c) Hyphantria Handmann, 1887 wrongly as an insect: https://www.gbif.org/species/127893319/verbatim

**Comment by guilhermepcoelho** [comment]
Hi, @rossmounce 

I've correct the higher taxonomy attributes of these names, soon they should appear correctly in GBIF.

Best regards.
