### ISSUE TITLE
Muridae contains a plant? [higher taxonomy error]

### ISSUE THREAD

**Issue by rossmounce** [plazi/community#289]
GBIF dataset: https://www.gbif.org/dataset/a016af63-6437-427b-80b7-22bc9a002e20

 dataset contains the digitized treatments in Plazi based on the original book chapter Don E. Wilson, Russell A. Mittermeier, Thomas E. Lacher, Jr (2017): Muridae. In: Handbook of the Mammals of the World – Volume 7 Rodents II.

should be all rodents but 

but... _Phloecomys cumingi_ as a plant species here: https://www.gbif.org/species/197825300/verbatim

**Comment by guilhermepcoelho** [comment]
Hi @rossmounce 

I have corrected the attributes for Phloecomys cumingi. Soon it should be correct in GBIF.

Best regards.
