### ISSUE TITLE
Treatment "Angiopteris nodosipetiolata Ting Wang tris, H. F. Chen & Y. H. Yan A, B 2024, sp. nov."

### ISSUE THREAD

**Issue by gsautter** [plazi/community#290]
First ticket via feedback button, just to see how generated body comes out.

**Context**
Treatment: Angiopteris nodosipetiolata Ting Wang tris, H. F. Chen & Y. H. Yan A, B 2024, sp. nov. - C615EC3AB7795E4D8ED5FC47F4AC8103 - [go to page](https://treatment.plazi.org/id/C615EC3AB7795E4D8ED5FC47F4AC8103)
Document: PhytoKeys 241: 177-189 - E415E7845E01563D918108C6915DC04D - [go to summary](https://publication.plazi.org/id/E415E7845E01563D918108C6915DC04D)

**Comment by flsimoes** [comment]
@gsautter can we close this one?

**Comment by gsautter** [comment]
Sure, go ahead ... as my entry says, it was merely a test for the newly added feedback button in the TreatmentBank website (see https://github.com/plazi/treatmentBank/issues/117) ... simply had to know whether or not it works, and what the links in the generated message footer would come out as before asking for any feedback regarding the newly added function ... which never came anyway.

**Comment by flsimoes** [comment]
> Sure, go ahead ... as my entry says, it was merely a test for the newly added feedback button in the TreatmentBank website (see [plazi/treatmentBank#117](https://github.com/plazi/treatmentBank/issues/117)) ... simply had to know whether or not it works, and what the links in the generated message footer would come out as before asking for any feedback regarding the newly added function ... which never came anyway.

I see
Well, we didn't understand this ticket was supposed to be used for feedback

That being said, I would recommend making the Feedback button stand out more. At the moment it is "lost" in the middle of the other buttons. Perhaps adding a different background color?

**Comment by gsautter** [comment]
> > Sure, go ahead ... as my entry says, it was merely a test for the newly added feedback button in the TreatmentBank website (see [plazi/treatmentBank#117](https://github.com/plazi/treatmentBank/issues/117)) ... simply had to know whether or not it works, and what the links in the generated message footer would come out as before asking for any feedback regarding the newly added function ... which never came anyway.
> 
> I see Well, we didn't understand this ticket was supposed to be used for feedback
> 
> That being said, I would recommend making the Feedback button stand out more. At the moment it is "lost" in the middle of the other buttons. Perhaps adding a different background color?

https://github.com/plazi/treatmentBank/issues/117 was asking for feedback ... this one originates from me testing the button ;-)

**Comment by myrmoteras** [comment]
I would suggest to move the feedback button to where it belongs, the actual treatment
![image](https://github.com/plazi/community/assets/4609956/37b97b8b-8829-49f7-8dae-256b286330e0)

integrated above means feedback to the TreatmentBank in general, not the specific treatment.

there is another issue to have the feedback button in the status line, cuased how wide the window is

missing at all in the block, but appearing somewhere else:
![image](https://github.com/plazi/community/assets/4609956/2f2f26fb-1eff-4957-b103-b660f8ffc987)

or overwriting
![image](https://github.com/plazi/community/assets/4609956/144103c2-6921-4597-86c2-14b48dcfb3e4)

**Comment by gsautter** [comment]
Done ...

**Comment by myrmoteras** [comment]
@gsautter thanks - very good
