### ISSUE TITLE
Treatment "Milnesium tardigradum Kaczmarek 2017, sensu lato"

### ISSUE THREAD

**Issue by KatjaSchulz** [plazi/community#291]
The following taxa have incorrect taxonomy data in TreatmentBank:
* [Milnesium tardigradum](https://treatment.plazi.org/id/03ED740D32047E50FF6BFA556FC4FDC6): Animalia|Annelida|Polychaeta|Phyllodocida|Aphroditidae - This is actually a tardigrade: Animalia|Tardigrada.
* [Megalomma inflata](https://treatment.plazi.org/id/2202BF4FFFDC5B6EFED850A4FD67F905):	Animalia|Arthropoda|Insecta|Coleoptera|Carabidae - This is actually a polychaete Animalia|Annelida
* [Astylus tucumanensis](https://treatment.plazi.org/id/03976845FFF7A1341A96FE70FCC288E9): Animalia|Cnidaria|Hydrozoa|Anthoathecata|Stylasteridae - This is actually a beetle: Animalia|Insecta|Coleoptera|Melyridae
* [Martinezia excavaticollis](https://treatment.plazi.org/id/223B87B493710463C4F6CED4EE73F841): Animalia|Amoebozoa|Lobosa|Amoebida|Entamoebidae - This is actually a beetle: Animalia|Insecta|Coleoptera|Scarabaeidae
* [Iconella meruloides](https://treatment.plazi.org/id/76261A0AD054FFDDFF2E107BFCB5FA5D): Chromista|Ochrophyta|Bacillariophyceae - This is actually a wasp: Animalia|Arthropoda|Insecta|Hymenoptera|Braconidae

While the previous examples all represent plausible taxonomic hierarchies that are just wrong for the focal taxon of the treatment, there are many treatments (I found over 1,000) with mixed-up hierarchies that cross over between kingdoms or other major groups.
Examples:
* [Odontonia bagginsi](https://treatment.plazi.org/id/A43D94B4A69735112E9348ADDA2201A1): Animalia|Tracheophyta|Liliopsida|Decapoda|Palaemonidae - This is indeed a palaemonid decapod, but Tracheophyta|Liliopsida are plants.
* [Cycloporus variegatus](https://treatment.plazi.org/id/039187B7D2693B4DFF35FD256339FF52), [Cycloporus reticulatus](https://treatment.plazi.org/id/039187B7D2603B41FF35FF7262A2FCDA): Fungi|Platyhelminthes||Polycladida|Stylostomidae - Platyhelminthes are not fungi.
* [Bothrocophias tulitoi](https://treatment.plazi.org/id/0A01137CF53F5AC49FF0B34BF82BA879):	Animalia|Chordata|Aves|Squamata|Viperidae - a snake, Squamata is not a child of Aves (birds) in any classification
* [Malanea evenosa](https://treatment.plazi.org/id/510DF73D4F6156A8A66041F1AE766367): Animalia|Tracheophyta|Magnoliopsida|Gentianales|Rubiaceae - hierarchy is correct, except for the kingdom
* [Biasticus griseocapillus](http://treatment.plazi.org/id/EFED6E08BFEC5FD18C238DAFB14CF4EA): Animalia|Annelida|Clitellata|Hemiptera|Reduviidae - Hemiptera are not in Annelida in any hierarchy

I will attach a file that has all the mixed up hierarchies I found. This list is not exhaustive. There are probably more.

**Context**
Treatment: Milnesium tardigradum Kaczmarek 2017, sensu lato - 03ED740D32047E50FF6BFA556FC4FDC6 - [go to page](https://treatment.plazi.org/id/03ED740D32047E50FF6BFA556FC4FDC6)
Document: zootaxa.4284.1.1.pdf.imf - FFD40C7532177E45FFFCFFEB6D1DFF96 - [go to summary](https://publication.plazi.org/id/FFD40C7532177E45FFFCFFEB6D1DFF96)

**Comment by KatjaSchulz** [comment]
[invalidTaxonomy.txt](https://github.com/user-attachments/files/15874539/invalidTaxonomy.txt)

**Comment by flsimoes** [comment]
@KatjaSchulz Thank you very much for pointing them out, we'll start working on the fixes right away.
Also thanks for the list! It is very helpful.

**Comment by myrmoteras** [comment]
@flsimoes can you try to find out, whether there is a systemic errror a possible cause of the errors?

**Comment by flsimoes** [comment]
> @flsimoes can you try to find out, whether there is a systemic errror a possible cause of the errors?

Yes, I'll do a deep-dive to figure it out

**Comment by flsimoes** [comment]
Fixed
[Milnesium tardigradum](https://treatment.plazi.org/id/03ED740D32047E50FF6BFA556FC4FDC6)
[Megalomma inflata](https://treatment.plazi.org/id/2202BF4FFFDC5B6EFED850A4FD67F905)
[Astylus tucumanensis](https://treatment.plazi.org/id/03976845FFF7A1341A96FE70FCC288E9)
[Martinezia excavaticollis](https://treatment.plazi.org/id/223B87B493710463C4F6CED4EE73F841)
[Iconella meruloides](https://treatment.plazi.org/id/76261A0AD054FFDDFF2E107BFCB5FA5D)
[Cycloporus variegatus](https://treatment.plazi.org/id/039187B7D2693B4DFF35FD256339FF52)
[Odontonia bagginsi](https://treatment.plazi.org/id/A43D94B4A69735112E9348ADDA2201A1)
[Bothrocophias tulitoi](https://treatment.plazi.org/id/0A01137CF53F5AC49FF0B34BF82BA879)
[Malanea evenosa](https://treatment.plazi.org/id/510DF73D4F6156A8A66041F1AE766367)
[Biasticus griseocapillus](http://treatment.plazi.org/id/EFED6E08BFEC5FD18C238DAFB14CF4EA)

**Comment by flsimoes** [comment]
@KatjaSchulz 

We're fixing the hierarchies you reported, but we stumbled upon this one where we can't figure out what would be wrong:

https://treatment.plazi.org/id/039087B3927C433CFE9DF4A0FD06FAA4 | Achaetobonellia ricei Biseswar 2005
The current hierarchy seems correct: Animalia|Annelida|Polychaeta|Echiuroidea|Bonelliidae

Can you confirm it, please?

**Comment by KatjaSchulz** [comment]
Yes, that looks correct. Not sure why it ended up in the list. Thanks!

**Comment by flsimoes** [comment]
@KatjaSchulz Last week we finished fixing the reported errors.
Thank you very much for letting us know!

Regarding the reasons for such errors, they had different causes. Some were originated from homonyms, especially when Coleoptera was involved, while others were a product of parsing the taxonomic names in the early days, the tools for which are much better nowadays.

**Comment by KatjaSchulz** [comment]
Thanks for taking care of this promptly!
