### ISSUE TITLE
the bank vole (a mammal) is NOT a plant

### ISSUE THREAD

**Issue by rossmounce** [plazi/community#292]
Over at GBIF I see the bank vole listed as a plant here: https://www.gbif.org/species/196220845/verbatim 

[from this Plazi dataset: Cricetidae. In: Handbook of the Mammals of the World – Volume 7 Rodents II. Barcelona: Lynx Edicions: 204-535, ISBN: 978-84-16728-04-6, DOI: 10.5281/zenodo.6707142 Mediated through: [Plazi.org taxonomic treatments database](http://www.plazi.org/) ]  https://www.gbif.org/dataset/ab66b2b7-9544-4411-bf61-5bc3651d7bca

**Comment by Carol-Sokolowicz** [comment]
This is fixed, 
thanks for pointing out
