### ISSUE TITLE
a coleoptera checklist contains plants & fungi (higher classification error)

### ISSUE THREAD

**Issue by rossmounce** [plazi/community#294]
This Plazi-mediated dataset on GBIF: https://www.gbif.org/dataset/607932e4-c3eb-42a7-ae75-a68dbcd4064a
"An annotated catalogue of the Coleoptera types deposited in the National Insect Collection (CNIN) of the National Autonomous University of Mexico"

ought to be just beetles but...

* one taxon is mistakenly tagged as kingdom Plantae: https://www.gbif.org/species/135435811/verbatim
* two taxa are mistakenly tagged in kingdom Fungi:
a) https://www.gbif.org/species/135435792/verbatim
b) https://www.gbif.org/species/135435793/verbatim

**Comment by Carol-Sokolowicz** [comment]
Fixed!
Thanks
