### ISSUE TITLE
inconsistent kingdom tag: Metazoa / Animalia used interchangeably(?) within same dataset

### ISSUE THREAD

**Issue by rossmounce** [plazi/community#295]
This is perhaps a slightly different type of milder error to those I've previously reported...

This Plazi-mediated dataset on GBIF: https://www.gbif.org/dataset/1e2bcc49-86c8-4612-a4eb-d9bdce9785ef
"Catalogue of the hymenopterous insects in the collection of the British Museum. Part VI. Formicidae."

Most of the taxa are tagged as Kingdom: Animalia

_but_

it seems that one or more taxa in this dataset are tagged as Kingdom: Metazoa instead.

It's just inconsistent tagging really.

e.g. this one is tagged in Metazoa: https://www.gbif.org/species/233194684 

I appreciate this is lower priority issue.

**Comment by rossmounce** [comment]
Another dataset also has the same kind of inconsistency between Metazoa / Animalia within the dataset.

"Annotated type catalogue of the Bulimulidae (Mollusca, Gastropoda, Orthalicoidea) in the Natural History Museum, London"
https://www.gbif.org/dataset/2cf23a39-7883-487a-be90-21ced4011e5c

error taxon: Bulimulidae (as Metazoa) https://www.gbif.org/species/233025490 

most other taxa are all listed in Animalia

**Comment by Carol-Sokolowicz** [comment]
This would take a lot of time fixing each one individually.
We'll discuss what would be the best strategy.
Thanks,

**Comment by flsimoes** [comment]
I've asked Guido for his input. Perhaps it is something to be fixed in the next Big Batch

**Comment by kbamaral** [comment]
Solved!
