### ISSUE TITLE
weevil beetles checklist dataset contains Chordata & Platyhleminthes

### ISSUE THREAD

**Issue by rossmounce** [plazi/community#296]
dataset at GBIF: https://www.gbif.org/dataset/0d33570c-4ae9-4408-9c78-045c551b58e5
"A contribution to the fauna of weevil beetles (Coleoptera: Curculionoidea) of the Central Donbass"

error taxa: 
* Aspis albolineata (Fabricius, 1792) https://www.gbif.org/species/212416214/verbatim
* Nanophyes marmoratus subsp. marmoratus (Goeze, 1777) https://www.gbif.org/species/212416220/verbatim

**Comment by Carol-Sokolowicz** [comment]
Fixed!
Thanks,
