### ISSUE TITLE
extant asteroids (Echinodermata) has many higher taxonomy errors

### ISSUE THREAD

**Issue by rossmounce** [plazi/community#297]
GBIF dataset here: https://www.gbif.org/dataset/83dc5b45-5596-4a84-ab44-8b2f4d777110
"The type specimens of extant asteroids (Echinodermata) in the Muséum national d’Histoire naturelle of Paris"

ought to be just echinodermata but...

error taxa include:
* 5 different taxa of Culcita as plants
   * https://www.gbif.org/species/195867157
   * https://www.gbif.org/species/195867154
   * https://www.gbif.org/species/195867156
   * https://www.gbif.org/species/195867152
   * https://www.gbif.org/species/195867246

* 2 taxa tagged as Radiozoa

   * https://www.gbif.org/species/195867006
   *  https://www.gbif.org/species/195867004

* many taxa tagged as Coccolithophyceae
  * https://www.gbif.org/species/195867382
  * https://www.gbif.org/species/195866987
  * https://www.gbif.org/species/195867383
  * https://www.gbif.org/species/195867263

* taxa tagged as fungi
   * https://www.gbif.org/species/195867647/verbatim

...lots of errors in this dataset and I may not have listed them all here.

**Comment by Carol-Sokolowicz** [comment]
I performed an extesive review in all names of the paper.
If you see somenthing else odd let me now.
