### ISSUE TITLE
How to proceed with "Correspondences" in Zootaxa

### ISSUE THREAD

**Issue by Carol-Sokolowicz** [plazi/community#30]
Hi Donat,
Zootaxa has a lot of Correspondance issues that have no headings, although they are about taxonomic treatments, this is an exemple:

![image](https://user-images.githubusercontent.com/57491712/79605764-e14cad00-80c6-11ea-8a91-2309f6a7a4eb.png)
https://drive.google.com/open?id=1gFv33U8KYvNOQx364kbfgsjA3gZhlAvq

Should I make part of the title which has the taxon as a treatment heading so the rest of the text can be extracted as a treatment or not?

I have similar doubt about the erratum on a previous issue https://github.com/plazi/community/issues/17

I'm not processing both correspondence an erratum yet because of this doubt,

Cheers

**Comment by mguidoti** [comment]
@myrmoteras we need your input here
