### ISSUE TITLE
In: "generic keys of the Leiodidae (Insecta: Coleoptera)" contains plants & fungi

### ISSUE THREAD

**Issue by rossmounce** [plazi/community#302]
GBIF dataset URL: https://www.gbif.org/dataset/a9286570-20d6-4a5b-af31-d4717ed26de9
"Updated catalog and generic keys of the Leiodidae (Insecta: Coleoptera) of the Neotropical region (“ Latin America ”: Mexico, the West Indies, and Central and South America)"

expected taxa - all beetles

error taxa:
* Tricholoma kaszabi Hlisnikovsky, 1964 https://www.gbif.org/species/177202160/verbatim (as fungi)
* Anisotoma with 14 child taxa beneath it all tagged as plants https://www.gbif.org/species/232922999 

also some 'orphan' tribes and subtribes that have no higher taxonomy data e.g.

* Neopelatopini https://www.gbif.org/species/163830390/verbatim
* Ptomaphaginina Szymczakowski https://www.gbif.org/species/163830395/verbatim

**Comment by kbamaral** [comment]
Solved!
