### ISSUE TITLE
Incorrect higher taxonomy for Stevekenia - https://doi.org/10.11646/zootaxa.4286.3.4

### ISSUE THREAD

**Issue by ManonGros** [plazi/community#303]
Hi PLAZI,

We got some feedback https://github.com/gbif/backbone-feedback/issues/25 concerning this dataset: https://www.gbif.org/dataset/706253b2-beb2-4712-8b44-9dd7e400e20c.

Stevekenia (https://www.gbif.org/species/132548941) is an Hemiptera, its higher taxonomy is mixed up with its host plant (a Solanaceae).

Would it be possible to correct it? Thanks!

**Comment by Carol-Sokolowicz** [comment]
This is fixed,
Thanks
