### ISSUE TITLE
Treatment "Enoplometopus debelius Holthuis 1983"

### ISSUE THREAD

**Issue by KatjaSchulz** [plazi/community#305]
This treatment actually contains two individual treatments for separate species: Enoplometopus debelius & Enoplometopus occidentalis. Please separate.

**Context**
Treatment: Enoplometopus debelius Holthuis 1983 - 0396AD3EFFE9DC65FD37FD3AFE625EAF - [go to page](https://treatment.plazi.org/id/0396AD3EFFE9DC65FD37FD3AFE625EAF)
Document: Zoosystema.25.4.643-664.pdf - FFAFD546FFE7DC75FFCAFF84FFAE5C4A - [go to summary](https://publication.plazi.org/id/FFAFD546FFE7DC75FFCAFF84FFAE5C4A)

**Comment by flsimoes** [comment]
Thank you very much for reporting this.
Fixed it and it should be showing up soon!
