### ISSUE TITLE
GBIF Feedback - 10.11646/zootaxa.4646.3.2 - authorship seems incorrect

### ISSUE THREAD

**Issue by ManonGros** [plazi/community#306]
Hi PLAZI,

The authorship for that species https://www.gbif.org/species/159628367 from this dataset https://www.gbif.org/dataset/b5150fe8-e62c-4754-8daa-641db7533221 seems to be incorrect. It should be _Turkozelotes attavirus_ Chatzaki, 2019. Would it be possible to update it? Thanks!

Related issue: https://github.com/gbif/backbone-feedback/issues/22

**Comment by truschel** [comment]
Hi Marie!
I just fixed it. If you have any other questions regarding this please let me know.

**Comment by ManonGros** [comment]
Thank you @truschel much appreciated!
