### ISSUE TITLE
Incorrect citation

### ISSUE THREAD

**Issue by diegoastua** [plazi/community#307]
Hi. 
I recently found out this teatment
https://treatment.plazi.org/GgServer/summary/0B1ACF14FFFBFFD0FFAB161FFFFD8C61
but authorship is incorrect (and I suspect will be for most chapters of this handbook). Wilson & Mittermeier were editors of the volumes but chapters were authored by different people, as seen here for HMW5
https://www.lynxeds.com/product/handbook-of-the-mammals-of-the-world-volume-5/#tab-additional_information

In this case, the correct citation would be 
Astúa, D. (2015) Family Didelphidae (Opossums). In Handbook of the Mammals of the World - Volume 5 – Monotremes and Marsupials (eds Wilson DE, Mittermeier RA), pp. 70-186. Barcelona: Lynx Edicions / Conservation International / IUCN.
 
or any specific format you are using. I am glad to redirect those needing a copy of that chapter to Plazi but I have to warn them of the correct citation each time.
Thanks and congratulations on the great work
Diego

**Comment by truschel** [comment]
Hi Diego
Thanks for the message. I fixed the author name.
Please, feel free to send any other questions if you have.

**Comment by diegoastua** [comment]
Thank you!
