### ISSUE TITLE
Title and figures question for Bentyra ryukyuana, Watanabe, 2021

### ISSUE THREAD

**Issue by myrmoteras** [plazi/community#308]
In this article, the title seems no to be a taxonomic work " Cultivating Englishness: national identity in Middle English romance,"  https://tb.plazi.org/GgServer/summary/FFC0FFEB1B45A714FFCA6633FFD77447

and the figs are not linked

https://treatment.plazi.org/id/03F98793-1B53-A703-FC16-6595FBAD7088

**Comment by juwingert** [comment]
Hi Donat, I will see that.

**Comment by juwingert** [comment]
The paper is work fine now:
[FFC0FFEB1B45A714FFCA6633FFD77447](https://tb.plazi.org/GgServer/summary/FFC0FFEB1B45A714FFCA6633FFD77447)
[12774639](http://zenodo.org/record/12774639)
[70224806-ca38-47ca-bd8a-63da3ac532f9](http://www.gbif.org/dataset/70224806-ca38-47ca-bd8a-63da3ac532f9)
