### ISSUE TITLE
Country error

### ISSUE THREAD

**Issue by millerjeremya** [plazi/community#309]
Please leave your comment here...
Erroneously inferred country, should be Sri Lanka, not Netherlands

**Context**
[GBIF occurrence](https://www.gbif.org/occurrence/1291011465)
[Plazi reference](http://treatment.plazi.org/id/03D68E42A11EFFACFF37FF01C2CD40B5)

**Comment by juwingert** [comment]
Hi @millerjeremya, I just fix that, thanks for your concern. 
Best regards.

**Comment by millerjeremya** [comment]
Hi, I was just checking up on this record. I don't see any change on GBIF. I realize it takes some time to update, not sure how long these days, but it's been nearly 1 month. Did something go wrong?

**Comment by juwingert** [comment]
Hi @millerjeremya, I can't tell you exactly why it hasn't changed in GBIF, but now I've done a deeper quality control, I believe it will solve the problem. Thank you for your feedback.
