### ISSUE TITLE
Fwd: Mix up in higher taxonomy between host and parasite

### ISSUE THREAD

**Issue by mguidoti** [plazi/community#31]
This was originally posted here: https://github.com/gbif/portal-feedback/issues/2727

Here's the print from the original thread:

![image](https://user-images.githubusercontent.com/44419136/79758401-bbf0b680-82f3-11ea-8657-43083d6bea10.png)

This is probably very simple to fix. The higher ranks was mistaken from hosts to parasites. Just have to go into each paper's IMF and fix the higher ranks for the mentioned taxa.

Could you do it, @flsimoes ?

Please, close the issue when it's done. 

This is an urgent task, so, please, halt what you're working on to fix this first. It came directly from @myrmoteras.

Thanks a lot!

**Comment by flsimoes** [comment]
Sure, will get to it right away!

**Comment by ManonGros** [comment]
Thanks @flsimoes and @mguidoti!
FYI: I updated the issue and added some genera (it would be great if you could check these as well before closing the issue). Many thanks!

**Comment by flsimoes** [comment]
I'll provide gradual updates within this comment just so we can keep track of changes:

Genera | DOI(s) of the dataset concerned | Status
-- | -- | --
Pseudonematophila | https://doi.org/10.5281/zenodo.279099, https://doi.org/10.15468/tshrol | **DONE**
Crassacarus | https://doi.org/10.11646/zootaxa.4023.1.1, https://doi.org/10.15468/lqwl7q
Vireodectes, Picipterodectes and Montsauria | https://doi.org/10.5281/zenodo.282115, https://doi.org/10.15468/d6pc0u
Fainharpirhynchus and Perhapyrhynchus | https://doi.org/10.11646/zootaxa.3860.4.1, https://doi.org/10.15468/rj0uq2
Atelophyllodes | https://doi.org/10.5281/zenodo.192069, https://doi.org/10.15468/bfafmr
Neopicobia and Rafapicobia | https://doi.org/10.11646/zootaxa.4113.1.1, https://doi.org/10.15468/ad9psd
Harpactiacus, Cinclosomatiellum, Philemoniellus, Garrulaxeus and Estrildinirmus | https://doi.org/10.11646/zootaxa.4615.2.2, https://doi.org/10.15468/yg76nv
Krantziaulonastus | https://doi.org/10.5281/zenodo.207623, https://doi.org/10.15468/urlfnk
Tyrannidectes | https://doi.org/10.5281/zenodo.203166, https://doi.org/10.15468/b6e5m8

**Comment by flsimoes** [comment]
These should be all done now. Please check if the corrections were properly made (it may take a couple of hours for GBIF to update though).

**Comment by flsimoes** [comment]
Forgot about this one:

Genera | DOI(s) of the dataset concerned | Status
-- | -- | --
Carnarvoncochlea and Conondalia | https://doi.org/10.11646/zootaxa.4583.1.1, <br>https://doi.org/10.15468/ycrhs6 | **Underway**

**Comment by ManonGros** [comment]
Thanks @flsimoes! I think everything looks good! I will keep the issue open on our side for our next backbone taxonomy update (we need to be able to check that the taxonomy has been corrected on our side).

**Comment by flsimoes** [comment]
@ManonGros Please let me know if anything like this happens again. Doesn't take long to fix most of this cases.
