### ISSUE TITLE
Month treatments with Coleoptera clasification

### ISSUE THREAD

**Issue by camiplata** [plazi/community#310]
I detected this issues on checklistBank, species of the paper "Twonew endemicspecies ofAbantiades Herrich-Schäffer (Lepidoptera: Hepialidae) from Kangaroo Island, Australia" . All taxa should be under Lepidoptera: Hepialidae, but they have been erronuesly matched to Coleoptera.

<img width="1184" alt="Captura de pantalla 2024-07-18 a la(s) 6 26 04 p m" src="https://github.com/user-attachments/assets/148f9a42-4f0b-463a-a6ca-95ea174d036b">
<img width="852" alt="Captura de pantalla 2024-07-18 a la(s) 6 27 44 p m" src="https://github.com/user-attachments/assets/1e3a9b98-25ea-404b-970f-33d47de319a5">

CLB example: https://www.checklistbank.org/dataset/7381/taxon/1712607434071334D2A6F9E7FEABF855.taxon
Plazi treatment: https://tb.plazi.org/GgServer/summary/EB2B180C34051336D231FFE6FFB3FFB5

Would are aiming to use  the fixed DwCA of this dataset for Cataloge of Life extended release

PD: the  paper title has some missing spaces between words

**Comment by kbamaral** [comment]
Solved!
