### ISSUE TITLE
Hymenoptera treatments with Plant clasification 

### ISSUE THREAD

**Issue by camiplata** [plazi/community#311]
I detected this issue on checklistBank, species of the paper "Dryinidae of the Afrotropical region (Hymenoptera, Chrysidoidea)" . All taxa should be under **Hymenoptera, Chrysidoidea,** but the genus  **Gonatopus Ljunghand** and all its species have been erroneously matched to  Plantae >phylum: Tracheophyta >class: Liliopsida >order: Alismatales >family: Araceae >

<img width="1067" alt="Captura de pantalla 2024-07-22 a la(s) 11 26 43 a m" src="https://github.com/user-attachments/assets/7fc97483-9c48-485d-86c6-ddbf883accf9">

CLB example: https://www.checklistbank.org/dataset/7381/taxon/1712607434071334D2A6F9E7FEABF855.taxon
Plazi treatment: https://treatment.plazi.org/GgServer/summary/FFD0FF9AFFAF2A48FFA9D64EFFE1FF87

Would are aiming to use the fixed DwCA of this dataset for Cataloge of Life extended release

**Comment by flsimoes** [comment]
Should be fixed now
Thanks for reporting!
