### ISSUE TITLE
Scale insect treatments with Plant clasification

### ISSUE THREAD

**Issue by camiplata** [plazi/community#313]
Paper: A new scale insect genus, Torosaspis (Hemiptera: Sternorrhyncha: Coccoidea: Diaspididae), with a new species, Torosaspi.

CLB: https://www.checklistbank.org/dataset/46733/classification?taxonKey=8F6E2521A053C70B9BC3FD65FE49FB28.taxon
PLAZI: https://treatment.plazi.org/GgServer/summary/73575D59A052C70A9B54FFD7FFE2FFCA

We are aiming to use the fixed DwCA of this dataset for Cataloge of Life extended release

<img width="1010" alt="Captura de pantalla 2024-07-22 a la(s) 1 11 07 p m" src="https://github.com/user-attachments/assets/1d301cc9-6021-4c15-b19f-433b7f5ecaff">
<img width="1017" alt="Captura de pantalla 2024-07-22 a la(s) 1 13 16 p m" src="https://github.com/user-attachments/assets/de5e0a17-c9f9-40e0-b1b1-c47da9dc40da">

**Comment by kbamaral** [comment]
Solved!

**Comment by camiplata** [comment]
thanks!!
