### ISSUE TITLE
Plazi datasets where one or several treatments have been wrongly assigned a Plant classification

### ISSUE THREAD

**Issue by camiplata** [plazi/community#314]
Plazi datasets where one or several treatments have been wrongly assigned a Plant classification. From 30 datasets reviewed half had this problem. 

COL has been using all Plazi datasets to build Catalogue of life extended release, one of the difficulties we have is that some  taxa have been wrongly assigned to a Plant classification. This creates very hard to spot issues on COL.
Some of the datasets listed are recent  2020-2023 so they probably have been proceed under the plazi workflow that uses "preferred kingdom" but still have been misplaced, maybe having also a preferred order and class by article could help to avoid misplaced classifications.

- [x] [Atlas of European millipedes 2: Order Julida (Class Diplopoda)](https://www.dev.checklistbank.org/dataset/21780/classification)
- [x] [An annotated catalog of the Iranian Pentatomoidea (Hemiptera: Heteroptera: Pentatomomorpha)](https://www.dev.checklistbank.org/dataset/36815/classification)
- [x] [Synopsis of Bakeriella Kieffer, 1910 (Hymenoptera, Bethylidae)](https://www.dev.checklistbank.org/dataset/42303/classification)
- [x] [A review of Dinetus Panzer, 1806 with descriptions of five new species and keys to world species (Hymenoptera, Crabronidae)](https://www.dev.checklistbank.org/dataset/3615/classification)
- [x] [Hidden diversity within the Nemastoma bidentatum Roewer, 1914 complex (Opiliones: Nemastomatidae) Part I: Morphological](https://www.dev.checklistbank.org/dataset/3586/classification)
- [x] [Grass-dependent Thysanoptera of the family Thripidae from Australia](https://www.dev.checklistbank.org/dataset/46148/classification)
- [x] [Revision of the Afrotropical species of Gonatopus group 3 (Hymenoptera: Dryinidae), with description of a new species f...](https://www.dev.checklistbank.org/dataset/36848/classification)
- [x] [Taxonomic review of the genus Urostylis (Hemiptera: Heteroptera: Urostylididae) from the Korean Peninsula, with descrip...](https://www.dev.checklistbank.org/dataset/29903/classification)
- [x] [The Leiodidae (Coleoptera) of Atlantic Canada: new records, faunal composition, and zoogeography](https://www.dev.checklistbank.org/dataset/22573/classification)
- [x] [Lost and found: The Eocene family Pyramimitridae (Neogastropoda) discovered in the Recent fauna of the Indo-Pacific](https://www.dev.checklistbank.org/dataset/46667/classification)
- [x] [Type Specimens Of Birds In The American Museum Of Natural History Part 11. Passeriformes: Parulidae, Drepanididae, Vire...](https://www.dev.checklistbank.org/dataset/7647/classification)
- [x] [The type material of spider wasps (Hymenoptera, Pompilidae) deposited in the Federal Scientific Center of the East Asia...](https://www.dev.checklistbank.org/dataset/20076/classification)
- [x] [Contribution to the knowledge of Afrotropical Dryinidae, Embolemidae and Sclerogibbidae (Hymenoptera), with description...](https://www.dev.checklistbank.org/dataset/28721/classification)
- [x] [Checklist of Dryinidae (Hymenoptera) from Guangdong Province, China, with descriptions of two new species)](https://www.dev.checklistbank.org/dataset/45256/classification)

**Comment by flsimoes** [comment]
@camiplata 
This record has a lot of host plants in it, so there's a good mix of Animals and Plants across the text. I did manage to quickly find a genus that was wrongly assigned, but it will take quite a bit of effort to find others.

Unless we figure out a faster way of filtering only those that are likely homonyms...

[An annotated catalog of the Iranian Pentatomoidea (Hemiptera: Heteroptera: Pentatomomorpha)](https://www.dev.checklistbank.org/dataset/36815/classification)
[36815](http://www.checklistbank.org/dataset/36815/about)

**Comment by flsimoes** [comment]
For this one below I'll have to ask Guido to check. It is an older upload and there is barely any higher taxonomy information in it.

[FF8F2C440F19BB7AFFA3991A3B5CFFE6](https://tb.plazi.org/GgServer/summary/FF8F2C440F19BB7AFFA3991A3B5CFFE6)
[Contribution to the knowledge of Afrotropical Dryinidae, Embolemidae and Sclerogibbidae (Hymenoptera), with description...](https://www.dev.checklistbank.org/dataset/28721/classification)

**Comment by camiplata** [comment]
thanks @flsimoes !!
