### ISSUE TITLE
196 datasets with potential classification issues

### ISSUE THREAD

**Issue by camiplata** [plazi/community#315]
Under the assumption that all treatments from a digitized paper belong to the same kingdom I have pulled apart 196 Plazi datasets where there are names assigned to more than one kingdom. This datasets are very likely to have incorrect classifications (see for example #311 )

[plazi_multipleKigdoms_2024-07-29.csv](https://github.com/user-attachments/files/16421136/plazi_multipleKigdoms_2024-07-29.csv)

**Comment by flsimoes** [comment]
Just an update
We've fixed 181 out of the 196 datasets.

**Comment by camiplata** [comment]
thanks for the update @flsimoes
