### ISSUE TITLE
147 datasets where one or several treatments have been wrongly assigned to a Plant classification

### ISSUE THREAD

**Issue by camiplata** [plazi/community#316]
I did an evaluation of the datasets providing Plant information to the Catalogue of life extended release, and looked for title patterns that indicated a wrongly assigned Plant classification. For example, if the article title contained insect orders but had a plant classification, and found 147 datasets with wrong classifications.

[plazi-Plants missmatched classification_ 2024-07-30.csv](https://github.com/user-attachments/files/16433665/plazi-Plants.missmatched.classification_.2024-07-30.csv)

Some datasetes  may have a mixed Animal/Plant classification for example:

<img width="940" alt="Captura de pantalla 2024-07-31 a la(s) 10 35 30 a m" src="https://github.com/user-attachments/assets/a4ef179b-965b-4e1e-aae8-453609113807">

Related to: #314 , #315

**Comment by camiplata** [comment]
Hi @flsimoes @jugiora, I would like to know if you see feasible to update these datasets during the following months. I know there are several species new to  COL among these datasets and we should like to add them.

**Comment by flsimoes** [comment]
Hi @camiplata 
Yes, we'll be working on them, not sure how long it will take though. Hopefully not that long.

**Comment by camiplata** [comment]
Thanks @flsimoes I'll be looking forward to it

**Comment by flsimoes** [comment]
For the record:

The following dataset doesn't seem to be properly linked with the Plazi UUID. Need to figure out what's going on...

https://www.checklistbank.org/dataset/34551

https://tb.plazi.org/GgServer/dioStats/stats?outputFields=doc.articleUuid+doc.name+doc.clbId+bib.title+cont.pageCount&groupingFields=doc.articleUuid+doc.name+doc.clbId+bib.title&FP-doc.articleUuid=5C00FF9EFFDAFF805469564E9829FF97&format=HTML

**Comment by myrmoteras** [comment]
@flsimoes this dataset is from Zookeys, may be ask Guido, since he is processing the mat it in them at the moment.

New species of the day<https://tb.plazi.org/GgServer/static/newToday.html>
Plazi<https://plazi.org/>
Bouchout+10 symposium<https://bouchoutdeclaration2024.org/>, August 21-23, 2024
________________________________

**Comment by flsimoes** [comment]
Just an update
We've fixed 147 out of the 147 datasets.

**Comment by flsimoes** [comment]
These have now been fixed

**Comment by flsimoes** [comment]
There are some instances where two different Kingdoms/Domains are indeed cited in the publication:

Plazi UUIDs
9C1BE31AF15C7114FF8E6C49114DCE31
FFD5FF846E72FFE2CC406A268A735F10
995A427BFF9D7035D435FFF7BA250562
FFE9FF8BFF9BFFB9FFA28857C46E2F4D
C707FFA2FF32FFDCFFE0FFB1931FE349
523FA83BFFF8FF9CFFB3976DFFAEFFA8
CC41A15E100EFFAEFFD9F637D100FFCD
1605FFABFE16FFCAFFFAFFDAFF90F27D

**Comment by camiplata** [comment]
This is really great @flsimoes, thanks for checking and fixing all these datasets.
