### ISSUE TITLE
Authorship incorrectly inferred - Phengaris teleius - https://doi.org/10.11646/zootaxa.4438.3.5

### ISSUE THREAD

**Issue by ManonGros** [plazi/community#317]
Hi PLAZI,

We recently received some feedback about this record (https://www.gbif.org/species/146020021) from this dataset: https://www.gbif.org/dataset/94c2cac9-f7a5-46f6-ae62-a6a93c9009ed (associated publication https://doi.org/10.11646/zootaxa.4438.3.5). The authorship associated with the name is Virgstrassir, 1779 in the dataset. However, in the zootaxa publication, the name provided is Phengaris teleius (Bergsträsser, 1779) which seems consisted with other sources. See the screenshot of zootaxa publication:
<img width="584" alt="Screenshot 2024-08-13 at 10 25 49" src="https://github.com/user-attachments/assets/b264d117-3dfa-458a-8fc0-6fdf53635f3b">

Would it be possible to change the authorship? Thanks!

**Comment by JonasBlanco** [comment]
Hi!

I just fixed it. It should be updated soon.
Let me know if there's any issue left.

Kind regards.

**Comment by JonasBlanco** [comment]
Here is the link for our fixed treatment:
https://treatment.plazi.org/id/03FDE918FFB0EA74FF30E801FCE4637B

**Comment by ManonGros** [comment]
Thank you @JonasBlanco!

In the literature this name seems to be a synonym of another name. I couldn't find in the publication something that indicates that this name is an accepted one (it is very possible I missed it). If the information isn't available, would it be better to leave the `taxonomicStatus` field blank?
(I am sure 100% sure about this, this is a real question)

**Comment by JonasBlanco** [comment]
Hi again!

Even though this species has been considered a synonym of any other taxonomic name in a different article, we should not include that information here.
We cannot make interpretations about the information presented in the article; we only release the data exactly as it was written.
If there is indeed a synonymy, that information can only be derived from the article in which the synonymization was made.
I hope I have been able to resolve your inquiry.

Sincerely,
Jonas

**Comment by ManonGros** [comment]
Thanks @JonasBlanco !
