### ISSUE TITLE
Correction to Plazi records found on GBIF

### ISSUE THREAD

**Issue by millerjeremya** [plazi/community#318]
Please leave your comment here...
Two records of Lepthyphantes christodeltshev van Helsdingen, 2009 extracted from 

HELSDINGEN, P. J. V. 2009. Lepthyphantes christodeltshev, a new species from Greece (Araneae, Linyphiidae). ZooKeys, 16, 301-308 doi: 10.3897/zookeys.16.226.

should be basisOfRecord = MaterialCitation
not PreservedSpecimen

The country of the holotype is given as Netherlands, but should be Greece

**Context**
[GBIF occurrence](https://www.gbif.org/occurrence/2608846175)
[Plazi reference](http://treatment.plazi.org/id/03D4616E2E46A00E03E4FD62FD0B8A5D)

**Comment by JonasBlanco** [comment]
Hi!

I just fixed the country for the materials.
Soon it should be correct in GBIF as well.

**Comment by JonasBlanco** [comment]
Hi!

I fixed the material citation in the document.
Just waiting now for GBIF to update.
