### ISSUE TITLE
Animalia is included as "genus" in several datasets

### ISSUE THREAD

**Issue by DianRHR** [plazi/community#319]
The dataset [26210 ](https://www.checklistbank.org/dataset/26210/classification) in ChecklistBank included 25 genus names as "Animalia" all of them with different authority, which is a big mistake. The 'genus Animalia'  is also present in other datasets: 300889, 25386, 203547. 

![image](https://github.com/user-attachments/assets/1d5102b6-cef5-49a8-9a19-9d18e2beb1a5)

Also, in this dataset almost all the families are duplicated with the same author. 
![image](https://github.com/user-attachments/assets/a73b6e26-e786-4eac-b6d3-622775e472b7)

**Comment by Carol-Sokolowicz** [comment]
Hi Dian,
I fixed those "Animalia" names that were mistakenly placed as genus and deleted the duplicated treatments.
I might take a while to update in all platforms, including the CheckList Bank.
But if you notice any persisting problem let me know.
Cheers

**Comment by DianRHR** [comment]
Thanks Carol, I checked it in Checklist Bank and it's almost clean, but still some families are duplicated, some with children and some just the family.

**Comment by camiplata** [comment]
@DianRHR is see the major issue has been adressed, for the propuse of the extended release is the issue closed?

**Comment by DianRHR** [comment]
There is still one genus "Animalia" in this dataset. I blocked the name "Animalia" as genus to avoid merging this name.
