### ISSUE TITLE
Errors in Taxonomic Tree

### ISSUE THREAD

**Issue by JCGiron** [plazi/community#32]
There are three instances of what should be one Arthropoda: Arthorpoda and Artropoda need to be corrected.
http://tb.plazi.org/GgServer/explorer

![image](https://user-images.githubusercontent.com/37313282/79911034-4fee7b00-83e5-11ea-8059-8901ee00ef0a.png)

There is also one additional "Arthropoda" within Arthropoda.

Hexapoda e Insecta appear separately under Arthropoda.

Alcyonacea (Cnidaria) and Anura (Chordata) appear within Insecta, and there are multiple other errors within Insecta.

**Comment by myrmoteras** [comment]
need to assign @gsautter for this

**Comment by gsautter** [comment]
This comes straight from the data ... either there are typos in the source documents proper, or the typos come from the higher taxa we import from GBIF and CoL ...

We can surely run some frequency analysis on the higher taxa we have in out stats, double-check the infrequent ones, and then correct them in the source documents.  But the input which taxa are misspelled has to come from the taxonomers, please, for me the only way of checking a taxon name is the catalogs proper.
