### ISSUE TITLE
Issues on the Mesostigmatic mites (Acari: Mesostigmata) of Saudi Arabia... paper digitization

### ISSUE THREAD

**Issue by camiplata** [plazi/community#321]
ref: https://treatment.plazi.org/GgServer/summary/CE683F45DE42FFF0FFF8FF8BFFFD0366

1. wrong classification, Polyaspis (Polyaspis) madagascarensis Kontschan & Stary, 1881 is a  mite not an hemipteran

**Original paper**
<img width="860" alt="Captura de pantalla 2024-09-11 a la(s) 12 22 42 p m" src="https://github.com/user-attachments/assets/3308e9cf-30e2-4429-87a7-91a84b6ea959">

**Currently on Plazi**
https://treatment.plazi.org/GgServer/html/3251473DDE4BFFFAFF6FF8FEFC6703B2
<img width="1142" alt="Captura de pantalla 2024-09-11 a la(s) 12 21 37 p m" src="https://github.com/user-attachments/assets/865412a3-cb00-42cf-a3bf-908c8966328c">

2. Missing genus

Empty families that on the original paper have at least one genus
<img width="614" alt="Captura de pantalla 2024-09-11 a la(s) 12 30 57 p m" src="https://github.com/user-attachments/assets/424ff087-80db-413c-8a3c-6667218a1c3b">

- Uroobovella
<img width="600" alt="Captura de pantalla 2024-09-11 a la(s) 12 46 16 p m" src="https://github.com/user-attachments/assets/5afb5745-593c-4d11-ab6b-d8800a7cbfe5">

- Clausiadinychus

<img width="600" alt="Captura de pantalla 2024-09-11 a la(s) 12 47 04 p m" src="https://github.com/user-attachments/assets/9a3003c5-deed-4553-9d3b-d55c0e491a72">

- Saprolaelaps

<img width="600" alt="Captura de pantalla 2024-09-11 a la(s) 12 47 50 p m" src="https://github.com/user-attachments/assets/ff227e83-4492-4aad-948c-e0dc30078eaa">

- Nenteria

<img width="600" alt="Captura de pantalla 2024-09-11 a la(s) 12 52 29 p m" src="https://github.com/user-attachments/assets/5171570c-7bd7-46a5-88bf-063a4f27bb3d">

**Comment by valdenar** [comment]
Hi @camiplata 
Thank you for the issue, it is important for us to receive this feedback!
Regarding the first point, I made the correction and will update it soon. 
Regarding the second point, I reviewed all the taxon names and they appear to be correct. Could you give me more information about the problem? What is the origin of the print that lists the families?

**Comment by flsimoes** [comment]
@camiplata regarding point 2:

I believe that the reason those genera are not showing up is that their respective treatments are of undetermined species, such as _Nenteria_ sp.
In these cases, we have a "isUncertain" attribute, which might have been held by our gatekeeper
I've run a quality control now, let's see if it shows up at your end.

**Comment by camiplata** [comment]
Thank you @valdenar por quicly fixing the issue, the second point is more about the missing genera, but I noticed they were missing via de families.

@flsimoes  I see! actually is a gut thing to have such a gatekeeper. Thanks for checking!

**Comment by camiplata** [comment]
Hi again, i just noticed that Polyaspis still has an incorrect classification under insects.

<img width="783" alt="Captura de pantalla 2024-11-19 a la(s) 11 07 16 p m" src="https://github.com/user-attachments/assets/b9c66ba0-cc62-4f0c-aef4-b136fbb4dba0">

**Comment by JonasBlanco** [comment]
Hi @camiplata!

I just fixed it, soon it should be updated in the databases.

Kind regards!

**Comment by JonasBlanco** [comment]
https://treatment.plazi.org/GgServer/html/3251473DDE4BFFFAFF6FF8FEFC6703B2

**Comment by camiplata** [comment]
Great!
