### ISSUE TITLE
Please update classification according to original paper - E74DFF91E418FFECC552FFD20E6DFFB3

### ISSUE THREAD

**Issue by camiplata** [plazi/community#323]
The correct higher classification of the [treatments associated](https://treatment.plazi.org/GgServer/summary/E74DFF91E418FFECC552FFD20E6DFFB3) to [this paper](https://www.mapress.com/zt/article/view/zootaxa.4564.1.12),  is:

Coleoptera> Staphylinidae> Scydmaeninae

**Comment by juwingert** [comment]
Dear @camiplata hello! Thanks for your feedback, the classification of taxon name and treatment is fixed already.

**Comment by camiplata** [comment]
thanks!!
