### ISSUE TITLE
Duplicated Family - Amazighopsidae, a new family of decapod macruran astacideans

### ISSUE THREAD

**Issue by camiplata** [plazi/community#324]
Hi the DWC-A use by CLB has the family duplicated as Amazighopsidae nov nov., this will render this dataset inadequate to use o COL extended release

https://tb.plazi.org/GgServer/summary/E31E2E30FFDCFFF3FFF73F0B6146FFFC

<img width="711" alt="Captura de pantalla 2024-10-05 a la(s) 10 23 11 a m" src="https://github.com/user-attachments/assets/36b0624d-0854-46aa-87f0-2a2da9028481">

**Comment by kbamaral** [comment]
Solved!
