### ISSUE TITLE
Incorrect classification an wrong or missing informaction

### ISSUE THREAD

**Issue by camiplata** [plazi/community#325]
https://tb.plazi.org/GgServer/summary/BD3DFFB7FFC3314DA356B63FFF96FFB5

Issues on this dataset DwC-A, this renders this dataset inadequate to use for COL
-  Taxa under plantae
-  Duplicated genera
-  Missing species

<img width="711" alt="Captura de pantalla 2024-10-05 a la(s) 10 25 19 a m" src="https://github.com/user-attachments/assets/925f53b1-0207-4c14-8dbd-6c7a13aa2fd9">

**Comment by kbamaral** [comment]
Hi Camila!

I made some corrections in this paper, but we are not sure if they will solve the problems you indicate. Please let us know if we need to do something else.
