### ISSUE TITLE
Stilbum splendidum- wrong higher classification - should be Hymenoptera - http://dx.doi.org/10.3897/zookeys.486.8753

### ISSUE THREAD

**Issue by ManonGros** [plazi/community#326]
This issue was originally reported here: https://github.com/gbif/backbone-feedback/issues/545

In this dataset published on GBIF: https://www.gbif.org/dataset/051394d3-767e-414f-b131-c84675a7a27f, Stilbum splendidum is published as a Fungi when it should be a Hymenoptera: https://www.gbif.org/species/152058522

See the original publication.

Would it be possible to update the dataset on GBIF? thanks!

**Comment by guilhermepcoelho** [comment]
Hello @ManonGros 

I fixed the higher taxonomy of all Stilbum names. They are correct on TreatmentBank now and soon they should be correct in GBIF as well.

Best regards.
