### ISSUE TITLE
Author typo paper "A new species of Sinophasma Günther, 1940"

### ISSUE THREAD

**Issue by camiplata** [plazi/community#327]
The author of the above mention paper `Günther, 1940`  got digitized as `Guenther, 1940 `, wich creates a duplicated genus when the treatment is use in COL

treatment: https://treatment.plazi.org/GgServer/summary/4E38DA1EFF9EFFD6C939FFDB9725EA67
original paper: https://dez.pensoft.net/articles.php?id=1123

**Comment by guilhermepcoelho** [comment]
Hello, @camiplata,

I have corrected all mentions of "Guenther" to "Günther" in this paper, as well as in the taxonomic names attributes. This name is already correct in TreatmentBank.

Best regards.
