### ISSUE TITLE
Doryphora reticulata Fabricius, 1787 - incorrect higher classification - should be Coleoptera - http://dx.doi.org/10.3897/zookeys.332.5199

### ISSUE THREAD

**Issue by ManonGros** [plazi/community#328]
Hi PLAZI,

Thank you for fixing the other issue I logged today so fast! This other issue was reported on helpdesk on this dataset: https://www.gbif.org/dataset/51e275b4-e4fa-4f96-aea9-cc96efa8c31d

Doryphora reticulata Fabricius, 1787 is actually a Coleoptera (Chrysomelidae, Chrysomelinae) as mentioned in the original publication. However this record shows it as a Lepidoptera: https://www.gbif.org/species/152047668

Would it be possible to update the dataset? Thanks!

**Comment by ManonGros** [comment]
It looks like there is the same issue for Doryphora paykulli (Stal, 1859) Stal, 1859: https://www.gbif.org/species/152047667

**Comment by guilhermepcoelho** [comment]
Hi, @ManonGros

I've corrected the higher taxonomy for all Doryphora names. They are already correct in TreatmentBank and soon they should be correct in GBIF as well.

Best regards.
