### ISSUE TITLE
Wrong classification Molluscs nested under Hemiptera

### ISSUE THREAD

**Issue by camiplata** [plazi/community#330]
One of COL data providers identified that the following  Plazi treatments are Mollusc and not Hemipterans.

https://treatment.PLAZI.org/id/5344AD7E1F6757C5ADB377B8690B5FCA
https://treatment.PLAZI.org/id/20E83D4AF6CACA600A64E4583BA940CD
https://treatment.PLAZI.org/id/FF6655E0AD0CD70C7A04B280DADBC44A
https://treatment.PLAZI.org/id/382B00939581C768BD24B4B0A614AB79
https://treatment.PLAZI.org/id/B60FE8BF8BA7B6E218068E13CCC26655
https://treatment.PLAZI.org/id/85CB9026CF0B3C59DD437D1557EAFCB4
https://treatment.PLAZI.org/id/F2FD38E6FA2A78E735998BF6CC5508EE
https://treatment.PLAZI.org/id/7C71CC6AEAB425F46D3FDD659D96D4E4
https://treatment.PLAZI.org/id/C048E568F016AA580DF6D3C7C6B2DB34
https://treatment.PLAZI.org/id/2AF55B524978278C0D1701AE18C7E01F
https://treatment.PLAZI.org/id/734224F324481632BF84767CA2F1BC63
https://treatment.PLAZI.org/id/19B9F35A78C332518D0D6F85C1D370CD
https://treatment.PLAZI.org/id/A928DAD8E738F1F14D1EEDCCC2786877
https://treatment.PLAZI.org/id/2B2EE9E6783ED206A2F1F33A3D5EF9EE
https://treatment.PLAZI.org/id/FB6BA410F2288D7A0094A266FDDB1939
https://treatment.PLAZI.org/id/791B5ED3FCBED3CFBF27CA2BAB7C6E51
https://treatment.PLAZI.org/id/26868E77846EA910123782C6FE430CC8
https://treatment.PLAZI.org/id/2FA4923CCD16968C3F97E019FC4FCB0F

**Comment by Carol-Sokolowicz** [comment]
This was fixed, if you find any errors left, please tell me

**Comment by camiplata** [comment]
Thanks Carol

**Comment by camiplata** [comment]
One more for this fix please https://treatment.plazi.org/id/43C4DFCBB1D72FE91B6B23558548DD86
