### ISSUE TITLE
Error in higher classification in dataset 49123 in ChecklistBank

### ISSUE THREAD

**Issue by DianRHR** [plazi/community#333]
This [dataset ](https://www.checklistbank.org/dataset/49123/classification?taxonKey=xG )and [Treatment ](https://treatment.plazi.org/id/03D887D8FFE18D01FF59FC05FD554011) have an important error in its higher classification and in the author of the name: 

Acanthurus nigricans is a fish not a beetle. This may be due to the homonym genus , however the article is completelly about the fish. 
Also, the authorship is (Linnaeus 1758) not (Linnaeus, 1758) Linnaeus 1758

**Comment by DianRHR** [comment]
Same cases in datasets: 
[2792 ](https://www.checklistbank.org/dataset/2792/classification?taxonKey=xY5)
[2179 ](https://www.checklistbank.org/dataset/21779/classification?taxonKey=xD4)
[46758](https://www.checklistbank.org/dataset/46758/classification?taxonKey=x8)

There might be other datasets with the same problem including other genus.

**Comment by flsimoes** [comment]
> This [dataset ](https://www.checklistbank.org/dataset/49123/classification?taxonKey=xG)and [Treatment ](https://treatment.plazi.org/id/03D887D8FFE18D01FF59FC05FD554011) have an important error in its higher classification and in the author of the name:
> 
> Acanthurus nigricans is a fish not a beetle. This may be due to the homonym genus , however the article is completelly about the fish. Also, the authorship is (Linnaeus 1758) not (Linnaeus, 1758) Linnaeus 1758

This is fixed now. I'll work on the other 3 next.

**Comment by flsimoes** [comment]
> Same cases in datasets: [2792 ](https://www.checklistbank.org/dataset/2792/classification?taxonKey=xY5) [2179 ](https://www.checklistbank.org/dataset/21779/classification?taxonKey=xD4) [46758](https://www.checklistbank.org/dataset/46758/classification?taxonKey=x8)
> 
> There might be other datasets with the same problem including other genus.

These have now been fixed as well
