### ISSUE TITLE
Non scientific name "Gen_Indet" in genus and species

### ISSUE THREAD

**Issue by camiplata** [plazi/community#334]
Non scientific name "Gen_Indet" in genus and species in:  A new Theropod Dinosaur from the Upper Cretaceous of Central Montana

https://www.checklistbank.org/dataset/25070/classification?taxonKey=xG
https://tb.plazi.org/GgServer/summary/FFABFFE7D0753E485958FF9FFF81D87D

<img width="907" alt="Captura de pantalla 2024-10-30 a la(s) 10 04 51 a m" src="https://github.com/user-attachments/assets/17a4a351-04ac-42a5-adc5-3ebd2c4b47ad"

**Comment by flsimoes** [comment]
Hi @camiplata this is part of a larger work with T. rex publications (@millerjeremya). As far as I'm aware this one is what it is. Fossils tend to have some odd situations with their classification.

**Comment by camiplata** [comment]
Hi @flsimoes, fossils are not on my expertise field so my apologies if I make wrong interpretations. But I understand Gen_Indet  works  like a placeholder (unranked) rather than a scientific name or a common name of the Jordan Theropod refered  on the paper thus is incorrect to mark it as a genus or as a species.

would it be a better way to represent cases like this?

**Comment by flsimoes** [comment]
To be honest, I'm not sure what's the best course of action.
As I understand, it was done this way so that the fossil appears in the citation list for T. rex in Synospecies.
What I did right now is to add an `isUncertain` attribute which did not exist when this was first processed. 


Perhaps this record could be removed on your end?

**Comment by camiplata** [comment]
yes we can handle it at our end, still interesting to understand how fossil data works

**Comment by myrmoteras** [comment]
@camiplata this has not so much to do with fossils, other than this bone wanted to be placed in a systematic framework. In other parts of taxonomy we normally don't have this urge to put a name on something. Sometimes this happenes in large phylogenies where the urge is to publish the phylogeny and indicate, that there is a genus or so in the need of description. If I remember right, this happens also sometimes in large monographs where the focus is to describe species rather the odd specimens that don't fit into the used TX nomuc framework.

New species of the day<https://tb.plazi.org/GgServer/static/newToday.html>
Plazi<https://plazi.org/>
Bouchout+10 symposium<https://bouchoutdeclaration2024.org/>, August 21-23, 2024
________________________________
