### ISSUE TITLE
Two occurrences with incorrect scientific names - https://doi.org/10.15468/a8x29b

### ISSUE THREAD

**Issue by ManonGros** [plazi/community#336]
Hi PLAZI,

We recently received some feedback concerning this dataset: https://www.gbif.org/dataset/8b4bac91-4cf6-46d8-86e9-08b648c3ce16
It looks like the scientific name for these two occurrences should be _Farlowella acestrichthys_ (see the original message and explanations here: https://github.com/gbif/portal-feedback/issues/5536#issuecomment-2447438782).

Would it be possible to take a look? Thanks!

**Comment by flsimoes** [comment]
https://github.com/gbif/portal-feedback/issues/5536#issuecomment-2450589019
