### ISSUE TITLE
Wrong DOI associated with GBIF dataset based on Plazi treatment

### ISSUE THREAD

**Issue by CecSve** [plazi/community#338]
The GBIF dataset [The improvement of heavy vehicle design to reduce injury risk in crashes with other road users](https://www.gbif.org/dataset/9f78774a-2c2e-4007-9af4-b456cb76dc5d) is linked to the following [DOI](http://dx.doi.org/10.26180/14834796) which resolves to a doctoral thesis from Monash University and does not seem to have anything to do with the Russian Entomological Journal.

**Comment by myrmoteras** [comment]
This is funny.
Will check what went wrong

New species of the day<https://tb.plazi.org/GgServer/static/newToday.html>
Plazi<https://plazi.org/>
Bouchout+10 symposium<https://bouchoutdeclaration2024.org/>, August 21-23, 2024
________________________________
From: Cecilie Svenningsen ***@***.***>
Sent: Friday, November 1, 2024 11:51:27 AM
To: plazi/community ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [plazi/community] Wrong DOI associated with GBIF dataset based on Plazi treatment (Issue #338)

EXTERNAL SENDER


The GBIF dataset The improvement of heavy vehicle design to reduce injury risk in crashes with other road users<https://www.gbif.org/dataset/9f78774a-2c2e-4007-9af4-b456cb76dc5d> is linked to the following DOI<http://dx.doi.org/10.26180/14834796> which resolves to a doctoral thesis from Monash University and does not seem to have anything to do with the Russian Entomological Journal.

**Comment by flsimoes** [comment]
Not sure what happened there, likely a doi mismatch when using Refindit to recover the metadata, but anyway, I've now fixed it on our end. Changes to the GBIF entry should appear shortly.
