### ISSUE TITLE
Wrong classification assigned to genus Stenodema

### ISSUE THREAD

**Issue by DianRHR** [plazi/community#339]
In this [dataset ]([url](url))the genus is wrongly placed under family Curculionidae. The original [publication ](https://www.researchgate.net/publication/334529002_Annotated_checklist_of_the_Hemiptera_Heteroptera_of_the_Site_of_Community_Importance_and_Special_Area_of_Conservation_Alpi_Marittime_NW_Italy)places it in Miridae

![image](https://github.com/user-attachments/assets/a49b8ca8-999c-4481-993a-d29220832066)

**Comment by flsimoes** [comment]
This is fixed now. Thanks for reporting!

GBIF: https://www.gbif.org/dataset/27455364-100a-4f24-b17c-b051ae69dd3a
TreatmentBank: https://tb.plazi.org/GgServer/summary/FFF5FFFC252E1B76FFB92925FF9AFFAE
