### ISSUE TITLE
errors in treatments

### ISSUE THREAD

**Issue by myrmoteras** [plazi/community#34]
genus name split: http://treatment.plazi.org/id/F4A56930A8FB03130B0D3D7A8C7EBD9F

**Comment by mguidoti** [comment]
Hi Donat,

This is a Pensoft journal. Can we manually fix this or should we ask them?

**Comment by myrmoteras** [comment]
yes, use GGeditor. This is easier fixed than writing emails.  If errors occure more often, then we need to write an issue in plazi/communication adressing pensoft

If fixed it
