### ISSUE TITLE
wrong classification changes an Orthopteran species into a weevil

### ISSUE THREAD

**Issue by DianRHR** [plazi/community#340]
Some orthopteran species included in this [dataset ](https://www.checklistbank.org/dataset/48327/classification?taxonKey=xB)are wrongly placed under Curculionidae
![image](https://github.com/user-attachments/assets/d1d0e793-8a1b-4703-a89e-a49446a9981e)

**Comment by flsimoes** [comment]
This is fixed now. Thanks for reporting!

TreatmentBank: https://tb.plazi.org/GgServer/summary/FFE52769A7368917FF9EFF84FFEEFFC3
GBIF: https://www.gbif.org/dataset/7015276f-bef6-45a0-9a1a-378cea75e186

**Comment by DianRHR** [comment]
Thanks @flsimoes I see that Conocephalus (and its species) are still below Coleoptera in the [gbif dataset](https://www.gbif.org/dataset/7015276f-bef6-45a0-9a1a-378cea75e186)

 ![image](https://github.com/user-attachments/assets/d8311bbd-7de2-46a8-881d-ad3b486a4f92)

**Comment by flsimoes** [comment]
@DianRHR sorry, that was indeed true
I've fixed it now
