### ISSUE TITLE
Foraminifera sneaked in bryophytes classification

### ISSUE THREAD

**Issue by camiplata** [plazi/community#341]
https://tb.plazi.org/GgServer/summary/2B7C0C49971BFFEBFFAD13517A77FFF8

Pohlia cruda (Hedw.) Lindb.: https://tb.plazi.org/GgServer/html/D7457431971EFFEEFFC017567B50FA93

<img width="691" alt="Captura de pantalla 2024-11-04 a la(s) 9 47 30 p m" src="https://github.com/user-attachments/assets/3135c3ba-71a6-48d7-9113-81b2d55e1c66">

**Comment by diegojalvares** [comment]
I corrected the higher taxonomy of the taxon, unfortunately, only the attributes Kingdom and Phylum are available in the paper.

**Comment by camiplata** [comment]
thanks!
