### ISSUE TITLE
Improve authorships - FFEBFFDAFD093704FE60FFB5FF9CFFC5

### ISSUE THREAD

**Issue by camiplata** [plazi/community#344]
https://treatment.plazi.org/GgServer/summary/FFEBFFDAFD093704FE60FFB5FF9CFFC5

Would it be possible to recover the authorship for genus Hoplitomeryx  and its related species? for Plazi and the data export to COL

And fix the authorships of the genus  Scontromeryx and related species, for the data export to COL as they show up as duplicated info.

<img width="953" alt="Captura de pantalla 2024-11-05 a la(s) 4 50 14 a m" src="https://github.com/user-attachments/assets/9b7df578-6c71-4129-b202-6531b22ac45d">

**Comment by diegojalvares** [comment]
Fixed
