### ISSUE TITLE
Species and subspecies epithets more than once in some names

### ISSUE THREAD

**Issue by DianRHR** [plazi/community#345]
Several names included in this [treatment ](https://treatment.plazi.org/GgServer/summary/121F1F1CFFA42575FF9CFF8BEC0FFFDD)have the species or subspecies epithet more than once. 

The dataset in ChecklistBank therefore has the same problem , so it makes conflict when trying to merge the name into the xRelease, as it is detected as "unparsable name" 

![image](https://github.com/user-attachments/assets/1cb6419d-8cc0-4406-8316-01dcd564b90d)

**Comment by diegojalvares** [comment]
Fixed
