### ISSUE TITLE
Treatment "Monteithocanthon elliotensis Gunter & Weir, new species"

### ISSUE THREAD

**Issue by dshorthouse** [plazi/community#346]
The following material:

[19°29'00''S, 146°57'00"E], Mount Elliot North Creek, 25–27 March 1991, 1000 m, G. Monteith and D. Cook, pitfall and dung traps (in QM 53830– 34 4x ♂, in ANIC 25-065497  2x ♂ (also as T53828– 9)

...was somehow interpreted and then shared to GBIF with a dwc:eventDate of 1934-10-04, which is 8 years before the collector's date of birth. This looks to be the specimen record: https://www.gbif.org/occurrence/2446103758.

**Context**
Treatment: Monteithocanthon elliotensis Gunter & Weir, new species - 03C887A8FFD0FFDAFF737E7B5B02B5FF - [go to page](https://treatment.plazi.org/id/03C887A8FFD0FFDAFF737E7B5B02B5FF)
Document: zootaxa.4290.2.1.pdf - FFF1FFD0FFCBFFC7FFE47F3A5F6FB348 - [go to summary](https://publication.plazi.org/id/FFF1FFD0FFCBFFC7FFE47F3A5F6FB348)

**Comment by JonasBlanco** [comment]
Hi!

I just fixed it. It shall update soon in the databases.

Kind regards,
Jonas
