### ISSUE TITLE
Crotalaria is not a Hymenopteran genus

### ISSUE THREAD

**Issue by DianRHR** [plazi/community#347]
This [dataset ](https://www.checklistbank.org/dataset/33138/classification?taxonKey=xJ)and [Treatment ](https://tb.plazi.org/GgServer/summary/FFB0FFA5F03D481DFF8A0D2EFFA3FFDC)include "Crotalaria" as a Hymenoptera genus, which is wrong as the aticle mentions that species of the genus Megachile feed on Fabaceae plants like Crotalaria. Therefore, Crotalaria shouln't be included in the dataset or it shoulb be included as a Plant with its proper higher classification. 

![image](https://github.com/user-attachments/assets/6506f480-ec36-41b2-992b-33ce5593bf55)

**Comment by valdenar** [comment]
Hi @DianRHR 
I have made corrections to the taxonomicNames attributes. An update should be available soon.
Thank you for contacting us regarding this issue.
