### ISSUE TITLE
Plants pretending to be insects - Myrtaceae from lowland Atlantic Forest

### ISSUE THREAD

**Issue by camiplata** [plazi/community#350]
Wrong Insect classification for Plant treatments Eugenia and Plinia genera, 
https://tb.plazi.org/GgServer/summary/D902FFBBFF942E345C486C19303FFFD6

<img width="500" alt="Captura de pantalla 2024-11-20 a la(s) 3 14 26 p m" src="https://github.com/user-attachments/assets/d0757f27-065e-41f0-848c-09a14afa1a87">

https://www.checklistbank.org/dataset/6131/classification?taxonKey=x3M

**Comment by valdenar** [comment]
Hi @camiplata 
I have made corrections to the taxonomicNames attributes. An update should be available soon.
Thank you for contacting us regarding this issue.
