### ISSUE TITLE
Wrong classification - The typification of Cordia flavescens

### ISSUE THREAD

**Issue by camiplata** [plazi/community#351]
Another Plant with identity crisis, Cordia is not an insect, this treatment has a particular mix of plant/insect classification
https://treatment.plazi.org/id/F3C4D982A5B4F601A9EC02B86DA0DF16

<img width="711" alt="Captura de pantalla 2024-11-20 a la(s) 3 30 23 p m" src="https://github.com/user-attachments/assets/7d259491-3d87-488c-bc98-7dd8fb2e0b1e">

https://www.checklistbank.org/dataset/34684/classification

The DwC-A also has an issue as the Family is documented along the authorship

<img width="727" alt="Captura de pantalla 2024-11-20 a la(s) 3 31 25 p m" src="https://github.com/user-attachments/assets/4efe9515-8678-4cf2-9264-c3de7a061720">

**Comment by valdenar** [comment]
Hi @camiplata
I have made corrections to the taxonomicNames attributes. An update should be available soon.

**Comment by camiplata** [comment]
THANKS
