### ISSUE TITLE
Genus of Siphonaptera and Acari are mixed some placed in the wrong group

### ISSUE THREAD

**Issue by DianRHR** [plazi/community#353]
This [dataset ](https://www.checklistbank.org/dataset/305209/about) includes genus and species of both Acari and Psocodea, however, some of them are placed in the wrong genus. 
Example: [Pediculus ](https://www.checklistbank.org/dataset/305209/taxon/K9CBL)Linnaeus, 1758 is a lice but it's wrongly placed in Acari, family Chaetodactylidae. 

All genus need to be checked and corrected.
![image](https://github.com/user-attachments/assets/f406951a-73f0-482b-9036-c5ea1ff656fb)

**Comment by jugiora** [comment]
Hi, @DianRHR 
I have made corrections to the taxonomicNames attributes. An update should be available soon.  
Thank you for contacting us regarding this issue.
