### ISSUE TITLE
wrong authorship format -  FC57DA714471C03B1FCFD537EC134736

### ISSUE THREAD

**Issue by camiplata** [plazi/community#354]
https://treatment.plazi.org/id/FC57DA714471C03B1FCFD537EC134736

<img width="1058" alt="Captura de pantalla 2024-11-28 a la(s) 11 23 10 a m" src="https://github.com/user-attachments/assets/568c0177-11da-486e-b8b7-87bb756d494a">

**Comment by jugiora** [comment]
Hi, @camiplata  
I have made corrections to the authority attributes. An update should be available soon.  
Thank you for contacting us regarding this issue.

**Comment by camiplata** [comment]
Thanks Julia!
