### ISSUE TITLE
Treatment "Liparis loeselii (L.) Rich. 1817"

### ISSUE THREAD

**Issue by CecSve** [plazi/community#355]
The higher taxonomy for this orchid has been assigned to Animalia and beetles. Reported by user in GBIF's portal feedback system: https://github.com/gbif/backbone-feedback/issues/567

**Context**
Treatment: Liparis loeselii (L.) Rich. 1817 - 03E787D7FFEE222D999AFB94FE47F9A6 - [go to page](https://treatment.plazi.org/id/03E787D7FFEE222D999AFB94FE47F9A6)
Document: Flora_des_Sihltals_Publ_Orchidaceae_only.pdf - FFDEFFAFFFE322209930FFD6FFF0FF9C - [go to summary](https://publication.plazi.org/id/FFDEFFAFFFE322209930FFD6FFF0FF9C)
GBIF: https://www.gbif.org/species/11712270/treatments

**Comment by guilhermepcoelho** [comment]
Hello @CecSve 

I have fixed all names wrongly assigned to Animalia in this paper. They are correct in TreatmentBank now and soon they should be correct is GBIF as well.

Best regards.
