### ISSUE TITLE
Lepidoptera as Beetle  DD5CFF980D2CFF95EF53F17D3063FFFE

### ISSUE THREAD

**Issue by camiplata** [plazi/community#356]
Please update the classification of the dataset's treatments to reflect the correct taxonomy

https://treatment.plazi.org/GgServer/summary/DD5CFF980D2CFF95EF53F17D3063FFFE

<img width="920" alt="Captura de pantalla 2024-12-27 a la(s) 8 00 08 a m" src="https://github.com/user-attachments/assets/a42b2af0-14a3-4fd8-a372-ddb533e15075" />

**Comment by flsimoes** [comment]
Updated to Lepidotera and Hepialidae
Thanks for reporting!
