### ISSUE TITLE
Incorrect classification, diatoms as molluscs  FFFBFFD2FFFC0B07FFD37D20FF9BFFCC

### ISSUE THREAD

**Issue by camiplata** [plazi/community#357]
Some treatments from "Lobban, Christopher S. & Witkowski, Andrzej, 2023, Marine benthic diatoms of Guam: new records, Dictyoneis apapae sp. nov., and updates to the checklist" were incorrectly classified as Molluscs.

https://treatment.plazi.org/GgServer/summary/FFFBFFD2FFFC0B07FFD37D20FF9BFFCC

<img width="921" alt="Captura de pantalla 2024-12-27 a la(s) 10 20 57 a m" src="https://github.com/user-attachments/assets/87685e4a-9210-471a-9094-ce4d3ba86c99" />

see for example: https://www.diatombase.org/aphia.php?p=taxdetails&id=162271

**Comment by flsimoes** [comment]
I've moved both _Actinocyclus_ and _Auricula_ to Chromista>Ochrophyta>Bacillariophyceae

Thanks for catching these
