### ISSUE TITLE
Incorrect classification, Lepidoptera, as beetles and protozoa FF9EFF84FFE9FFC2E336FFDBFF92232C

### ISSUE THREAD

**Issue by camiplata** [plazi/community#358]
https://treatment.plazi.org/GgServer/summary/FF9EFF84FFE9FFC2E336FFDBFF92232C

<img width="768" alt="Captura de pantalla 2024-12-27 a la(s) 10 42 51 a m" src="https://github.com/user-attachments/assets/bbc5d223-68ea-4c55-8372-1ee0d3fa168e" />

https://www.checklistbank.org/dataset/22939/classification?taxonKey=xJ

**Comment by flsimoes** [comment]
Fixed
Thanks for reporting!
