### ISSUE TITLE
Incorrect clasification Lepidopter as coleoptera  B716170FFF9FFFC906588A65FFD1FFE1

### ISSUE THREAD

**Issue by camiplata** [plazi/community#359]
https://tb.plazi.org/GgServer/summary/B716170FFF9FFFC906588A65FFD1FFE1

<img width="1053" alt="Captura de pantalla 2024-12-27 a la(s) 3 22 39 p m" src="https://github.com/user-attachments/assets/e994550f-9f80-4601-b261-ab8f651a2b2b" />

https://www.checklistbank.org/dataset/40504/classification

**Comment by flsimoes** [comment]
Fixed!
Thank you for catching these!
