### ISSUE TITLE
Multi-taxa treatments

### ISSUE THREAD

**Issue by flsimoes** [plazi/community#36]
Do we have a way of dealing with multi-taxa treatments? (such as the one in the example below)

![image](https://user-images.githubusercontent.com/3343086/81001117-a57f4a80-8e1d-11ea-80fb-ed4a9434fc1c.png)

I had asked a similar thing before, but I believe we haven't reached a conclusion about it: https://github.com/plazi/plazi-at-poa/issues/246

**Comment by myrmoteras** [comment]
no. probably just chose the first taxonomic name, since it is about it too. You can also leaf if on the side. 
I would just make it Metrocorini

**Comment by flsimoes** [comment]
Ok! Thanks!
