### ISSUE TITLE
Lepidoptera dataset with names under incorrect classifications, and missing tribe- child relationships

### ISSUE THREAD

**Issue by camiplata** [plazi/community#360]
https://tb.plazi.org/GgServer/summary/EA3DFF83FFCA5704A877194DC041FF80

<img width="741" alt="Captura de pantalla 2024-12-27 a la(s) 3 28 32 p m" src="https://github.com/user-attachments/assets/9f2a9bf1-93ad-48a6-ae94-b92c27b6622e" />

https://www.checklistbank.org/dataset/305230/classification

All species should be under   Lepidoptera > Erebidae > Arctiinae  and subsequent tribes, currently the classification does npot follow the original data and the tribes have no children

<img width="527" alt="Captura de pantalla 2024-12-27 a la(s) 3 32 06 p m" src="https://github.com/user-attachments/assets/4df3d704-96d8-438b-b227-c2e7f318696f" />

**Comment by flsimoes** [comment]
I've so far transfered the "Plants" to their correct classification and added the Tribes to treatment taxa up til _Baroa_ (in alphabetical order)

**Comment by flsimoes** [comment]
All fixed now
