### ISSUE TITLE
incorrect classification Mollusc under arthropoda FFAAFFB0FF8AA26AFFEFFF85FFEC690A

### ISSUE THREAD

**Issue by camiplata** [plazi/community#361]
https://treatment.plazi.org/GgServer/summary/FFAAFFB0FF8AA26AFFEFFF85FFEC690A

<img width="899" alt="Captura de pantalla 2024-12-27 a la(s) 3 52 37 p m" src="https://github.com/user-attachments/assets/09eb7a27-b6f6-444e-a258-75293579d01b" />

https://www.checklistbank.org/dataset/5612/classification

**Comment by flsimoes** [comment]
Fixed
Thanks for reporting!
