### ISSUE TITLE
analyse CLB higher taxonomy issues

### ISSUE THREAD

**Issue by myrmoteras** [plazi/community#363]
@flsimoes could you please analyse the higher taxa errors in https://github.com/plazi/community/issues/362 to  see whether there are patterns to lead to wrong higher taxa so we can try to avoide them in the future.

**Comment by flsimoes** [comment]
Of course
I even commented in that issue

**Comment by flsimoes** [comment]
For the record
Most of the reported cases are from older uploads, i.e. pre-gatekeeper (circa 2020) and the improved qc rulesets.

**Comment by myrmoteras** [comment]
> For the record Most of the reported cases are from older uploads, i.e. pre-gatekeeper (circa 2020) and the improved qc rulesets.

this I expected. It is important to know, because in this case it does not have an effect on our current processing of new data.

**Comment by myrmoteras** [comment]
> Of course I even commented in that issue

@flsimoes sorry, where did you comment? (i.e. what is the "that issue"?)

**Comment by flsimoes** [comment]
> > Of course I even commented in that issue
> 
> @flsimoes sorry, where did you comment? (i.e. what is the "that issue"?)

Sorry, was replying via mobile, so it was a bit trickier to get the links

That's what I meant
https://github.com/plazi/community/issues/362#issuecomment-2564600600

Yesterday I organized a task to fix these and we'll work on them next week onwards. Since there are 127 uploads with potential issues, it will take some extra hands.

**Comment by flsimoes** [comment]
> > For the record Most of the reported cases are from older uploads, i.e. pre-gatekeeper (circa 2020) and the improved qc rulesets.
> 
> this I expected. It is important to know, because in this case it does not have an effect on our current processing of new data.

Indeed + recently (post-Disentis) Guido implemented the changes discussed with Markus Doring, so higher taxonomy is now more faithful to what is presented in the publication.

That mostly leaves certain homonyms as the source of wrong parsing.
