### ISSUE TITLE
Zootaxa Monograph

### ISSUE THREAD

**Issue by Carol-Sokolowicz** [plazi/community#37]
Hi Donat,

Just to let you know that I've been working on this Zootaxa monograph:
zootaxa.4741.1.1
DOI: 10.11646/zootaxa.4741.1.1

I started working on it before I move to EJT backlog, but since it is a long catalog the treatments are tricky so I've been working a little bit every day.
As soon as I upload it I let you know.
Cheers,

**Comment by mguidoti** [comment]
@myrmoteras already did:
http://tb.plazi.org/GgServer/summary/B2762347FFFB8758FFE2CF34FFD7F267

Sorry for the wasted time and lost work, @Carol-Sokolowicz. I'm closing this issue now. 

Thanks,

**Comment by mguidoti** [comment]
I've got curious and checked this paper real quick. 

It says on the abstract that a total of 600 treatments were included (at least, there are some incertae sedis within the text). 

![image](https://user-images.githubusercontent.com/44419136/82606882-3419f880-9b8e-11ea-9f2f-d0730792883a.png)

Only 122 treatments were extracted:
![image](https://user-images.githubusercontent.com/44419136/82606946-4dbb4000-9b8e-11ea-9608-771d152929e8.png)

Within the text, it's fast to find some missing treatments:
![image](https://user-images.githubusercontent.com/44419136/82606967-590e6b80-9b8e-11ea-9da5-6701560134d2.png)

And there are a lot of 'species group' treatments as well:
![image](https://user-images.githubusercontent.com/44419136/82607023-704d5900-9b8e-11ea-9807-ef0c85641719.png)

For example, from page 42 to page 52, nothing was marked. 

@myrmoteras should we do anything about this or leave it as it is?

Thanks for your input,

**Comment by myrmoteras** [comment]
Lets ask Guido, whether he can do something about it, i.e. under stand why this happened.

**Comment by myrmoteras** [comment]
Lets ask Guido, whether he can do something about it, i.e. under stand why this happened.

**Comment by mguidoti** [comment]
@myrmoteras @Carol-Sokolowicz do we have any follow up on this?

**Comment by Carol-Sokolowicz** [comment]
This has been already uploaded 

B2762347FFFB8758FFE2CF34FFD7F267

**Comment by flsimoes** [comment]
I just reopened this issue as it was never solved.

Just a recap:

- Carolina worked on the monograph, but it was uploaded by Donat in the meantime.
- Donat suggested we check with Guido to see whether he could do anything about it.
- Later on Carolina closed the issue, commenting that the document had already been uploaded (but not updated), which was not new information (see first bullet-point), hence why I am reopening, as it still remains to be corrected.

**Comment by flsimoes** [comment]
@truschel just finished correcting everything again! Thanks a lot for this!

**Comment by myrmoteras** [comment]
this is quiet something: from 122 to 720 treatments.
@truschel doing this gargantuan task: Do you have any suggestions to improve GGI to discover more treatments'

Thanks for this effort

**Comment by truschel** [comment]
Hi @myrmoteras 
In the case of this monograph, the possible heading and nomenclature section of treatment are with other words in the same  line and a broken inside the line was necessary for separe the subSubSections. I believe we need to check the function of taking treatments with other words along the same line of the heading.

**Comment by flsimoes** [comment]
Closing this one as there doesn't seem to be more to be discussed

**Comment by mguidoti** [comment]
Why aren't we considering to move these issues into Discussions, select the right answer if one exist, and create this backlog of Q/A so a new user can come in and research before ask a new one (ideally), or even us, to find something that we know we discussed before?

**Comment by myrmoteras** [comment]
Somewhere we have an issue about informal taxonomic ranks - more recently with the Lasius revision. We need to followup on this. Need to check
