### ISSUE TITLE
Is it a treatment stub or not?

### ISSUE THREAD

**Issue by Carol-Sokolowicz** [plazi/community#39]
Hi Donat,
I was looking if this EJT papes was already uploaded and I couldn't find it on the TB Stats but different from other EJT papers it is not on TB as a treatment stub, but I also couldn't open the UUID.

![image](https://user-images.githubusercontent.com/57491712/81214249-f2922680-8fad-11ea-8ce5-e2d548321dfe.png)

23ED16FEE6AA40B4B55EA2C31CB86A22

It is a stub after all, should I process it?

**Comment by myrmoteras** [comment]
if it is a stub, then you need to process the article to resolve the stub

**Comment by Carol-Sokolowicz** [comment]
Ok! Thanks!
