### ISSUE TITLE
When should Keys be their own treatment?

### ISSUE THREAD

**Issue by flsimoes** [plazi/community#41]
@myrmoteras

In situations such as the one below, should the `key` be its own treatment? Or should it simply be a `subSubsection = key` of the preceding "main" treatment?

![image](https://user-images.githubusercontent.com/3343086/82909223-5c637780-9f3f-11ea-83c8-935fdee5e1c7.png)

I was under the impression that these should be separate treatments (even if they deal with the same taxon).

**Comment by flsimoes** [comment]
Just to help the discussion, this is an example where the key needs to be part of the preceding treatment:

![image](https://user-images.githubusercontent.com/3343086/82913603-e2ce8800-9f44-11ea-9580-4c9d9ea6c5c4.png)

**Comment by flsimoes** [comment]
And what about keys like this one? Should we split treatments?

![image](https://user-images.githubusercontent.com/3343086/82927559-4366c080-9f57-11ea-929b-69abdd5c055f.png)

**Comment by flsimoes** [comment]
@myrmoteras @mguidoti @truschel @valdenar @Carol-Sokolowicz 

With the uncertainty raised by this question, we are at a risk of creating several spurious treatments OR partly missing them, as it is not clear to me which are the correct ways to deal with them.

I find it to be a fairly urgent matter in which we need to, at least, find common ground.

**Comment by truschel** [comment]
Hi Donat @myrmoteras 

I have seven Adansonia papers ready for upload but I would like to know the answer before.

**Comment by myrmoteras** [comment]
The rule for keys is:
* If the key is part of a higher taxon treatment, then keep it in the higher taxon treatment.
* If the key is part of a higher taxon treatment, but separated by other treatments (eg all the species level treatment), then make it a separate treatment.
* if it is only a key, then it is a treatment of itself.

**Comment by flsimoes** [comment]
Thank you very much Donat!

**Comment by flsimoes** [comment]
@myrmoteras @mguidoti 

Even though this question has been already answered, now I have a different take on the subject.

As Donat said:

> The rule for keys is:
> * If the key is part of a higher taxon treatment, then keep it in the higher taxon treatment.
> * If the key is part of a higher taxon treatment, but separated by other treatments (eg all the species level treatment), then make it a separate treatment.
> * if it is only a key, then it is a treatment of itself.

That is fine... for when we do manual corrections. This won't work for templates and there's a simple reason for that.

As we know, when we set up a template we have to tell GGI to mark groups of `headings 2` to then acquire the `treatments`. With that in mind, we would then want GGI to recognize headings such as this one:

![image](https://user-images.githubusercontent.com/3343086/85866797-56f78800-b79e-11ea-8464-b9157d0fa700.png)

As stated above we want the template to mark this heading for when the key is separate from its "main" `treatment`. However, this will also mark them as treatments when the key is immediately after its "main" `treatment`.

My point is: **template-wise** (under an automated process) it is impossible to follow these guidelines. Having the template mark all keys as individual treatments seems to be the only way it will work.

**Comment by mguidoti** [comment]
Well, that will depend on the heading style of the keys, which is layout-dependent and journal-specific.

But my view is that keys should always be separated treatments as they are elements of the taxonomic paper that can (and should) be cited independently if used.

**Comment by flsimoes** [comment]
> Well, that will depend on the heading style of the keys, which is layout-dependent and journal-specific.
> 
> But my view is that keys should always be separated treatments as they are elements of the taxonomic paper that can (and should) be cited independently if used.

I agree with you.
