### ISSUE TITLE
Images with no captions

### ISSUE THREAD

**Issue by Carol-Sokolowicz** [plazi/community#42]
Hi Donat,
I have this EJT monograph and the images of a entire page were all marked as one figure and the captions were not marked because GGI did not recognize as text.
Should I split the figures and mark the captions as in-line captions?
Just so you know it is over 500 images.
So let me know how to proceed since it would take a lot o time.

![image](https://user-images.githubusercontent.com/57491712/82938077-a19b9f80-9f67-11ea-91f0-5ada2e2a54b4.png)

**Comment by mguidoti** [comment]
@Carol-Sokolowicz could you please provide the number or, even better, the link to the PDF and IMFs?

Thanks

**Comment by myrmoteras** [comment]
which ejt is this?
Are these things cited in the treatment?

**Comment by Carol-Sokolowicz** [comment]
This is ejt-2017-346. The images are at the end of the monograph, after references. Are distribution maps of the species.
Here is the IMF file https://drive.google.com/open?id=17MfGiU6Ohnxk5LQjdF9OI6Ebk2A4vC5B

**Comment by myrmoteras** [comment]
https://github.com/plazi/ggi/issues/62 I hope Guido has an idea. 

It would be an intersting case, because these maps are often used....

**Comment by Carol-Sokolowicz** [comment]
Ok, I'll finish the rest of the fixing and then wait for his ideas.

**Comment by Carol-Sokolowicz** [comment]
This has been uploaded as it was as Donat suggested [here](https://github.com/plazi/ggi/issues/62)
