### ISSUE TITLE
treatment at subfamily instead at species level Zootaxa.1622

### ISSUE THREAD

**Issue by myrmoteras** [plazi/community#43]
http://tb.plazi.org/GgServer/html/03C2878BFFDCFFE7F3D4D5213403FADD

http://tb.plazi.org/GgServer/summary/FFFBFFF3FFC6FFC2F343D6263625FFB2

**Comment by mguidoti** [comment]
@truschel could you please check this?

Thanks

**Comment by truschel** [comment]
@myrmoteras @mguidoti it is done.
