### ISSUE TITLE
How should we designated a supplementum paper in a template?

### ISSUE THREAD

**Issue by truschel** [plazi/community#44]
Hi Donat

I'm working on a template just for the monographs of Acta Entomologica Musei Nationalis Pragae. These monographs are part of a volume that does not contain an issue, but is designated as "supplementum".

![image](https://user-images.githubusercontent.com/57402704/87708042-7d468d00-c778-11ea-8793-34feb46cbd8b.png)
![image](https://user-images.githubusercontent.com/57402704/87708063-8899b880-c778-11ea-80fa-586935d5d4c1.png)

How should I do for the template? Should I put it as the issue of journal?

**Comment by gsautter** [comment]
Just make it volume 56 ... it's all just document attributes (which we can change should the need arise) ... in general, such questions might best be answered based upon how this specific document would be _cited_ downstream ... if we have all the attributes that allow unambiguous resolution of a reference, we're all set.

**Comment by mguidoti** [comment]
I think that's one of the cases were they restart the pagination in this special issue, suppl. 

So, you have **`56(1): 1-?`** and **`56(suppl.): 1-?`**.

Lacking this 'suppl.' might hamper the resolving to the right reference, no?

**Comment by mguidoti** [comment]
Links for reference:

https://www.aemnp.eu/acta-entomologica/volume-57-1/
https://www.aemnp.eu/acta-entomologica/volume-57-s/

**Comment by gsautter** [comment]
> Lacking this 'suppl.' might hamper the resolving to the right reference, no?

Well, one question is how often this happens ... and the other question is if the title and authors are also the same as for the article starting at page 1 ... if the latter isn't the case, resolution should still work, and the former (unless the answer is "this happens quite frequently") might suggest we should not invest all too much effort in resolving this ...
What would you want to resolve it _to_, anyway? I mean, as a taxonomist, how would you reference this specific paper in a bibliography? Maybe we can go by that ...

**Comment by mguidoti** [comment]
Ok, 

So, I would say, definitely NOT frequent. But some journals still use this. It's hard to give you a number. What I can say is that we will encounter this in other journals as well.

Having all the other info (same authors, same title, exact same pagination) would be an extreme case of bad luck. So I do believe that, using the rest, we can resolve to the right reference.

As a taxonomist, or a scientist for that matter, I think the goal is to resolve to the right reference, right?

**Comment by gsautter** [comment]
> As a taxonomist, or a scientist for that matter, I think the goal is to resolve to the right reference, right?

Sure ... the question is a different one, however: If you were authoring a paper, how would you reference such a supplement in your bibliography?

The latter is about what we'll have to work with on the referencing side when we resolve a reference ...

**Comment by mguidoti** [comment]
Definitely **`56(suppl.): 1-?`**.

Others might have a different vision? @myrmoteras @truschel @flsimoes

**Comment by gsautter** [comment]
OK, now RefParse pretty much ignores the "(suppl.)" as well, simply because it's (as you said) relatively rare ... and into what attribute would this additional qualifier go? It's not a volume or issue number, is it?

Also, there might be multiple supplements to the same journal volume/issue ... how would they be distinguished?

**Comment by mguidoti** [comment]
It's not a number, but it's the issue identifier, just like issue 1 or 2.

To distinguish them while citing: `56(suppl. 1): 1-?`, `56(suppl. 2): 1-?`.

I guess we always thought about issue number as, well, number, right? However, we can have letters on this issue identifier (but not on volume, at least, not that I'm aware of). So perhaps that, if we decide that this is relevant enough to worth the trouble, we should consider changing the logic behind issue number to something like issue identifier, accepting other characters than [0-9]? 

Just thinking out loud here.

Thanks for looking into it.

**Comment by gsautter** [comment]
The thing is that some journals just use an issue number, but no volume number at all ... and in those cases, it has to be a number ... spent some good three hours discussing things like this with Terry when designing RefParse back in 2011 ...

Anyway, what would the issue number be in that case? "s1", "s2", etc., maybe? Obviously, there are multiple ways of spelling out or abbreviating "supplement", so we need to normalize ... nice little can of worms we've opened here ...

**Comment by mguidoti** [comment]
So what about asking Terry's input on this particular thing, now that the can is open, before actually doing something?

**Comment by flsimoes** [comment]
The main problem in the particular example shown here is that the journal has the following issues:
56 (1)
56 (2)
56 (suppl. 1)
56 (suppl. 2)

Pagination is sequential in each individual issue, meaning that 56(1) starts at pp. 1-??, 56(suppl.) 1-??, and so on

**Comment by mguidoti** [comment]
Not true... pagination on 56(2) starts where the 56(1) ends. As I said, it restarts only on supplements.

But Guido is interested in knowing how we would cite this in our papers...

**Comment by flsimoes** [comment]
Actually, what I wrote is true (I didn't mention 56(2)). Anyways... not relevant

**Comment by flsimoes** [comment]
Here's another example from The Coleopterists Bulletin.

In this case they have a special issue number for Monographs.

https://drive.google.com/open?id=1uM0alXBN4cNCsTg_ZnP--KV12RBcsOW5

![image](https://user-images.githubusercontent.com/3343086/96022105-c0bba080-0e26-11eb-948c-b72d5b446814.png)

**Comment by flsimoes** [comment]
And another one

https://www.biotaxa.org/pja/article/view/2020111/59768
![image](https://user-images.githubusercontent.com/3343086/96033196-282d1c80-0e36-11eb-95c6-5a46c249abfd.png)

**Comment by gsautter** [comment]
Maybe we need a special qualifier for this ... in quite some references, people append " (Supplement)" to the journal name, but doing so in the metadata will hamper downstream aggregation, etc. ... an additional field for "Series (Journal)" or "Series within Journal" ("Journal Series" implies too much of "Series of Journals" imho) might solve this, if with some additional effort (implementation on my end, updating templates on your end) ,,,

**Comment by mguidoti** [comment]
As this shows up more frequently than I would like to admit, I think we have to eventually add it.

From our point of view... the additional work in updating templates is totally worth it. But again, I won't draw any comments on how this piles up in your list of priorities... 

Sorry for asking one more feature!

**Comment by gsautter** [comment]
Comes with next update ... which will also comprise the new template infrastructure.

**Comment by flsimoes** [comment]
Thanks a lot for both updates Guido!
