### ISSUE TITLE
One specimen has 70 collectors - GBIF

### ISSUE THREAD

**Issue by ManonGros** [plazi/community#47]
This is another issue that was reported via the GBIF portal feedback: https://github.com/gbif/portal-feedback/issues/2487
 One of our users noticed that one specimen was recorded by 70 collectors. The dataset concerned is the following : https://doi.org/10.11646/zootaxa.4732.1.1

PS: you can check all the issues opened on our portal associated with the PLAZI organisation key with the following link: https://github.com/gbif/portal-feedback/issues?q=is%3Aissue+is%3Aopen+7ce8aef0-9e92-11dc-8738-b8a03c50a862

**Comment by myrmoteras** [comment]
hi POA team 
this is too big to handle for me - but at the same time very rich in data http://treatment.plazi.org/GgServer/summary/FFDA7568FFA5FFC7FFE0FF80FFE76311

It might be also interesting to understand why we get 70 collectors.

Shorthouse who discovered the error points our that we actually feed into Bionomia - another outlet of for Plazi mediated data

tx for looking into this

donat

**Comment by mguidoti** [comment]
Hi @ManonGros, we will sort these out this week. Thanks for the link!

@myrmoteras I'll save a copy of this IMF and send it to Guido, so he can investigate what went wrong, but we'll try to fix it as soon as possible.

**Comment by gsautter** [comment]
You sure this is the right document? The occurrence listed in the original GBIF ticket is https://www.gbif.org/occurrence/2572159687 with taxon "Phyllomyza nitens Loew, 1869", linked to treatment http://treatment.plazi.org/id/03B187B7FFBBFFF3FF3AFDEFC7F8A1E8 (which Tatiana edited today) from document http://treatment.plazi.org/GgServer/summary/FF88FFCFFFBFFFFBFFADFF93C656A063 ...

**Comment by gsautter** [comment]
No problem you didn't retain a copy before fixing, we have versioning on all documents ... plus, I can also look at past versions of the treatment ... here the uncorrected version: http://treatment.plazi.org/GgServer/xml/03B187B7FFBBFFF3FF3AFDEFC7F8A1E8/7

My only idea how this could have happened is that some large materials citation was split up manually during QC, but the attributes remained unchanged ... that list of "collector names" seems to contain but every proper name from the start of the first of these materials citations up to the end of its parent paragraph ...

**Comment by gsautter** [comment]
Should we add a QC rule checking for the number of collector names? Maybe report anything above 2 or 3?

**Comment by mguidoti** [comment]
I think it's sensible to have this additional QC rule... it's not something that we will see that often and, in these cases, it's better to have false positives than bad data.

Thanks, Guido!

**Comment by truschel** [comment]
The collector names were fixed.
