### ISSUE TITLE
chart maker; does not work

### ISSUE THREAD

**Issue by myrmoteras** [plazi/community#49]
Hi!

I’ve been trying to access the chart maker for a while now, but never seem to manage on http://plazi.cs.umb.edu/GgServer/srsStatCharts . Is this tool still available? I suppose I could try and use the API to get the same functions, but it would be much easier to use the chart maker given that it seems to have everything I need.

Many thanks, by the way, for the amazing services Plazi offers!

All the best,

Stijn Conix
Postdoctoral Research Fellow
CLPS, KU Leuven
www.stijnconix.info

**Comment by myrmoteras** [comment]
Hi Stijn
Thanks for your interest in this. I will let my colleagues answer, CCed @gsautter
Keep me posted whether it works.
As a caution: I am not sure whether this functionality has been kept up with the expansion of the stats. We will hear from Guido.
All the best
Donat

email sent to Guido

**Comment by myrmoteras** [comment]
We might want to keep an eye on this - definitely a good tool, it we get it to work again

**Comment by mguidoti** [comment]
I envisioned this tool as part of the BLR website, and I think I might even have written this somewhere in the BLR repo.

It's definitely a good service to the community.

**Comment by flsimoes** [comment]
Closing this issue as it is stale, and likely not relevant anymore
