### ISSUE TITLE
Syninclusions

### ISSUE THREAD

**Issue by flsimoes** [plazi/community#50]
Hi @myrmoteras 

Have you seen syninclusions on papers before? This is a fossil term, which I'm not familiar with (apparently it means co-occurrences of multiple individuals). Also not sure how that would work out for holotypes.

![image](https://user-images.githubusercontent.com/3343086/100629082-a91d7600-3307-11eb-9cdb-dd1fc8952f02.png)

This screenshot is from Zoosystema's last issue (Zoosystema.42.29.583-592) which I'm just about to upload.

**Comment by myrmoteras** [comment]
I would just ignore for the moment and proceed. You can keep it somewhere as a note for curiosa for a locaton and format of MC

**Comment by flsimoes** [comment]
> I would just ignore for the moment and proceed. You can keep it somewhere as a note for curiosa for a locaton and format of MC

Will do! Thanks!

**Comment by mguidoti** [comment]
That's interesting, though. 

And the way they presented these material citations wouldn't quite allow to extract all of the specimen code and reuse the distributional info anyways...

**Comment by flsimoes** [comment]
Just to register another example: FFC5526AFF8EFFA01827FF91FFE9FFB3
