### ISSUE TITLE
corrections of previous wrong identifications: (this publication must have errors: http://treatment.plazi.org/GgServer/summary/F4447C79460DFFCF7027FFF87D206A7C)

### ISSUE THREAD

**Issue by myrmoteras** [plazi/community#51]
This zootaxa article talks about new genera but has only the materials citation of a new species

http://treatment.plazi.org/GgServer/summary/F4447C79460DFFCF7027FFF87D206A7C

**Comment by flsimoes** [comment]
Not really. This is an erratum (hence why the title has the author's name as well).

![image](https://user-images.githubusercontent.com/3343086/102349745-90a59080-3f82-11eb-83f2-063375a2b241.png)

Anyway, I could see there were some QC errors to fix in this one.
