### ISSUE TITLE
MC processing error reported from GBIF

### ISSUE THREAD

**Issue by myrmoteras** [plazi/community#53]
Feedback from GBIF.org regarding: https://www.gbif.org/occurrence/2985226229

Looks like an explosion of catalog numbers here from the processing of a monograph's material citations.

**Comment by flsimoes** [comment]
Hi @myrmoteras 

What exactly needs to be done here from our side?

**Comment by myrmoteras** [comment]
@flsimoes  check whether the MC are properly processed. It seems that there are too many collection code in a treatment.
 something went wrong here 

![image](https://user-images.githubusercontent.com/4609956/105032550-3010e400-5a57-11eb-8534-6f5161b8412c.png)
http://treatment.plazi.org/id/03FB87A9FECCFEBEFE6D6F21FEAAFA37

and here the XML
http://treatment.plazi.org/GgServer/xml/03FB87A9FECCFEBEFE6D6F21FEAAFA37

**Comment by flsimoes** [comment]
We'll look into it! Thanks!

**Comment by flsimoes** [comment]
So, I cleaned the `collectionCodes` a bit, but to parse through all the `materialsCitations` would be quite a heavy task, as there are over 1800 of them. That will take significant time from anyone proceeding with such a task.

![image](https://user-images.githubusercontent.com/3343086/105050300-672dc800-5a4c-11eb-8662-bda987db27b3.png)

What should we do?

**Comment by myrmoteras** [comment]
let's have a look at this before we start doing this. Can we figure out, why we got this concoktion of tens of collection codes in stead of one? Since the annotation attribute for collectioncode are all wrong, we could also just delete them? This could be done using the editing tool in GGI

**Comment by myrmoteras** [comment]
@flsimoes actually, now it is not bad anymore. http://tb.plazi.org/GgServer/srsStats/stats?outputFields=doc.uuid+doc.articleUuid+matCit.collectionCode&groupingFields=doc.uuid+doc.articleUuid+matCit.collectionCode&FP-doc.articleUuid=FFC2FFD1FFE7FF85FFC06A3AFFC2FFC3&format=HTML
there are 1802 mc with 1304 with collection codes. None of them is so messed up, so it mus have been a local problem.

**Comment by myrmoteras** [comment]
actually, what David refers to are specimenCodes.... and this looks different
http://tb.plazi.org/GgServer/srsStats/stats?outputFields=doc.uuid+doc.articleUuid+matCit.id+matCit.verbatimMatCit+matCit.specimenCode&groupingFields=doc.uuid+doc.articleUuid+matCit.id+matCit.verbatimMatCit+matCit.specimenCode&FP-doc.articleUuid=FFC2FFD1FFE7FF85FFC06A3AFFC2FFC3&FP-matCit.specimenCode=0-&format=HTML

if you look at them, I would just delete annoation attributes for specimenCodes, because almost all are wrong, and few have a specimenCode at all. Why this happened?

**Comment by flsimoes** [comment]
> actually, what David refers to are specimenCodes.... and this looks different
> http://tb.plazi.org/GgServer/srsStats/stats?outputFields=doc.uuid+doc.articleUuid+matCit.id+matCit.verbatimMatCit+matCit.specimenCode&groupingFields=doc.uuid+doc.articleUuid+matCit.id+matCit.verbatimMatCit+matCit.specimenCode&FP-doc.articleUuid=FFC2FFD1FFE7FF85FFC06A3AFFC2FFC3&FP-matCit.specimenCode=0-&format=HTML
> 
> if you look at them, I would just delete annoation attributes for specimenCodes, because almost all are wrong, and few have a specimenCode at all. Why this happened?

Sure
Removed all specimenCodes right now. Might take a few minutes before it updates on TB

The most likely reason for this to happen, as far as I could tell, is that the authors had a Capital Letter + Numbers pattern for their collecting methods (or transects, not sure) which are very similar to what GGI would recognize as a specimenCode (such as MNHN-000123).

**Comment by myrmoteras** [comment]
the question still is, why they have been inherited to almost all of them?!

**Comment by flsimoes** [comment]
Hard to know. This pattern sometimes happens with collectors' names.

It may be a product of originally having a very long materialsCitation where we manually split the annotation, and as a consequence the parameters are kept for all of them.

**Comment by flsimoes** [comment]
Stale issue.
