### ISSUE TITLE
fix GBIF records

### ISSUE THREAD

**Issue by myrmoteras** [plazi/community#55]
@mguidoti @flsimoes 
here is an open issue in GBIF to be resolved.

https://github.com/plazi/community/issues/45

https://github.com/gbif/portal-feedback/issues/2420

Let's find a strategy forwards how this could be solved automatically, and at the same avoided upon creation

**Comment by flsimoes** [comment]
What do you understand by solving it automatically? (just so we are in the same page)

Regarding avoiding it upon creation, I understand that this would have more to do with perhaps adapting Guido's library for Country names and Collection names (both of which we have seen examples of spurious annotations). To be honest, I'm not entirely sure how these are fetched.

**Comment by myrmoteras** [comment]
> What do you understand by solving it automatically? 
That means that Guido runs a script on server side to replace something in all the documents or part of.

> Regarding avoiding it upon creation
that means analysing the errors and to figure out how it could be avoided so GGI gizmos can be enhanced to omit this false positives.

**Comment by flsimoes** [comment]
Thanks!

I guess both solutions, whatever we come up with, will feed off each other in the end, as there will mostly be clear (or semi-clear) patterns.
