### ISSUE TITLE
sreencast request:  combinging images

### ISSUE THREAD

**Issue by myrmoteras** [plazi/community#56]
Might it be possible, once Jeremy can master combining  split images into , to create a screencast, so we can teach others how to use the tool?

https://github.com/plazi/ggi/issues/128#issuecomment-763984329

It is especially relevant for papers that include long phylogenies like this one: https://zenodo.org/record/4451923#.YAi66ehKiPo

**Comment by mguidoti** [comment]
Absolutely. 

Our screencast master is in vacation time (@valdenar) but I'll leave a task to him in ClickUp when he comes back. 

Plus, @valdenar, don't forget to reply with the link of the screencast here, once it's done.

**Comment by myrmoteras** [comment]
@valdenar please get in touch with Jeremy Miller who is pushing this for his work: https://github.com/plazi/ggi/issues/128#issuecomment-764482828. Once he can do what he want,s then its time to screencast

**Comment by valdenar** [comment]
individual screencast produced for "combining images". Link for review:
https://youtu.be/IfF5fKUX8Gg
