### ISSUE TITLE
Text flow

### ISSUE THREAD

**Issue by millerjeremya** [plazi/community#57]
I'm struggling with text flow. Maybe some of you have a more successful approach. 
In this particular case, I am editing a page in a sub window, and have rotated it 90 degrees clockwise. This makes the text of a figure captions I am working on read horizontally. The caption text occupies two lines, and the text stream currently connects the first word in each line as successors, and subsequently bounces between the lines as you move along the page. The objective here is to reorder the text in the intended word order. 
The semi-automated approach using Order stream doesn't help here, at least as I have attempted it. 

I've tried cutting and re-linking the words (successor/predecessor), but I eventually get to this (or a similar) prompt:
Cannot Set Predecessor...They belong to the same logical text stream...
![image](https://user-images.githubusercontent.com/4322250/105483525-42cf2700-5caa-11eb-8f7e-c0c44d063b94.png)
From this point, I'm stuck.
Thanks in advance for your advice. 

Here is the page in question displayed in a sub window and rotated 90 degrees
Source document: http://tb.plazi.org/GgServer/summary/6603FFA80B5D0D64FFF6AB533D39FF9A (Figure 2)
![image](https://user-images.githubusercontent.com/4322250/105482299-79a43d80-5ca8-11eb-8be3-f68d7e19a8e3.png)

**Comment by flsimoes** [comment]
Hi @millerjeremya 

From what I can see, there's some word relation problems within your text flow which might be the cause of the problems.

As you can see here, through the green visual cue, is that the caption is starting and ending at the wrong part of the text, suggesting the problems I mentioned above.
![image](https://user-images.githubusercontent.com/3343086/105493370-14485080-5c98-11eb-85dc-453d884961db.png)

My suggestion for you is to first have `word flow` on in the Display Control, and also remove the caption annotation completely to start things off.

Now there are two options:

1. from the first word onwards disconnect all of them from each other (using `cut stream after` or `cut stream before`). Now you draw a bounding box around the whole caption and choose `Make Stream`. Check, visually, if everything seems ok, flowwise, paying extra attentions for artificial paragraph breaks (see example below). Finally, draw a bounding box around the caption and use the pink macro `Mark Caption`.

![image](https://user-images.githubusercontent.com/3343086/105494229-41e1c980-5c99-11eb-9441-4908b1a8b7dd.png)

2. from the first word onwards disconnect all of them from each other (using `cut stream after` or `cut stream before`). Now start connecting them in order (`Click Successor`). At the same time, check their relation (`Previous word relation` or `Next word relation`) and make sure they are all `Separate word`. Finally, draw a bounding box around the caption and use the pink macro `Mark Caption`.

I find the second option to be safer.

Please let me know if you need more help.

**Comment by millerjeremya** [comment]
Thanks a lot, that helps. I wondered if there were just a way to get rid of all the stream links at once; it's tedious and a little hard on the eyes to do it one at a time. But it's functional.

**Comment by flsimoes** [comment]
> Thanks a lot, that helps. I wondered if there were just a way to get rid of all the stream links at once; it's tedious and a little hard on the eyes to do it one at a time. But it's functional.

Not that I'm aware of.
You can try drawing a bounding box around the text and clicking "Order Stream", but I doubt it will help much in cases such as the one presented here.
