### ISSUE TITLE
Figure citations and captions

### ISSUE THREAD

**Issue by millerjeremya** [plazi/community#58]
Does anyone understand the use of fields like captionStart, subCaptionsStart in figureCitation and caption? 
Specifically, what controls the green link text in treatmentBank that points to cited figures? How to get it to consistently read something like "View Fig. 7", rather than "View Fig" or "View Figure"?
![image](https://user-images.githubusercontent.com/4322250/105599958-f6ace100-5d94-11eb-9957-b10763a3f8e0.png)

Also, is there any effect of having the captionText as part of the figureCitation? 
![image](https://user-images.githubusercontent.com/4322250/105602333-9ec2aa00-5d95-11eb-8d89-df215546d17f.png)
![image](https://user-images.githubusercontent.com/4322250/105602948-c9146780-5d95-11eb-8d4a-3cc92ad84e32.png)

**Comment by flsimoes** [comment]
I guess only Guido will know that. I have no clue as to why it is inconsistent.

**Comment by mguidoti** [comment]
I have to myself that the targetBox is the actual link (to the figure), the rest are parameters to ease the process in different roads. But this is not documented (like any other part of GGI at this moment) and we might have to ask directly if you want a definitive answer, @millerjeremya.

**Comment by flsimoes** [comment]
Hi @millerjeremya 

Here's Guido's answer:

> The link composes from the `captionStart` (or `captionStart-<X>`) attributes of `figureCitation`s, using the `captionText` (or `captionText-<X>`) attributes as the hover text ... if no `captionStart` or `captionStart-<X>` attribute is present, the XSLT falls back to "Figure".
> 
> In GGI, all the aforementioned attributes are set when marking a figure citation.
