### ISSUE TITLE
How to mark up common names?

### ISSUE THREAD

**Issue by truschel** [plazi/community#6]
How we should mark common names of species in the subSubSection attributes?

![image](https://user-images.githubusercontent.com/57402704/74772039-0612d880-526e-11ea-8626-825c2eae7a61.png)

**Comment by myrmoteras** [comment]
subSubSection type=vernacular_name and the vernacular name should be tagged with "vernacularName"

**Comment by myrmoteras** [comment]
In poa we then could ask guido whether there are attributes for language etc.

**Comment by truschel** [comment]
Thank you Donat!
