### ISSUE TITLE
Caption in text

### ISSUE THREAD

**Issue by millerjeremya** [plazi/community#60]
I found an instance where a figure caption is embedded in the main text. To troubleshoot, I tried cutting the text stream before this happens, then re-selecting the successor. But this didn't fix the problem. What am I missing? 
This caption is just fine in the figures section. Note that this was a document that you recently helped me with regarding multipage figures and captions with word order problems; thought that could be relevant. 
Treatment: http://treatment.plazi.org/GgServer/html/9A3A87D00B580DE5FA0DA2503C52F408
Source: http://treatment.plazi.org/GgServer/summary/6603FFA80B5D0D64FFF6AB533D39FF9A

![image](https://user-images.githubusercontent.com/4322250/107040953-31187400-67c0-11eb-91c3-7ef9b6f7ea5a.png)

![image](https://user-images.githubusercontent.com/4322250/107040528-9f106b80-67bf-11eb-84e2-8e87844b1cee.png)

![image](https://user-images.githubusercontent.com/4322250/107040562-ab94c400-67bf-11eb-81e2-b8ec29d83037.png)

**Comment by flsimoes** [comment]
I believe this is a glitch of some sort.
I took a look at that section and it looks fine to me. I removed the `block` and `paragraph` regions of the Caption, let's wait and see if it solves this.

**Comment by flsimoes** [comment]
So no, it didn't fix the problem. I guess this is something that only Guido will know what to do.

**Comment by mguidoti** [comment]
@myrmoteras pinging you here too.

**Comment by flsimoes** [comment]
This has been fixed since
