### ISSUE TITLE
Explosion of collectors in recordedBy

### ISSUE THREAD

**Issue by dshorthouse** [plazi/community#61]
This one has an explosion of collectors listed in recordedBy.

**Context**
[GBIF occurrence](https://www.gbif.org/occurrence/3017727567)
[Plazi reference](http://treatment.plazi.org/id/039C342A6E0EEC47FF1E64A2FC9EF955)

**Comment by mguidoti** [comment]
Hi @dshorthouse, 

Thanks for reporting. The issue is caused by three materialsCitations only, and the fix is on the way. 

Best,

**Comment by mguidoti** [comment]
@dshorthouse https://www.gbif.org/occurrence/3017727567 seems ok now. 

Thanks once again for reporting it!
