### ISSUE TITLE
Wrong authorship in DwCA

### ISSUE THREAD

**Issue by mdoering** [plazi/community#64]
This name has a wrong authorship in the DwC data. The verbatim scientificName is correct though.
Removing the basionym parenthesis is most problematic:

```
scientificName = Paraserthianthes lophantha Willd. C. Nielsen
scientificNameAuthorship = Willd. C. Nielsen
verbatimScientificName = Paraserthianthes lophantha (Willd.) I. C. Nielsen
```
http://treatment.plazi.org/id/039287B6FFBB6350B233E82BFC0B5092

https://www.gbif.org/species/169094292/verbatim

**Comment by myrmoteras** [comment]
ok - should be fixed

**Comment by mdoering** [comment]
Thanks! @gsautter, is this maybe a systematic, programmatic error that needs a review?

**Comment by myrmoteras** [comment]
@mdoering in this case it might be a manual edit, because these are unusual treatments. It doesn't mean we should ask this questions,  and will.

**Comment by gsautter** [comment]
For what it looks like, this is more of a data problem, namely in how the `authorityName` and `baseAuthorityName` attributes are set in http://treatment.plazi.org/GgServer/xml/039287B6FFBB6350B233E82BFC0B5092 ...

However, there also seems to have been a programmatic problem in the handling of basionym authorities ... fixed now, and the DwC-A looks better ... @mdoering please check.

Also corrected the authorities of the other taxa in this document.

**Comment by mdoering** [comment]
Thanks! I've scheduled it for reimport

**Comment by gsautter** [comment]
> Thanks! I've scheduled it for reimport

Shouldn't that happen automatically on a request to `.../crawl`? Our exporter makes that call whenever a DwC-A is updated ...

**Comment by mdoering** [comment]
if you always hit crawl then yes it was redundant

**Comment by gsautter** [comment]
OK, then the implementation does it right ... thanks for clarifying.
