### ISSUE TITLE
10 insect genera spotted in plants

### ISSUE THREAD

**Issue by mdoering** [plazi/community#65]
These 10 genera coming from Plazi come in as plants, most as Fabaceae, when in fact they are insects.
The first dataset I verified seems to have mixed genera from Animalia and Plantae so I suspect this is a species interaction problem, feeds on, host plant, etc.

 - [Clodionus](https://www.gbif.org/species/8440255) from [The first Aleyrodidae from the Lowermost Eocene Oise amber (Hemiptera: Sternorrhyncha)](https://www.gbif.org/dataset/5f0653f2-d47e-439c-93c8-95b9c1a0d3fe)
 - [Eurycoplangiodes](https://www.gbif.org/species/10700374) from [Orthoptera Tettigoniidae (Conocephalinae, Hexacentrinae, Phaneropterinae Mecopodinae, Hetrodinae) from some protected areas of Central African Republic](https://www.gbif.org/dataset/108a5b4b-23db-4b34-93a3-7effb973414e)
 - [Isaraselis](https://www.gbif.org/species/8695467) from [The first Aleyrodidae from the Lowermost Eocene Oise amber (Hemiptera: Sternorrhyncha)](https://www.gbif.org/dataset/5f0653f2-d47e-439c-93c8-95b9c1a0d3fe)
 - [Lukotekia](https://www.gbif.org/species/8586537) from [The first Aleyrodidae from the Lowermost Eocene Oise amber (Hemiptera: Sternorrhyncha)](https://www.gbif.org/dataset/5f0653f2-d47e-439c-93c8-95b9c1a0d3fe)
 - [Odontotarsiellus](https://www.gbif.org/species/9506496) from [An annotated catalog of the Iranian Pentatomoidea (Hemiptera: Heteroptera: Pentatomomorpha)](https://www.gbif.org/dataset/533c476d-abac-4e19-ac8b-e636e2dd8bda)
 - [Oisedicus](https://www.gbif.org/species/8561722) from [The first Aleyrodidae from the Lowermost Eocene Oise amber (Hemiptera: Sternorrhyncha)](https://www.gbif.org/dataset/5f0653f2-d47e-439c-93c8-95b9c1a0d3fe)
 - [Psammotisia](https://www.gbif.org/species/9581326) from [An annotated catalog of the Iranian Pentatomoidea (Hemiptera: Heteroptera: Pentatomomorpha)](https://www.gbif.org/dataset/533c476d-abac-4e19-ac8b-e636e2dd8bda)
 - [Risibia](https://www.gbif.org/species/9387571) from [An annotated catalog of the Iranian Pentatomoidea (Hemiptera: Heteroptera: Pentatomomorpha)](https://www.gbif.org/dataset/533c476d-abac-4e19-ac8b-e636e2dd8bda)
 - [Taphocerus](https://www.gbif.org/species/9444719) from [An annotated catalogue of the Coleoptera types deposited in the National Insect Collection (CNIN) of the National Autonomous University of Mexico](https://www.gbif.org/dataset/607932e4-c3eb-42a7-ae75-a68dbcd4064a)
 - [Stosicthrips](https://www.gbif.org/species/8609577) from [New taxa and new records of Australian Panchaetothripinae (Thysanoptera, Thripidae)](https://www.gbif.org/dataset/ae548dde-aa3e-4c6d-b70b-0608aa3f316a)
 - [Trichromoithrips](https://www.gbif.org/species/10569926) from [Trichromothrips genus-group (Thysanoptera, Thripidae) from China, with descriptions of three new species and ten new records](https://www.gbif.org/dataset/0f26b1ea-8fb2-4ef4-ba99-ccc81dc1ad50)

**Comment by mdoering** [comment]
These misplacements across kingdoms have a considerable impact on the quality of the GBIF taxonomy.
Can we think of a way to avoid them? Maybe flag datasets for manual review in case they span several kingdoms? I assume entire journals should often even be restricted to a certain kingdom or at least nomenclatural code. Is that a way to flag problematic datasets for manual review?

**Comment by myrmoteras** [comment]
this is interesting: just the last case, there is one that is wrong, need to explore more to understand what makes this happening.


http://tb.plazi.org/GgServer/srsStats/stats?outputFields=doc.uuid+doc.articleUuid+tax.name+tax.phylumEpithet+tax.classEpithet+tax.orderEpithet+tax.familyEpithet+tax.genusEpithet&groupingFields=doc.uuid+doc.articleUuid+tax.name+tax.phylumEpithet+tax.classEpithet+tax.orderEpithet+tax.familyEpithet+tax.genusEpithet&FP-doc.articleUuid=BB06FF93EB76FFFBFF8E2E36FF8CFFDB&format=HTML


http://tb.plazi.org/GgServer/srsStats/stats?outputFields=doc.uuid+doc.articleUuid+bib.title+tax.name+tax.phylumEpithet+tax.classEpithet+tax.orderEpithet+tax.familyEpithet+tax.genusEpithet&groupingFields=doc.uuid+doc.articleUuid+bib.title+tax.name+tax.phylumEpithet+tax.classEpithet+tax.orderEpithet+tax.familyEpithet+tax.genusEpithet&FP-doc.articleUuid=3F24823C545CFFF8C15A2E33FF9A1177&format=HTML

http://tb.plazi.org/GgServer/srsStats/stats?outputFields=doc.uuid+doc.articleUuid+bib.title+tax.name+tax.phylumEpithet+tax.classEpithet+tax.orderEpithet+tax.familyEpithet+tax.genusEpithet&groupingFields=doc.uuid+doc.articleUuid+bib.title+tax.name+tax.phylumEpithet+tax.classEpithet+tax.orderEpithet+tax.familyEpithet+tax.genusEpithet&FP-doc.articleUuid=FA7E2A39FFC4FFF3FFD3067BFFF2FFC5&format=HTML

**Comment by myrmoteras** [comment]
is fixed 
 Trichromoithrips from Trichromothrips genus-group (Thysanoptera, Thripidae) from China, with descriptions of three new species and ten new records  http://tb.plazi.org/GgServer/summary/BB06FF93EB76FFFBFF8E2E36FF8CFFDB

**Comment by mdoering** [comment]
is phylum Tracheophyta for _Stosicthrips szitas_ correct?

**Comment by myrmoteras** [comment]
of course not - thank for pointing it out

Just wondering: You write above about `considerable impact`. I wonder, whether there is a difference between when we enter new species, new genera like in the above case of _Stosicthrips szitas_where we are the sole provider of the time being of these taxa, and just a taxon for which you already have a taxon in your backbone.

**Comment by mdoering** [comment]
It depends on how we identify a name as being the same name. The classification mostly plays not much role, but we need to decide if a name could be a homonym and cannot in all cases count on an authorship. So the kingdom does play a kew role for us in that decision. In the case of Stosicthrips for example we created a redundant plant genus: https://www.gbif.org/species/search?q=Stosicthrips&rank=GENUS

The classification below is (currently) not that much of an issue - unless as you say the name is coming in via Plazi only. In that case the classification is taken from you guys further down the hierarchy.

**Comment by guilhermepcoelho** [comment]
I fixed all names wrongly assign to Plantae in these datasets. Soon it should be correct in GBIF.
