### ISSUE TITLE
taxonomicName higher categories: fixing errors

### ISSUE THREAD

**Issue by myrmoteras** [plazi/community#67]
see issue 
* https://github.com/plazi/community/issues/65 wrong higher categories
* https://github.com/plazi/community/issues/66

here is the list of articles with 2 or more kingdoms in the nomenclature section that need be fixed:

https://tb.plazi.org/GgServer/dioStats/stats?outputFields=doc.articleUuid+doc.name+doc.doi+doc.uploadUser+doc.uploadDate+doc.updateUser+doc.updateDate+cont.pageCount+cont.treatCount+treat.kingdomEpithet&groupingFields=doc.articleUuid+doc.name+doc.doi+doc.uploadUser+doc.uploadDate+doc.updateUser+doc.updateDate+cont.pageCount+cont.treatCount&orderingFields=-doc.uploadDate&FP-treat.kingdomEpithet=0-&AP-treat.kingdomEpithet=2-&format=HTML

**Comment by myrmoteras** [comment]
@flsimoes this just come in from 
https://github.com/gbif/portal-feedback/issues/2727#issuecomment-802885900

thanks for taking care of
d
Genera | DOI(s) of the dataset    concerned
-- | --
Neopicobia   and Rafapicobia | https://doi.org/10.11646/zootaxa.4113.1.1,   https://doi.org/10.15468/ad9psd
Tyrannidectes | https://doi.org/10.5281/zenodo.203166,   https://doi.org/10.15468/b6e5m8

**Comment by flsimoes** [comment]
> @flsimoes this just come in from
> [gbif/portal-feedback#2727 (comment)](https://github.com/gbif/portal-feedback/issues/2727#issuecomment-802885900)
> 
> thanks for taking care of
> d
> 
> Genera	DOI(s) of the dataset concerned
> Neopicobia and Rafapicobia	https://doi.org/10.11646/zootaxa.4113.1.1, https://doi.org/10.15468/ad9psd
> Tyrannidectes	https://doi.org/10.5281/zenodo.203166, https://doi.org/10.15468/b6e5m8

No worries, will take a look at these.
F

**Comment by flsimoes** [comment]
I understand that Guido went and correct these.
