### ISSUE TITLE
Explosion of content in recordedBy

### ISSUE THREAD

**Issue by dshorthouse** [plazi/community#69]
As in the subject and in addition to this, the content in recordedBy looks like localities. So, there may be other underlying parsing problems.

**Context**
[GBIF occurrence](https://www.gbif.org/occurrence/2831262414)
[Plazi reference](http://treatment.plazi.org/id/131D87EFFF86FFA8FFDC5EDDFD3FFA42)

**Comment by flsimoes** [comment]
@dshorthouse Thank you very much for pointing this out!

I've just finished fixing these collector/recordedBy errors and the changes should be up shortly.
