### ISSUE TITLE
explosion of recordedBy from treatment published April 2021

### ISSUE THREAD

**Issue by dshorthouse** [plazi/community#70]
Parsing of content for eventDate and recordedBy in this very recent treatment made an explosion.

**Context**
[GBIF occurrence](https://www.gbif.org/occurrence/3067212367)
[Plazi reference](http://treatment.plazi.org/id/CCEC59C83A665AEC99DF4D76776EB82B)

**Comment by mguidoti** [comment]
Thanks for reporting this! 

We started to process material citations from Pensoft journals, and, we might get some issues until we are fully adapted. But we're already looking into it, and will fix it in a timely manner.

**Comment by dshorthouse** [comment]
Thanks @mguidoti. What are the criteria for processed material to be acceptably released to GBIF?

**Comment by dshorthouse** [comment]
Sorry, was inadvertently clicking buttons.

**Comment by mguidoti** [comment]
No worries. 

So, we have several different rules blocking the data transit to GBIF, regarding material citations alone as you can see in the print below:

https://files.slack.com/files-pri/T0181V6AW8L-F01U6LR0CQ5/image.png

This is from the QC dialog in GGI and these rules were added by Oct-Nov, last year. The novelty here is the fact that this is a Pensoft import, meaning, it's coming from a XML and not a processed PDF. As said, we are just starting with the processing of matCits from these Pensoft imports and I've a feeling that it haven't passed through the "gatekeeper" like it's suppose to. If so, the transit would have been blocked and we would have to manually curate the paper before letting it go to GBIF - which is our normal workflow now.

So we are checking it and not only fixing it. 

As soon as possible we'll get back to you here.

**Comment by flsimoes** [comment]
This has now been fixed, should be updated on GBIF shortly
