### ISSUE TITLE
List of collectors in recordedBy not present in treatment

### ISSUE THREAD

**Issue by dshorthouse** [plazi/community#71]
The list of collectors parsed for this specimen record & included in recordedBy is more expansive than that mentioned in the treatment.

**Context**
[GBIF occurrence](https://www.gbif.org/occurrence/2960754305)
[Plazi reference](http://treatment.plazi.org/id/84783E54FFA7FFC8AFD07CC1FE077115)

**Comment by flsimoes** [comment]
Thanks for reporting this one!
Also, sorry for the delay in replying @dshorthouse
 
I corrected the errors you mentioned. It might take a while for the changes to show up on GBIF though.
