### ISSUE TITLE
Explosion of recordedBy in this one

### ISSUE THREAD

**Issue by dshorthouse** [plazi/community#72]
Please leave your comment here...

**Context**
[GBIF occurrence](https://www.gbif.org/occurrence/3067212316)
[Plazi reference](http://treatment.plazi.org/id/CCEC59C83A665AEC99DF4D76776EB82B)

**Comment by flsimoes** [comment]
Hi @dshorthouse 
If I'm not mistaken this is the same as https://github.com/plazi/community/issues/70 isn't it?

I had a look at our end and almost all the materialsCitations had already been corrected (there's only one of them that looks incorrect to me), though the GBIF entry wasn't updated (as can be seen in the link you sent us).

Here's our stats link with the materials verbatim:
http://tb.plazi.org/GgServer/srsStats/stats?outputFields=doc.uuid+tax.name+matCit.collector&groupingFields=doc.uuid+tax.name+matCit.collector&FP-doc.uuid=CCEC59C83A665AEC99DF4D76776EB82B&format=HTML

**Comment by dshorthouse** [comment]
@flsimoes Same class of error yes, but different record. Thanks for having a look.

**Comment by flsimoes** [comment]
Fixed with #70
