### ISSUE TITLE
Plant with incorrect higher taxonomy

### ISSUE THREAD

**Issue by ManonGros** [plazi/community#73]
Hi Plazi team!

One of our GBIF users noticed an issue with the higher taxonomy of Spartina patens Aiton, 1817 which is a plant but is classified as an insect (https://www.gbif.org/species/10857569). See this issue https://github.com/gbif/portal-feedback/issues/3478

We integrated this species and associated taxonomy from this dataset https://www.gbif.org/dataset/7a684426-15d9-4d60-9e1e-a5c182e5b17b (https://doi.org/10.3897/phytokeys.10.2734). Would it be possible to take a look?
Thanks!

**Comment by truschel** [comment]
Hi @ManonGros 
I'll take a look and let you know when I resolve the issue.

**Comment by flsimoes** [comment]
@ManonGros 
We've corrected that and all _Spartina_ occurrences in this publication. Please bear in mind that changes sent to GBIF might take a few hours to come into effect.

**Comment by ManonGros** [comment]
Wonderful! Thank you both!

There is a second somewhat similar issue concerning an other dataset: https://github.com/gbif/portal-feedback/issues/3476

The dataset is this one: https://www.gbif.org/dataset/834831a3-c0b8-44fa-b357-c14c05822909
One of the taxa included in the dataset, a moth, is shown with a plant higher taxonomy. Could you take a look?
Thanks!

**Comment by ManonGros** [comment]
Thank you both for being so quick, hopefully we will have a GBIF backbone update soon enough so those changes will be visible there as well.
