### ISSUE TITLE
Enable discussions for this repo

### ISSUE THREAD

**Issue by retog** [plazi/community#74]
- [x] Enable discussions
- [x] Refrence in readme
- [x] convert question/discussion issues to discussions

**Comment by mguidoti** [comment]
Thanks for the reminder, @retog. I already activated `Discussions` here and updated the README. Could you please check if I missed anything?

@flsimoes could you coordinate with someone in the team to move the discussions from `Issues` to `Discussions`? 

Thanks!

**Comment by retog** [comment]
![image](https://user-images.githubusercontent.com/110756/123806579-5cc30480-d8ef-11eb-8715-76dc933756d5.png)
The issue seems a left-over here, but as issues can also be raised, it might good to explain when to choose which.

I would suggest: 
- Issue: a request for something to be different. The issue describes what there is now and what there should be instead. 
- Discussions: questions and everything else.

**Comment by mguidoti** [comment]
You're right, I'm on it. 

Thanks for pointing it out.

**Comment by mguidoti** [comment]
Done, @retog. 

Decided to create specific `md` files showing how to create a Discussion topic or Issue and linked them back to the README, which is cleaner and easier to follow now. 

What do you think?

Best,

**Comment by debpaul** [comment]
@mguidoti I'm watching how you all implement the new Discussion feature that GitHub has added. (I installed it in a private repo to try it). Hope this proves useful for many of us using GitHub.

**Comment by mguidoti** [comment]
Hi @debpaul, thanks for the interest! 

Moving to Discussions was actually @retog's idea, I'm only implementing it here with @flsimoes help. I think this will make this repo better organized. We can even classify the different discussions, and we can assign the selected answer in the ones marked as Q&A - pretty cool!

**Comment by retog** [comment]
Thanks @mguidoti, I think it's very well done now. Let's hope this will lead to fruitful discussions and Plazi more effective in liberating data!
