### ISSUE TITLE
processing 10.1016/j.ympev.2011.02.017

### ISSUE THREAD

**Issue by myrmoteras** [plazi/community#85]
@flsimoes @mguidoti can you please look into this article that just got mentioned in taxacom. 
[molecularPhylogeneticsEvolution.59.2.320-330.pdf](https://github.com/plazi/community/files/6922053/molecularPhylogeneticsEvolution.59.2.320-330.pdf)

in the appendix there are two sections that are of interest.
A has all the materials examined, including accession codes etc.

B has all the nomenclatural changes.

It would be good to process this and to use as an example, also for the discussion in BiCIKL, and with Joe at GBIF about linking phylogenies to occurrences.

Let us discuss how to deal with this

P.S. this is an interesting example, where Rod tried to make a point that a link to a treatment is meaningless. 

> Hi Donat, 
> 
> I’ll leave it to John to decide whether the links you provide are the sort of thing he was after.
> 
> If we think of all these interconnected facts as nodes and edges in  a “knowledge graph”, then we’re all working on the same thing, just focussing on different nodes, based on a combination of what we think matters and what our skills and resources are. 
> 
> Obviously we may view the same things differently. If the goal is to provide article level citations then the often cryptic treatment-style citations in taxonomy are an obstacle (what article does  "Molec. Phylogen. Evol. 59(2): 328” refer to?). If treatment citations are the goal, then a citation like:
> 
> Coughenour, J. M., Simmons, M. P., Lombardi, J. A., Yakobson, K., & Archer, R. H. (2011). Phylogeny of Celastraceae subfamily Hippocrateoideae inferred from morphological characters and nuclear and plastid loci. Molecular Phylogenetics and Evolution, 59(2), 320–330. doi:10.1016/j.ympev.2011.02.017
> 
> is the wrong level of granularity. I think both are useful.
> 
> Regards,
> 
> Rod
> 

and here my answer

> Hi Rod
> 
> Thanks for this example. I agree only insofar that we need the article citation. But in todays digital world a citation is not helpful, illustrated by your example, Coughenour, J. M., Simmons, M. P., Lombardi, J. A., Yakobson, K., & Archer, R. H. (2011). Phylogeny of Celastraceae subfamily Hippocrateoideae inferred from morphological characters and nuclear and plastid loci. Molecular Phylogenetics and Evolution, 59(2), 320-330. doi:10.1016/j.ympev.2011.02.017 which leads to a closed access article https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdoi.org%2F10.1016%2Fj.ympev.2011.02.017&amp;data=04%7C01%7C%7C8710e7536bad4ea95e0808d9564deb89%7Cbe0003e8c6b9496883aeb34586974b76%7C0%7C0%7C637635714947181952%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&amp;sdata=uAZsl4AnxlpR905Z%2BfG6M6ngDhELWdKs2zgmfNOspbA%3D&amp;reserved=0
> 
> Whilst a taxonomic name and the Molec. Phylogen. Evol. 59(2): 328, for example for Pristimera dewildemaniana (N.Hallé) R.H.Archer refers to a treatment:
> 
> Pristimera dewildemaniana (N.Hallé) R.H.Archer, comb. nov.
> Simirestis dewildemaniana N.Hallé, Bull. Mus. Nat. Hist. Nat., Sér 2,
> 30: 465 (1958). Hippocratea dewildemaniana (N.Hallé) J.B. Hall, Kew. Bull. 35: 841 (1981). Simirestis dewildemaniana N.Hallé, Mem. Inst. Franc. Afr. Noire 64: 71 (1962). -TYPE: Democratic Republic of Congo, Central Forest, Lesse, Bequaert 4154 (BR, holo.).
> Hippocratea affinis De Wild., Pl. Bequaert 2: 61 (1923).
> 
> which includes another plethora of links that is essentially an essential part of the catalogue.
> 
> A treatment citation is not at all cryptic but rather clear. The problem is that the current citation style to refer to an article is cumbersome, but once we made the treatments citable, this will be open, save time for anybody else interested in Pristimera dewildemaniana (N.Hallé) R.H.Archer, Molec. Phylogen. Evol. 59(2): 328.
> Essentially anybody cataloguing makes the effort to find the treatments, but then discards it.
> 
> Donat
>

**Comment by flsimoes** [comment]
Donat processed this one himself:

TB: https://tb.plazi.org/GgServer/summary/A05F2F68FFB99B2BFFE3FF92FFF7FFA6
Zenodo: https://zenodo.org/record/5155694
GBIF: https://www.gbif.org/dataset/9f08fae6-4e03-4823-988c-2076eddd45f5
