### ISSUE TITLE
Trying to make sense of a treatment

### ISSUE THREAD

**Issue by rdmpage** [plazi/community#86]
I'm trying to make sense of a treatment that was highlighted on the Plazi home page. The treatment is [Lathrobium guangdongense Peng & Li, 2014,](http://tb.plazi.org/GgServer/html/FFD27766BC125A82B1EC7A30EE0E0610) 

I have the following problems:
- a specimen from China is displayed in the Atlantic
- there doesn't seem to be any reason for this based on the treatment data
- Plazi tells me my browser doesn't support Google Maps, which is incorrect
- There are no occurrences in the GBIF record or the Darwin Core archive, despite the XML having material citations.

First off the insect is from China but on the home page appears in the Atlantic.

![Screenshot 2021-08-03 at 18 23 38](https://user-images.githubusercontent.com/83306/128059466-de313aad-2ce2-46ee-bbe2-685f28677b42.png)

These things can happen, especially if the longitude is set to the wrong hemisphere. So I looked at the treatment and couldn't see anything obvious, everything seems to be in the eastern hemisphere. When I try to click on a "GoogleMaps" link I get this:

![Screenshot 2021-08-03 at 18 24 27](https://user-images.githubusercontent.com/83306/128059777-2f9d6acb-cc80-4990-a24f-3b935ea7dd0e.png)

My browser does, in fact, support Google Maps, but no matter whether I tried Safari, Firefox, or Chrome on my Mac (10.14.6) they all display the same message.

I then look at the GBIF record https://www.gbif.org/dataset/72182565-897c-4bd9-aa86-463d967f55bc and there is no map. Yet the XML for this treatment has material citations http://tb.plazi.org/GgServer/xml/FFD27766BC125A82B1EC7A30EE0E0610 with latitude and longitudes.

Not sure what has happened, but something seems amiss with this treatment.

**Comment by flsimoes** [comment]
I'll take a look right away. Please bear with me while I check it.

**Comment by rdmpage** [comment]
@flsimoes Thanks!

**Comment by flsimoes** [comment]
@rdmpage Found the problem!
For some reason the elevation data on the last of these materialsCitations was wrongly marked as lat/long (as you can see, the elev. is 1,270-1,570 so you can easily picture why it ended up in the middle of the Atlantic). This is fixed in our end now, not sure how long it takes for all the cascade changes to take effect though.

Regarding Google Maps integrations, unfortunately that's not much up my aisle. @myrmoteras might be able to help you best with that.
