### ISSUE TITLE
font decoding issue ®rst instead of first

### ISSUE THREAD

**Issue by myrmoteras** [plazi/community#88]
in this article there is a font decoding issue decoding `first` as `®rst` https://tb.plazi.org/GgServer/html/03DE3D65F47BC61B9050A44A4A76382C

https://tb.plazi.org/GgServer/summary/FFE7451DF45CC63C914CA755481B3C2A

did not check whether this is specific to this treatment, article or journal

**Comment by flsimoes** [comment]
I believe this happens rarely for the earlier years of this journal.
Did some fixing on this particular one.

**Comment by flsimoes** [comment]
This one has a lot of decoding issues (good part of the text is as `artifact`), will require a lot of manual fixing.

**Comment by debpaul** [comment]
> This one has a lot of decoding issues (good part of the text is as `artifact`), will require a lot of manual fixing.

Need a way to route these to humans willing to work on them?

**Comment by flsimoes** [comment]
> > This one has a lot of decoding issues (good part of the text is as `artifact`), will require a lot of manual fixing.
> 
> Need a way to route these to humans willing to work on them?

Sorry @debpaul guess your reply slipped by me.
I guess that would require some training to start with. @myrmoteras

**Comment by mguidoti** [comment]
Hi @debpaul, @flsimoes, 

Plazi has a ongoing project to create a comprehensive self-guided, web-based training program. Moreover, we are working on other entry points to this world other than GGI (I'm talking about easier-to-learn tools to edit IMFs). 

So, if today we need to provide 1:1 attention to walk the interested ones into this world, soon we will have a more coordinated and organized way to provide an independent experience in terms of learning and contributing.
