### ISSUE TITLE
Insecta Mundi 0720 - Possible treatments

### ISSUE THREAD

**Issue by flsimoes** [plazi/community#9]
Can the entries in this particular publication be considered treatments?

[Insecta Mundi 0720](https://drive.google.com/open?id=1XQhmZd-FnePaHj5BbJUgV8JK44EXf94g)
[UUID](http://publication.plazi.org/id/885B9859FFEEFFCFFFEB1955FF91FFDF)

One could argue that the publication only comments on the biology of the taxa. However, even if they do not seem to be describing taxonomic details, this type of discussion/description will eventually appear as a treatment citation in future publications, thus making a case for it to be considered a treatment now.

**Comment by myrmoteras** [comment]
yes.
these sort of treatments are important for mining of host species, etc. We need to keep a list of such articles. I normally add them here. @mguidoti could also help to curate a list of exemplar articles/treatments that we later could use for discussions, demos, etc.

**Comment by myrmoteras** [comment]
here is the entry in the demo cases wikipage https://github.com/plazi/Plazi-Communications/wiki/Demo-cases-and-FAQ#articles-including-treatments-that-list-hostparasite-species-relation
