### ISSUE TITLE
Name provided in checklist doesn't match content of treatment

### ISSUE THREAD

**Issue by ManonGros** [plazi/community#93]
This issue was originally reported here, a little bit differently: https://github.com/gbif/backbone-feedback/issues/360

The dataset concerned is this one: https://doi.org/10.5281/zenodo.291971 / https://www.gbif.org/dataset/81656d78-6689-4555-9a97-f8503ee08776

The treatment for this species (https://www.gbif.org/species/7325030/treatments) specifies that:
1. the original name is Bromus giganteus Linnaeus
2. the current accepted name is Festuca gigantea (L.) Vill.

However, the name given in the checklist is `Festuca gigantea Linnaeus, 1753` (which doesn't match any of the names mentioned above).
Would it be possible to check the dataset and perhaps update the name to Festuca gigantea (L.) Vill.?

**Comment by myrmoteras** [comment]
ok - I will look into this

**Comment by jugiora** [comment]
The names are fixed but the GBIF updates can take a while.
