### ISSUE TITLE
Homo bodoensis

### ISSUE THREAD

**Issue by mdoering** [plazi/community#95]
A new hominin species, maybe worth a manual markup?
https://onlinelibrary.wiley.com/doi/10.1002/evan.21929

**Comment by Carol-Sokolowicz** [comment]
[GBIF data](https://www.gbif.org/dataset/85a52735-5112-4407-b9bb-61dd3b03962d)

**Comment by myrmoteras** [comment]
Interesting that there are no figures

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by flsimoes** [comment]
I think this is still on the way as well

**Comment by flsimoes** [comment]
@Carol-Sokolowicz Can you double-check the figures and specially figureCitations on this one? They are still not showing up on TB or GBIF

**Comment by Carol-Sokolowicz** [comment]
I think I might have worked now.
Figure 1 is not cited inside the treatment.
