### ISSUE TITLE
termites of guam: bibiliographic data in GBIF needs corrections?

### ISSUE THREAD

**Issue by myrmoteras** [plazi/community#96]
The deposition of this article in GBIF needs some input in regards of the metadata which seems odd.

https://treatment.plazi.org/id/03E787F1B713A955FEFE90B4F92CF770

https://www.gbif.org/dataset/9b2056ec-f71b-4ff8-b642-e7aed6aa0eeb

![image](https://user-images.githubusercontent.com/4609956/139590553-e118a036-7c8f-4b73-821e-785159ca9d68.png)

https://treatment.plazi.org/GgServer/summary/FFDEFF89B713A955FFD59822FF8CFF82

check whether this is a more generic issue for this project?

**Comment by flsimoes** [comment]
Just removed that wrong bit from the metadata. Should be updated soon
