### ISSUE TITLE
Overly precise dates and elevations for specimen

### ISSUE THREAD

**Issue by rdmpage** [plazi/community#98]
For _Bironium taurus_, Löbl, 2021 https://tb.plazi.org/GgServer/html/03AE7920FF89FFE950DCFA0707BB4FBB (see https://plazi-tester.herokuapp.com/?uri=03AE7920-FF89-FFE9-50DC-FA0707BB4FBB ) the parser has stripped ranges from the date and elevation. 

```
Type material. Holotype ♂, IRIAN JAYA Jayawijaya Prov., Borme . 1000– 1300 m, 13– 18.VIII.92, leg. A. Riedel ( MHNG).
```

The elevation is 1000-1300 m but this is interpreted as `1300 m`. The date is 13–18.VIII.92 but this is interpreted as `1992-08-18`.

**Comment by flsimoes** [comment]
> For _Bironium taurus_, Löbl, 2021 https://tb.plazi.org/GgServer/html/03AE7920FF89FFE950DCFA0707BB4FBB (see https://plazi-tester.herokuapp.com/?uri=03AE7920-FF89-FFE9-50DC-FA0707BB4FBB ) the parser has stripped ranges from the date and elevation.
> 
> ```
> Type material. Holotype ♂, IRIAN JAYA Jayawijaya Prov., Borme . 1000– 1300 m, 13– 18.VIII.92, leg. A. Riedel ( MHNG).
> ```
> 
> The elevation is 1000-1300 m but this is interpreted as `1300 m`. The date is 13–18.VIII.92 but this is interpreted as `1992-08-18`.

We are taking a look, but there was a wild hiccup with decoding the hyphens in this particular paper, thus causing some of these issues.

**Comment by rdmpage** [comment]
I understand, I’m assuming that under the hood Plazi is using regular expressions, and these often need tweaking. Yet another reason for having some sort of post-parsing checks.

**Comment by myrmoteras** [comment]
Yes, all our algorithms are regularly reviewed and modified if necessary, not least based on feedback we get.

There are checks in place, and extended if necessarily and possible  (Simoes F, Agosti D, Guidoti M 2021. Delivering Fit-for-Use Data: Quality control. Biodiversity Information Science and Standards 5: e75432. doi: [10.3897/biss.5.75432](https://doi.org/10.3897/biss.5.75543)
